<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-04-19">
<meta name="description" content="Tales Mançano Academic Website">

<title>Fichamento: Elites and the expansion of education in nineteenth-century Sweden – Tales Mançano</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ebcc418b19e6abcbe615d4e8be58f8e7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id="></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '', { 'anonymize_ip': true});
</script>


<!-- 

Load Academicons v1: https://jpswalsh.github.io/academicons/

-->

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">



<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">





<!---

The following code are needed to show dimension citation and altmetrics.

https://api.altmetric.com/embeds.html

https://badge.dimensions.ai/

--->



<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>



<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>



<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Fichamento: Elites and the expansion of education in nineteenth-century Sweden – Tales Mançano">
<meta property="og:description" content="Andersson e Berger (2019)">
<meta property="og:site_name" content="Tales Mançano">
<meta name="twitter:title" content="Fichamento: Elites and the expansion of education in nineteenth-century Sweden – Tales Mançano">
<meta name="twitter:description" content="Andersson e Berger (2019)">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Tales Mançano</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../posts.html">
 <span class="dropdown-text">Posts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../contact.html">
 <span class="dropdown-text">Contact</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-research" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Research</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-research">    
        <li>
    <a class="dropdown-item" href="../../publications.html">
 <span class="dropdown-text">List of Publications</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects.html">
 <span class="dropdown-text">Grants</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-outreach" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Outreach</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-outreach">    
        <li>
    <a class="dropdown-item" href="../../posts.html">
 <span class="dropdown-text">Presentations</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../files/2026-1-02-CV-Mancano-Tales.pdf"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/drganghe/quarto-academic-website-template" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../posts.xml" target="_blank"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#referência-apa-7" id="toc-referência-apa-7" class="nav-link active" data-scroll-target="#referência-apa-7"><span class="header-section-number">1</span> Referência APA 7</a></li>
  <li><a href="#entrada-bibtex" id="toc-entrada-bibtex" class="nav-link" data-scroll-target="#entrada-bibtex"><span class="header-section-number">2</span> Entrada BibTeX</a></li>
  <li><a href="#timestamp" id="toc-timestamp" class="nav-link" data-scroll-target="#timestamp"><span class="header-section-number">3</span> Timestamp</a></li>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  <li><a href="#introdução-pp.-14" id="toc-introdução-pp.-14" class="nav-link" data-scroll-target="#introdução-pp.-14"><span class="header-section-number">4</span> Introdução (pp.&nbsp;1–4)</a>
  <ul class="collapse">
  <li><a href="#problema-e-debate-16" id="toc-problema-e-debate-16" class="nav-link" data-scroll-target="#problema-e-debate-16"><span class="header-section-number">4.1</span> Problema e debate [§1–§6]</a></li>
  <li><a href="#literatura-e-hipóteses-711" id="toc-literatura-e-hipóteses-711" class="nav-link" data-scroll-target="#literatura-e-hipóteses-711"><span class="header-section-number">4.2</span> Literatura e hipóteses [§7–§11]</a></li>
  <li><a href="#caso-sueco-1218" id="toc-caso-sueco-1218" class="nav-link" data-scroll-target="#caso-sueco-1218"><span class="header-section-number">4.3</span> Caso sueco [§12–§18]</a></li>
  <li><a href="#estratégia-e-dados-1924" id="toc-estratégia-e-dados-1924" class="nav-link" data-scroll-target="#estratégia-e-dados-1924"><span class="header-section-number">4.4</span> Estratégia e dados [§19–§24]</a></li>
  </ul></li>
  <li><a href="#evidência-empírica-pp.-1323" id="toc-evidência-empírica-pp.-1323" class="nav-link" data-scroll-target="#evidência-empírica-pp.-1323"><span class="header-section-number">5</span> Evidência empírica (pp.&nbsp;13–23)</a>
  <ul class="collapse">
  <li><a href="#desigualdade-e-gasto-escolar-2529" id="toc-desigualdade-e-gasto-escolar-2529" class="nav-link" data-scroll-target="#desigualdade-e-gasto-escolar-2529"><span class="header-section-number">5.1</span> Desigualdade e gasto escolar [§25–§29]</a></li>
  <li><a href="#elite-fundiária-e-capitalista-3034" id="toc-elite-fundiária-e-capitalista-3034" class="nav-link" data-scroll-target="#elite-fundiária-e-capitalista-3034"><span class="header-section-number">5.2</span> Elite fundiária e capitalista [§30–§34]</a></li>
  <li><a href="#robustez-e-mecanismo-3540" id="toc-robustez-e-mecanismo-3540" class="nav-link" data-scroll-target="#robustez-e-mecanismo-3540"><span class="header-section-number">5.3</span> Robustez e mecanismo [§35–§40]</a></li>
  <li><a href="#interpretação-histórica-4145" id="toc-interpretação-histórica-4145" class="nav-link" data-scroll-target="#interpretação-histórica-4145"><span class="header-section-number">5.4</span> Interpretação histórica [§41–§45]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">6</span> Argumento Sintético</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: Elites and the expansion of education in nineteenth-century Sweden</h1>
<p class="subtitle lead">Andersson e Berger (2019)</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Economics of Education</div>
    <div class="quarto-category">Institutions</div>
    <div class="quarto-category">Development Economics</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 19, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>

<style>
.lang-toggle {
  position: fixed;
  top: 70px;
  right: 20px;
  z-index: 1000;
}
.lang-btn {
  background: transparent;
  border: 1px solid #666;
  border-radius: 4px;
  padding: 5px 12px;
  margin: 0 2px;
  cursor: pointer;
  font-size: 14px;
  transition: all 0.3s;
}
.lang-btn:hover {
  background: #f0f0f0;
}
.lang-btn.active {
  background: #0366d6;
  color: white;
  border-color: #0366d6;
}
.lang-content[lang]:not([lang="en"]) { display: none; }
.lang-content[lang="en"] { display: block; }
</style>
<section id="referência-apa-7" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="referência-apa-7"><span class="header-section-number">1</span> Referência APA 7</h2>
<p>Andersson, J., &amp; Berger, T. (2019). Elites and the expansion of education in nineteenth-century Sweden. <em>Economic History Review, 72</em>(3), 897–924.</p>
</section>
<section id="entrada-bibtex" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="entrada-bibtex"><span class="header-section-number">2</span> Entrada BibTeX</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Entrada BibTeX → AnderssonBerger2019
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="va">@article</span>{<span class="ot">AnderssonBerger2019</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span> = {Andersson, Jens and Berger, Thor},</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span> = {Elites and the expansion of education in nineteenth-century Sweden},</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">journal</span> = {Economic History Review},</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span> = {2019},</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">volume</span> = {72},</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">number</span> = {3},</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">pages</span> = {897--924},</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="dt">doi</span> = {10.1111/ehr.12738}</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section>
<section id="timestamp" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="timestamp"><span class="header-section-number">3</span> Timestamp</h2>
<p>Última atualização: 2026-04-19<br>
Modelo: Perplexity (Lazy cheap model (Grok?)) Gerado em: 2026-04-19T21:40:00-03:00</p>
</section>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v15.0</em>. A análise é adversarial sem ser destrutiva: identifica vulnerabilidades reais do argumento e reconhece contribuições genuínas com a mesma precisão. O raciocínio analítico subjacente a cada dimensão é registrado no campo <code>Raciocínio analítico</code> da tabela.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Instituição</td>
<td style="text-align: left;">O artigo explicita a afiliação institucional e torna transparente a autoria, o que ajuda a situar o contexto acadêmico do texto; não há, porém, nota biográfica sobre formação individual além da afiliação.</td>
<td style="text-align: left;">Lund University <a href="https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/111334221/20361269-5540-47e3-9f31-7ad221c675c9/Andersson-and-Berger-2019-Elites-and-the-expansion-of-education-in-nineteenth-century-Sweden.pdf?AWSAccessKeyId=ASIA2F3EMEYER3ILXUM5&amp;Signature=%2BQyM5ZVjsqkRP6YaiTSXWJY%2FWh0%3D&amp;x-amz-security-token=IQoJb3JpZ2luX2VjEEkaCXVzLWVhc3QtMSJHMEUCIQDilUDbv5Nac7mpQ24RhmQIqFpSXgoxUJJffdJDvyz5SgIgPxdjXNJ8Rt12pQrlACBNX%2F8cwO7Xds%2BGs8AkiSlpttkq8wQIEhABGgw2OTk3NTMzMDk3MDUiDKX7%2FkIdw3gyV31aGSrQBKvuq34K5uKiQCM4vsRycTnjOWHQ5I5QOTU%2Ft8yo4Cu%2BVLu262oDasiZbiNRcgqzmXU7h2AXXw7FoSUcBbsXj4KpA%2Fb8VhSgn26uU6KIjjWX0H615VZ%2BW0FGlNLaAsZxTb0a8fVdfAlnR8arS%2F6isGHFxsb2q%2BhlS1VnARuGaNld%2Fu51zYhwu7D%2FQhXbK4Ztkmu7uHPC2UBkhy8C2HdQh%2F0coiP3OYBZJ4WwTIKSKSd9vD72z9q1EaFdNVOvtoRSAQ1h0LFjBfT77CgUUvuHX5xYsmW%2B3sf2MqlpGcCLoMYrg4kJwuEC5sSDTVtf15o3wVs5hxahfqXEwJeE02K%2BmUElNEPlnYfU7eCb7jQumgzPXWFhxBYxQxAm29cw%2BoInWqITzChGns%2FKIy51Owa8Ym9vzbD1vZwgIVUGaFOBjgqfHFMpg0yAuzz0xXQtrl9nft03F2oyvHalQoh53FtvLbGUgWTP%2BXfdl8HXm99IxkDBSZxspegbgXqX9xZvZv0Gtn5TO6q%2FwjaDtkpTjWuY4Ti9AhpV5%2BMmaUGDA6IXNW3AvW7p5z4%2Bzzh7pX7QGi5lZnTPND746I5ToxHWOAOY8BJNCeGx4lR8or%2BgFH1DqhUeK2PwJr3yvstYBd5UjSihKArClr0N0ucDcjx1NEjgtq0F55%2B%2BJpVqhJOm0XFFwMtwiVjt7stTcKhvsECgYruwtAS6H9%2F3BJSFhO8iBxD8GojQ0PfRJ3A1BgX4nOpkPXwaLfXRSo9IC9xpeJvg3dLCwArWC%2FXTUkxCVQgZL7vIjOcw3uiVzwY6mAGQ2828jdIDAl9zOWD4j1Eb%2BQvvfnh%2BcgkmxH%2BCHWFmh%2FKQ3bllUqJSltM%2BJj30%2Bkoy%2Fd0Gnp4tNrTtVONoxTomd0XoP%2BnzU%2Bd%2BBy1%2BJG0rbCMcga07B6MrVLq70iMkd3dAgpySwattPhMgt7ts5mbM%2BtWk6fJUnaeKbxXt%2BBNoboD1GrEzM2pLfHjhohQmGrnmCiv3dSdlgg%3D%3D&amp;Expires=1776646272">ppl-ai-file-upload.s3.amazonaws</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">A questão central é explicitada logo na introdução: entender como a distribuição do poder político local afetou o gasto em escolarização primária. Trata-se de uma pergunta explicativa, com componente comparativo histórico.</td>
<td style="text-align: left;">Como a distribuição de poder político nos governos locais moldou o gasto em <em>folkskola</em> na Suécia antes do “industrial breakthrough”</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">O texto desdobra a pergunta central em questões auxiliares sobre se a desigualdade de votos aumenta o gasto escolar, se esse padrão é explicado por elites fundiárias ou capitalistas, e se industrialização ou difusão do sufrágio explicam a variação observada.</td>
<td style="text-align: left;">Se a desigualdade de votos se associa ao gasto educacional; se a associação vem de elites fundiárias ou capitalistas; se industrialização, riqueza ou ampliação do voto explicam os padrões</td>
</tr>
<tr class="even">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O puzzle é genuíno porque confronta duas expectativas rivais da literatura: elites como bloqueadoras ou como promotoras da escolarização. Ele é generalizável além do caso sueco, mas o artigo o trata por meio de um caso histórico específico e institucionalmente singular.</td>
<td style="text-align: left;">Puzzle explicativo sobre mudança institucional e provisão de bem público; debate entre elite obstruction e elite support</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">A tese é precisa: elites fundiárias, e não capitalistas, estiveram associadas a maior investimento em educação primária. O que sustenta a descoberta é a associação robusta em regressões e verificações de robustez, mas o mecanismo permanece inferencialmente aberto.</td>
<td style="text-align: left;">Municípios dominados por elites fundiárias investiram mais em escolarização; a evidência não aponta o mesmo para elites capitalistas <a href="https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/111334221/20361269-5540-47e3-9f31-7ad221c675c9/Andersson-and-Berger-2019-Elites-and-the-expansion-of-education-in-nineteenth-century-Sweden.pdf?AWSAccessKeyId=ASIA2F3EMEYER3ILXUM5&amp;Signature=%2BQyM5ZVjsqkRP6YaiTSXWJY%2FWh0%3D&amp;x-amz-security-token=IQoJb3JpZ2luX2VjEEkaCXVzLWVhc3QtMSJHMEUCIQDilUDbv5Nac7mpQ24RhmQIqFpSXgoxUJJffdJDvyz5SgIgPxdjXNJ8Rt12pQrlACBNX%2F8cwO7Xds%2BGs8AkiSlpttkq8wQIEhABGgw2OTk3NTMzMDk3MDUiDKX7%2FkIdw3gyV31aGSrQBKvuq34K5uKiQCM4vsRycTnjOWHQ5I5QOTU%2Ft8yo4Cu%2BVLu262oDasiZbiNRcgqzmXU7h2AXXw7FoSUcBbsXj4KpA%2Fb8VhSgn26uU6KIjjWX0H615VZ%2BW0FGlNLaAsZxTb0a8fVdfAlnR8arS%2F6isGHFxsb2q%2BhlS1VnARuGaNld%2Fu51zYhwu7D%2FQhXbK4Ztkmu7uHPC2UBkhy8C2HdQh%2F0coiP3OYBZJ4WwTIKSKSd9vD72z9q1EaFdNVOvtoRSAQ1h0LFjBfT77CgUUvuHX5xYsmW%2B3sf2MqlpGcCLoMYrg4kJwuEC5sSDTVtf15o3wVs5hxahfqXEwJeE02K%2BmUElNEPlnYfU7eCb7jQumgzPXWFhxBYxQxAm29cw%2BoInWqITzChGns%2FKIy51Owa8Ym9vzbD1vZwgIVUGaFOBjgqfHFMpg0yAuzz0xXQtrl9nft03F2oyvHalQoh53FtvLbGUgWTP%2BXfdl8HXm99IxkDBSZxspegbgXqX9xZvZv0Gtn5TO6q%2FwjaDtkpTjWuY4Ti9AhpV5%2BMmaUGDA6IXNW3AvW7p5z4%2Bzzh7pX7QGi5lZnTPND746I5ToxHWOAOY8BJNCeGx4lR8or%2BgFH1DqhUeK2PwJr3yvstYBd5UjSihKArClr0N0ucDcjx1NEjgtq0F55%2B%2BJpVqhJOm0XFFwMtwiVjt7stTcKhvsECgYruwtAS6H9%2F3BJSFhO8iBxD8GojQ0PfRJ3A1BgX4nOpkPXwaLfXRSo9IC9xpeJvg3dLCwArWC%2FXTUkxCVQgZL7vIjOcw3uiVzwY6mAGQ2828jdIDAl9zOWD4j1Eb%2BQvvfnh%2BcgkmxH%2BCHWFmh%2FKQ3bllUqJSltM%2BJj30%2Bkoy%2Fd0Gnp4tNrTtVONoxTomd0XoP%2BnzU%2Bd%2BBy1%2BJG0rbCMcga07B6MrVLq70iMkd3dAgpySwattPhMgt7ts5mbM%2BtWk6fJUnaeKbxXt%2BBNoboD1GrEzM2pLfHjhohQmGrnmCiv3dSdlgg%3D%3D&amp;Expires=1776646272">ppl-ai-file-upload.s3.amazonaws</a></td>
</tr>
<tr class="even">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">O estudo é quantitativo-histórico, com dados municipais inéditos para mais de 2.000 municípios rurais, medidas de gasto educacional e desigualdade de votos, regressões OLS, efeitos fixos e testes de robustez. A identificação é associacional, não experimental, e depende de controles observáveis e comparação entre municípios.</td>
<td style="text-align: left;">Construção de base inédita com finanças municipais e direitos de voto; OLS com controles, efeitos fixos de condado e distrito, testes alternativos de medida e análise de robustez</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">O DGP é relativamente claro: fenômenos de poder político e gasto público são observados por registros municipais de 1871–1874; esses registros são transformados em Gini e dummies de elite; a análise estima associações entre desigualdade política e gasto educacional. A unidade é a municipalidade rural, mas a desigualdade de voto é medida por voto-holders, não pela população inteira.</td>
<td style="text-align: left;">Fenômeno: poder político desigual e gasto escolar; observação: livros/relatórios municipais; coleta: BiSOS e outras fontes; operacionalização: Gini, elites &gt;10/25/50%; análise: regressões OLS; unidade: municípios rurais</td>
</tr>
<tr class="even">
<td style="text-align: left;">Achados e Contribuições</td>
<td style="text-align: left;">O principal achado é a relação positiva entre desigualdade de votos e gasto educacional, concentrada em localidades com elites fundiárias. A contribuição teórica é mostrar que elite capture não implica necessariamente subinvestimento em educação; metodologicamente, o artigo separa elite fundiária de elite capitalista e examina composição do gasto público.</td>
<td style="text-align: left;">Desigualdade de votos correlaciona-se com mais gasto escolar; elite fundiária, não capitalista, explica o padrão; o gasto aumenta em educação sem aumento equivalente do gasto total</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Análise Crítica dos Achados</td>
<td style="text-align: left;">O artigo responde bem à pergunta empírica, mas a inferência causal é limitada pela possibilidade de variáveis omitidas e seleção não observada; os autores reconhecem isso e usam Altonji et al.&nbsp;como diagnóstico, não como prova definitiva. Além disso, o mecanismo “patronagem social” é plausível, porém não identificado diretamente.</td>
<td style="text-align: left;">A resposta é forte em robustez, mais fraca em identificação causal estrita; a evidência aponta associação persistente, mas o mecanismo é interpretativo e o contexto sueco restringe generalização</td>
</tr>
<tr class="even">
<td style="text-align: left;">Limitações</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> potencial viés por fatores omitidos, sensibilidade à definição de gasto educacional, e dificuldade de identificar mecanismos com precisão.<br><br><strong>Não reconhecidas ou subestimadas:</strong> mensuração imperfeita do voto desigual em dados agrupados, possível endogeneidade das medidas de elite, e sub-representação de canais informais ou privados de investimento educacional.</td>
<td style="text-align: left;">Os autores admitem o risco de omitidas e testam alternativas de normalização; a mensuração de voto é agrupada e pode subestimar desigualdade; contribuições privadas ficam fora da medida principal</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Perspectiva Teórica</td>
<td style="text-align: left;">O texto combina economia política histórica, teoria das elites e literatura sobre capital humano e instituições. A ontologia implícita é relacional e institucionalista: elites reagem a incentivos sociais, políticos e distributivos, não apenas a retornos econômicos.</td>
<td style="text-align: left;">Diálogo com Lindert, Galor, Acemoglu e Robinson, Kaestle, Aghion et al.; a moldura é compatível com uma explicação institucional e política da escolarização</td>
</tr>
<tr class="even">
<td style="text-align: left;">Principais Referências</td>
<td style="text-align: left;">O diálogo central é com Lindert, Galor et al., Acemoglu e Robinson, Go e Lindert, Cvrcek e Zajicek, Shammas e Aghion et al.&nbsp;O balanço bibliográfico é bom, mas a literatura de história sueca e educação histórica ocupa papel mais interpretativo do que cumulativo no desenho de identificação.</td>
<td style="text-align: left;">Lindert; Galor, Moav e Vollrath; Acemoglu e Robinson; Go e Lindert; Cvrcek e Zajicek; Shammas; Aghion et al.; Sandberg; Boli; Nilsson e Pettersson</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Observações</td>
<td style="text-align: left;">O artigo é forte como caso histórico de política educacional sob franquia restrita e demonstra que elite fundiária pode financiar bens públicos em contextos específicos. Para um leitor interessado em inferência causal, o principal alerta é que a identificação é robusta, mas não definitiva, e o mecanismo permanece parcialmente conjectural.</td>
<td style="text-align: left;">O texto é útil para pesquisas sobre desigualdade política, provisão local de bens públicos e trajetórias de escolarização; sua validade externa depende de contextos em que elites fundiárias tenham incentivos sociais distintos dos capitalistas</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="introdução-pp.-14" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="introdução-pp.-14"><span class="header-section-number">4</span> Introdução (pp.&nbsp;1–4)</h2>
<section id="problema-e-debate-16" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="problema-e-debate-16"><span class="header-section-number">4.1</span> Problema e debate [§1–§6]</h3>
<p>O artigo abre situando um debate clássico sobre se elites políticas bloqueiam ou promovem a escolarização em massa. Os autores afirmam que a literatura associa a desigualdade econômica e política à obstrução da educação, mas também reconhece casos em que elites apoiaram a expansão escolar por razões de ordem social, identidade nacional, disciplina do trabalho ou patronagem local. A pergunta central emerge dessa tensão: afinal, elites são barreira ou motor da escolarização? <a href="https://ppl-ai-file-upload.s3.amazonaws.com/web/direct-files/attachments/111334221/20361269-5540-47e3-9f31-7ad221c675c9/Andersson-and-Berger-2019-Elites-and-the-expansion-of-education-in-nineteenth-century-Sweden.pdf?AWSAccessKeyId=ASIA2F3EMEYER3ILXUM5&amp;Signature=%2BQyM5ZVjsqkRP6YaiTSXWJY%2FWh0%3D&amp;x-amz-security-token=IQoJb3JpZ2luX2VjEEkaCXVzLWVhc3QtMSJHMEUCIQDilUDbv5Nac7mpQ24RhmQIqFpSXgoxUJJffdJDvyz5SgIgPxdjXNJ8Rt12pQrlACBNX%2F8cwO7Xds%2BGs8AkiSlpttkq8wQIEhABGgw2OTk3NTMzMDk3MDUiDKX7%2FkIdw3gyV31aGSrQBKvuq34K5uKiQCM4vsRycTnjOWHQ5I5QOTU%2Ft8yo4Cu%2BVLu262oDasiZbiNRcgqzmXU7h2AXXw7FoSUcBbsXj4KpA%2Fb8VhSgn26uU6KIjjWX0H615VZ%2BW0FGlNLaAsZxTb0a8fVdfAlnR8arS%2F6isGHFxsb2q%2BhlS1VnARuGaNld%2Fu51zYhwu7D%2FQhXbK4Ztkmu7uHPC2UBkhy8C2HdQh%2F0coiP3OYBZJ4WwTIKSKSd9vD72z9q1EaFdNVOvtoRSAQ1h0LFjBfT77CgUUvuHX5xYsmW%2B3sf2MqlpGcCLoMYrg4kJwuEC5sSDTVtf15o3wVs5hxahfqXEwJeE02K%2BmUElNEPlnYfU7eCb7jQumgzPXWFhxBYxQxAm29cw%2BoInWqITzChGns%2FKIy51Owa8Ym9vzbD1vZwgIVUGaFOBjgqfHFMpg0yAuzz0xXQtrl9nft03F2oyvHalQoh53FtvLbGUgWTP%2BXfdl8HXm99IxkDBSZxspegbgXqX9xZvZv0Gtn5TO6q%2FwjaDtkpTjWuY4Ti9AhpV5%2BMmaUGDA6IXNW3AvW7p5z4%2Bzzh7pX7QGi5lZnTPND746I5ToxHWOAOY8BJNCeGx4lR8or%2BgFH1DqhUeK2PwJr3yvstYBd5UjSihKArClr0N0ucDcjx1NEjgtq0F55%2B%2BJpVqhJOm0XFFwMtwiVjt7stTcKhvsECgYruwtAS6H9%2F3BJSFhO8iBxD8GojQ0PfRJ3A1BgX4nOpkPXwaLfXRSo9IC9xpeJvg3dLCwArWC%2FXTUkxCVQgZL7vIjOcw3uiVzwY6mAGQ2828jdIDAl9zOWD4j1Eb%2BQvvfnh%2BcgkmxH%2BCHWFmh%2FKQ3bllUqJSltM%2BJj30%2Bkoy%2Fd0Gnp4tNrTtVONoxTomd0XoP%2BnzU%2Bd%2BBy1%2BJG0rbCMcga07B6MrVLq70iMkd3dAgpySwattPhMgt7ts5mbM%2BtWk6fJUnaeKbxXt%2BBNoboD1GrEzM2pLfHjhohQmGrnmCiv3dSdlgg%3D%3D&amp;Expires=1776646272">ppl-ai-file-upload.s3.amazonaws</a></p>
<p>A contribuição do artigo é deslocar essa questão para a Suécia oitocentista e para o nível local de governo. Os autores sustentam que, como o financiamento escolar era local e o voto era altamente restrito e ponderado pela tributação, a distribuição do poder político em municipalidades rurais foi um determinante importante do investimento em <em>folkskola</em> . Isso é enquadrado como um caso relevante porque a Suécia combinava baixo desenvolvimento econômico com elevado capital humano, o que torna o puzzle empiricamente interessante .</p>
</section>
<section id="literatura-e-hipóteses-711" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="literatura-e-hipóteses-711"><span class="header-section-number">4.2</span> Literatura e hipóteses [§7–§11]</h3>
<p>Na revisão de literatura, os autores contrapõem duas hipóteses gerais. A primeira é a hipótese de obstrução: elites fundiárias, diante de baixos retornos privados da educação no campo, tenderiam a bloquear o gasto escolar para preservar controle social e reduzir a mobilidade do trabalho rural . A segunda é a hipótese de apoio seletivo: elites podem investir em educação quando percebem benefícios externos, ordem social, nação ou disciplina laboral .</p>
<p>Os autores também mostram que a literatura comparada não produz uma resposta unívoca. Eles citam estudos que apontam associação negativa entre desigualdade fundiária e escolarização, mas também trabalhos em que elites locais ou autocracias promoveram educação em contextos específicos . Isso permite que o artigo formule uma hipótese mais precisa: o comportamento das elites depende da composição social da elite e do contexto institucional, em vez de obedecer a uma regra geral de bloqueio .</p>
</section>
<section id="caso-sueco-1218" class="level3" data-number="4.3">
<h3 data-number="4.3" class="anchored" data-anchor-id="caso-sueco-1218"><span class="header-section-number">4.3</span> Caso sueco [§12–§18]</h3>
<p>A seção sobre a Suécia destaca três elementos institucionais decisivos. Primeiro, a Lei de 1842 exigiu ao menos uma escola por paróquia, mas sem obrigatoriedade de frequência e com pouco financiamento estatal inicial . Segundo, o sistema de voto local era altamente desigual: a votação era ponderada pela renda e pela terra, e um pequeno grupo podia concentrar a maior parte dos votos . Terceiro, a provisão escolar permaneceu sob autoridade local e eclesiástica, o que ligava diretamente gasto educacional e estrutura política local .</p>
<p>Os autores também descrevem a expansão material da escolarização entre 1847 e 1874. Houve aumento rápido no número de escolas e de docentes, e a matrícula aproximou-se da universalização na década de 1870, embora a escolarização efetiva ainda fosse curta e irregular . A prosa do artigo insiste que o crescimento do sistema não decorreu de plena democratização, o que reforça a relevância analítica do caso .</p>
</section>
<section id="estratégia-e-dados-1924" class="level3" data-number="4.4">
<h3 data-number="4.4" class="anchored" data-anchor-id="estratégia-e-dados-1924"><span class="header-section-number">4.4</span> Estratégia e dados [§19–§24]</h3>
<p>O artigo então passa da contextualização à estratégia empírica. Os autores constroem um novo banco de dados com mais de 2.000 municipalidades rurais, combinando finanças municipais, distribuição de votos e características locais como riqueza tributável, acessibilidade ferroviária, distância a cidades e composição ocupacional . A unidade de análise é a municipalidade rural, e o gasto educacional principal é medido por despesa em escola primária em 1874, normalizada por contribuinte para refletir esforço fiscal .</p>
<p>A distribuição do voto é resumida por coeficientes de Gini e por indicadores de elite fundiária e capitalista. Os autores reconhecem que a medida de Gini é imperfeita porque usa dados agrupados e subestima a desigualdade entre os votantes, razão pela qual também calculam um Gini ajustado que incorpora a fração da população sem voto . A amostra revela forte desigualdade política média e uma presença ampla de elites fundiárias, o que prepara o argumento principal do artigo .</p>
</section>
</section>
<section id="evidência-empírica-pp.-1323" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="evidência-empírica-pp.-1323"><span class="header-section-number">5</span> Evidência empírica (pp.&nbsp;13–23)</h2>
<section id="desigualdade-e-gasto-escolar-2529" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="desigualdade-e-gasto-escolar-2529"><span class="header-section-number">5.1</span> Desigualdade e gasto escolar [§25–§29]</h3>
<p>A primeira etapa da análise examina a associação entre desigualdade de votos e gasto educacional. O texto relata que a relação é positiva tanto em gráficos binned scatter quanto em regressões OLS com controles de riqueza, características municipais, direitos de voto e efeitos fixos de condado e distrito . Mesmo depois dos controles, a desigualdade de votos permanece associada a mais gasto em educação primária .</p>
<p>Os autores também testam desagregações da desigualdade. O resultado importante é que a associação positiva vem da desigualdade entre proprietários de terra, não da desigualdade entre detentores de renda; a desigualdade entre rendistas não apresenta associação significativa com gasto escolar . Esse achado é central porque desloca a interpretação do “efeito da desigualdade” genérica para uma composição específica de elite .</p>
</section>
<section id="elite-fundiária-e-capitalista-3034" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="elite-fundiária-e-capitalista-3034"><span class="header-section-number">5.2</span> Elite fundiária e capitalista [§30–§34]</h3>
<p>Na etapa seguinte, o artigo distingue elites fundiárias e capitalistas. A distribuição de gastos escolares é deslocada para cima em municípios dominados por elites, sobretudo fundiárias, e regressões mostram que a presença de elite fundiária está robustamente associada a maior gasto educacional, enquanto a presença de elite capitalista não apresenta efeito positivo consistente . Quando a elite fundiária é ainda mais concentrada — chegando a “ditadores locais” com mais de metade dos votos — o efeito estimado é maior .</p>
<p>Os autores interpretam isso como evidência de que a fundiária, e não a capitalista, impulsionou a escolarização taxada para as massas . Eles também observam que a ampliação do sufrágio local não parece explicar o aumento do gasto: a fração da população com voto aparece negativamente associada ao gasto escolar em várias especificações . O argumento implícito é que, na fase estudada, maior participação política não significou automaticamente maior investimento em educação .</p>
</section>
<section id="robustez-e-mecanismo-3540" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="robustez-e-mecanismo-3540"><span class="header-section-number">5.3</span> Robustez e mecanismo [§35–§40]</h3>
<p>Os autores enfrentam três preocupações principais. A primeira é viés por omissão; eles respondem com controles adicionais, efeitos fixos e um exercício do tipo Altonji et al., argumentando que fatores não observados teriam de ser muito fortes para anular o resultado . A segunda é sensibilidade à forma de medir gasto; os resultados permanecem semelhantes quando a despesa é normalizada por população, quando se excluem subsídios estatais, quando se separa gasto em prédios, salários e outros itens, e quando se retiram outliers . A terceira é que o efeito poderia refletir um compromisso geral com bens públicos; a resposta é que o padrão é específico da educação e se associa a uma reconfiguração da composição do gasto, não a um aumento generalizado do orçamento municipal .</p>
<p>A análise de bens públicos é importante porque restringe a interpretação do resultado. Os autores mostram que elites fundiárias não elevam o gasto total, mas aumentam a parcela destinada à educação e reduzem a destinada à assistência aos pobres . A hipótese de “falha de coordenação” recebe pouco apoio, porque o índice de concentração do gasto não se altera de modo relevante . Assim, a leitura preferida é redistributiva e política: elites fundiárias escolhem favorecer escola em detrimento de outras rubricas .</p>
</section>
<section id="interpretação-histórica-4145" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="interpretação-histórica-4145"><span class="header-section-number">5.4</span> Interpretação histórica [§41–§45]</h3>
<p>Na interpretação final, o texto combina três motivos para explicar o apoio de elites fundiárias à educação. Primeiro, a tradição de patronagem local e cuidado da comunidade; segundo, motivos de controle social diante da proletarização rural; terceiro, ideais de construção nacional e formação de cidadãos . Os autores são prudentes ao dizer que não identificam o mecanismo com precisão, apenas o tornam consistente com essa literatura histórica .</p>
<p>A conclusão também polemiza com duas visões correntes. Contra a historiografia sueca mais antiga, eles negam que a escolarização tenha sido sobretudo um processo liderado por camponeses ou apenas religioso . Contra a literatura internacional mais recente, eles rejeitam que industrialização e ascensão capitalista sejam a explicação principal . O argumento final é que elites fundiárias podem promover educação mesmo em sistemas politicamente restritivos, o que relativiza a ideia de que mais sufrágio seja sempre condição necessária para escolarização em massa .</p>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">6</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> Na Suécia rural do século XIX, elites fundiárias foram decisivas para ampliar o investimento em educação primária, enquanto elites capitalistas não exibiram o mesmo padrão.</p>
<p><strong>Natureza do argumento:</strong> Explicativo-histórico, com inferência causal principalmente associacional.</p>
<p><strong>O que o texto demonstra:</strong> Municípios com maior desigualdade de voto — especialmente onde elites fundiárias concentravam poder — gastaram mais em <em>folkskola</em>, e esse efeito permaneceu robusto a múltiplos controles, definições alternativas de gasto e testes de composição do orçamento.</p>
<p><strong>O que fica como hipótese ou agenda:</strong> O mecanismo preciso do apoio das elites fundiárias permanece inferido, não diretamente observado; a explicação mais plausível envolve patronagem local, controle social e projetos de ordem nacional.</p>
<p><strong>Contribuição para o debate:</strong> O artigo corrige a expectativa de que elite capture implica necessariamente menos educação, mostrando que a composição da elite e o contexto institucional podem inverter essa relação.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:http:|https:)\/\/drganghe\.github\.io\/custom");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="http://www.github.com/mancano-tales">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
<p>Build on <a href="https://github.com/drganghe/quarto-academic-website-template">Quart Academic Website Template</a> adapted by <a href="http://drganghe.github.io">Dr.&nbsp;Gang He</a></p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/drganghe/quarto-academic-website-template" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank">
<p><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></p>
</a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="../../posts.xml" target="_blank">
      <i class="bi bi-rss" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>