<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="description" content="Tales Mançano Academic Website">

<title>Fichamento: A política do atraso educacional: visões e conflitos sobre a instrução pública em São Paulo entre 1851 e 1892 – Tales Mançano</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ebcc418b19e6abcbe615d4e8be58f8e7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id="></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '', { 'anonymize_ip': true});
</script>


<!-- 

Load Academicons v1: https://jpswalsh.github.io/academicons/

-->

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">



<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">





<!---

The following code are needed to show dimension citation and altmetrics.

https://api.altmetric.com/embeds.html

https://badge.dimensions.ai/

--->



<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>



<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>



<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Fichamento: A política do atraso educacional: visões e conflitos sobre a instrução pública em São Paulo entre 1851 e 1892 – Tales Mançano">
<meta property="og:description" content="Colistete, Renato Perim (2014)">
<meta property="og:site_name" content="Tales Mançano">
<meta name="twitter:title" content="Fichamento: A política do atraso educacional: visões e conflitos sobre a instrução pública em São Paulo entre 1851 e 1892 – Tales Mançano">
<meta name="twitter:description" content="Colistete, Renato Perim (2014)">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Tales Mançano</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../posts.html">
 <span class="dropdown-text">Posts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../contact.html">
 <span class="dropdown-text">Contact</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-research" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Research</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-research">    
        <li>
    <a class="dropdown-item" href="../../publications.html">
 <span class="dropdown-text">List of Publications</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects.html">
 <span class="dropdown-text">Grants</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-outreach" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Outreach</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-outreach">    
        <li>
    <a class="dropdown-item" href="../../posts.html">
 <span class="dropdown-text">Presentations</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../files/2026-1-02-CV-Mancano-Tales.pdf"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/drganghe/quarto-academic-website-template" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../posts.xml" target="_blank"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Alternar modo de leitor">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link active" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  <li><a href="#introdução-pp.-13" id="toc-introdução-pp.-13" class="nav-link" data-scroll-target="#introdução-pp.-13"><span class="header-section-number">1</span> Introdução (pp.&nbsp;1–3)</a>
  <ul class="collapse">
  <li><a href="#o-problema-do-atraso-educacional-e-a-lacuna-historiográfica-14" id="toc-o-problema-do-atraso-educacional-e-a-lacuna-historiográfica-14" class="nav-link" data-scroll-target="#o-problema-do-atraso-educacional-e-a-lacuna-historiográfica-14"><span class="header-section-number">1.1</span> O problema do atraso educacional e a lacuna historiográfica [§1–§4]</a></li>
  </ul></li>
  <li><a href="#descentralização-e-o-surgimento-do-elemento-popular-pp.-35" id="toc-descentralização-e-o-surgimento-do-elemento-popular-pp.-35" class="nav-link" data-scroll-target="#descentralização-e-o-surgimento-do-elemento-popular-pp.-35"><span class="header-section-number">2</span> Descentralização e o Surgimento do “Elemento Popular” (pp.&nbsp;3–5)</a>
  <ul class="collapse">
  <li><a href="#a-lei-nº-9-de-1874-e-seus-limites-57" id="toc-a-lei-nº-9-de-1874-e-seus-limites-57" class="nav-link" data-scroll-target="#a-lei-nº-9-de-1874-e-seus-limites-57"><span class="header-section-number">2.1</span> A Lei nº 9 de 1874 e seus limites [§5–§7]</a></li>
  <li><a href="#o-projeto-de-reforma-de-rangel-pestana-1883-811" id="toc-o-projeto-de-reforma-de-rangel-pestana-1883-811" class="nav-link" data-scroll-target="#o-projeto-de-reforma-de-rangel-pestana-1883-811"><span class="header-section-number">2.2</span> O projeto de reforma de Rangel Pestana (1883) [§8–§11]</a></li>
  </ul></li>
  <li><a href="#a-reforma-frustrada-de-1885-pp.-57" id="toc-a-reforma-frustrada-de-1885-pp.-57" class="nav-link" data-scroll-target="#a-reforma-frustrada-de-1885-pp.-57"><span class="header-section-number">3</span> A Reforma Frustrada de 1885 (pp.&nbsp;5–7)</a>
  <ul class="collapse">
  <li><a href="#o-ato-de-2-de-maio-e-a-descentralização-participativa-1215" id="toc-o-ato-de-2-de-maio-e-a-descentralização-participativa-1215" class="nav-link" data-scroll-target="#o-ato-de-2-de-maio-e-a-descentralização-participativa-1215"><span class="header-section-number">3.1</span> O Ato de 2 de maio e a descentralização participativa [§12–§15]</a></li>
  </ul></li>
  <li><a href="#a-reação-conservadora-e-o-veto-de-1886-pp.-912" id="toc-a-reação-conservadora-e-o-veto-de-1886-pp.-912" class="nav-link" data-scroll-target="#a-reação-conservadora-e-o-veto-de-1886-pp.-912"><span class="header-section-number">4</span> A Reação Conservadora e o Veto de 1886 (pp.&nbsp;9–12)</a>
  <ul class="collapse">
  <li><a href="#bloqueio-conservador-ao-ato-de-2-de-maio-1618" id="toc-bloqueio-conservador-ao-ato-de-2-de-maio-1618" class="nav-link" data-scroll-target="#bloqueio-conservador-ao-ato-de-2-de-maio-1618"><span class="header-section-number">4.1</span> Bloqueio conservador ao Ato de 2 de maio [§16–§18]</a></li>
  <li><a href="#a-reforma-de-compromisso-de-1887-1921" id="toc-a-reforma-de-compromisso-de-1887-1921" class="nav-link" data-scroll-target="#a-reforma-de-compromisso-de-1887-1921"><span class="header-section-number">4.2</span> A reforma de compromisso de 1887 [§19–§21]</a></li>
  </ul></li>
  <li><a href="#consolidação-dos-conselhos-municipais-e-rent-seeking-pp.-1216" id="toc-consolidação-dos-conselhos-municipais-e-rent-seeking-pp.-1216" class="nav-link" data-scroll-target="#consolidação-dos-conselhos-municipais-e-rent-seeking-pp.-1216"><span class="header-section-number">5</span> Consolidação dos Conselhos Municipais e <em>Rent-Seeking</em> (pp.&nbsp;12–16)</a>
  <ul class="collapse">
  <li><a href="#rodrigues-alves-e-a-regulamentação-do-fundo-escolar-2225" id="toc-rodrigues-alves-e-a-regulamentação-do-fundo-escolar-2225" class="nav-link" data-scroll-target="#rodrigues-alves-e-a-regulamentação-do-fundo-escolar-2225"><span class="header-section-number">5.1</span> Rodrigues Alves e a regulamentação do fundo escolar [§22–§25]</a></li>
  </ul></li>
  <li><a href="#a-crise-de-18891892-república-municipalização-e-a-reforma-caetano-de-campos-pp.-1622" id="toc-a-crise-de-18891892-república-municipalização-e-a-reforma-caetano-de-campos-pp.-1622" class="nav-link" data-scroll-target="#a-crise-de-18891892-república-municipalização-e-a-reforma-caetano-de-campos-pp.-1622"><span class="header-section-number">6</span> A Crise de 1889–1892: República, Municipalização e a Reforma Caetano de Campos (pp.&nbsp;16–22)</a>
  <ul class="collapse">
  <li><a href="#proclamação-da-república-e-reconfiguração-do-conflito-2628" id="toc-proclamação-da-república-e-reconfiguração-do-conflito-2628" class="nav-link" data-scroll-target="#proclamação-da-república-e-reconfiguração-do-conflito-2628"><span class="header-section-number">6.1</span> Proclamação da República e reconfiguração do conflito [§26–§28]</a></li>
  <li><a href="#a-reforma-de-1892-e-a-reconfiguração-institucional-2931" id="toc-a-reforma-de-1892-e-a-reconfiguração-institucional-2931" class="nav-link" data-scroll-target="#a-reforma-de-1892-e-a-reconfiguração-institucional-2931"><span class="header-section-number">6.2</span> A Reforma de 1892 e a reconfiguração institucional [§29–§31]</a></li>
  </ul></li>
  <li><a href="#conclusões-pp.-22" id="toc-conclusões-pp.-22" class="nav-link" data-scroll-target="#conclusões-pp.-22"><span class="header-section-number">7</span> Conclusões (pp.&nbsp;22)</a>
  <ul class="collapse">
  <li><a href="#balanço-do-argumento-e-implicações-3234" id="toc-balanço-do-argumento-e-implicações-3234" class="nav-link" data-scroll-target="#balanço-do-argumento-e-implicações-3234"><span class="header-section-number">7.1</span> Balanço do argumento e implicações [§32–§34]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">8</span> Argumento Sintético</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: A política do atraso educacional: visões e conflitos sobre a instrução pública em São Paulo entre 1851 e 1892</h1>
<p class="subtitle lead">Colistete, Renato Perim (2014)</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Political Economy</div>
    <div class="quarto-category">Politics of Education</div>
    <div class="quarto-category">Development Economics</div>
    <div class="quarto-category">Brazil</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">20 de abril de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>

<style>
.lang-toggle {
  position: fixed;
  top: 70px;
  right: 20px;
  z-index: 1000;
}
.lang-btn {
  background: transparent;
  border: 1px solid #666;
  border-radius: 4px;
  padding: 5px 12px;
  margin: 0 2px;
  cursor: pointer;
  font-size: 14px;
  transition: all 0.3s;
}
.lang-btn:hover {
  background: #f0f0f0;
}
.lang-btn.active {
  background: #0366d6;
  color: white;
  border-color: #0366d6;
}
.lang-content[lang]:not([lang="en"]) { display: none; }
.lang-content[lang="en"] { display: block; }
</style>
<p>Colistete, R. P. (2014). <em>A política do atraso educacional: visões e conflitos sobre a instrução pública em São Paulo entre 1851 e 1892</em>. Versão de trabalho, janeiro de 2014. Departamento de Economia, FEA-USP.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Entrada BibTeX → Colistete2014
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="va">@unpublished</span>{<span class="ot">Colistete2014</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span> = {Colistete, Renato Perim},</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>  = {A pol{<span class="ch">\'</span>i}tica do atraso educacional: vis{<span class="ch">\~</span>o}es e conflitos sobre a instru{<span class="ch">\c</span>{c}}{<span class="ch">\~</span>a}o p{<span class="ch">\'</span>u}blica em S{<span class="ch">\~</span>a}o Paulo entre 1851 e 1892},</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>   = {2014},</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">note</span>   = {Vers{<span class="ch">\~</span>a}o de trabalho, janeiro de 2014. Departamento de Economia, FEA-USP. Apoio: IPEA/Programa C{<span class="ch">\'</span>a}tedras para o Desenvolvimento},</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
<p>Última atualização: 2026-04-20 Modelo: Perplexity — Claude Sonnet 4.6 Thinking Gerado em: 2026-04-20T07:27:00-03:00</p>
<hr>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v15.0</em>. A análise é adversarial sem ser destrutiva: identifica vulnerabilidades reais do argumento e reconhece contribuições genuínas com a mesma precisão. O raciocínio analítico subjacente a cada dimensão é registrado no campo <code>Raciocínio analítico</code> da tabela.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Instituição</strong></td>
<td style="text-align: left;">O autor assina com nome, departamento e e-mail institucionais no cabeçalho do próprio texto; não há nota biográfica adicional, mas a informação é explícita e suficiente para identificação.</td>
<td style="text-align: left;">Renato Perim Colistete — Departamento de Economia, FEA-USP (Faculdade de Economia, Administração e Contabilidade, Universidade de São Paulo). Nível de formação não explicitado no texto.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Questão de Pesquisa</strong></td>
<td style="text-align: left;">A pergunta aparece explicitamente na p.&nbsp;2 do artigo, formulada pelo próprio autor. Sua natureza é explicativa-causal: busca identificar o mecanismo responsável por um resultado (persistência do atraso educacional) que contrasta com uma condição favorável (crescimento econômico).</td>
<td style="text-align: left;">Por que o acesso à educação primária para a maioria das crianças em idade escolar continuou altamente restrito e desigual em São Paulo, mesmo diante do enorme crescimento econômico da segunda metade do século XIX e da implementação de políticas supostamente ilustradas pelos fundadores da República? (Pergunta formulada explicitamente pelo autor.) Natureza: <strong>explicativa</strong>.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Questões Secundárias</strong></td>
<td style="text-align: left;">Colistete articula duas subperguntas que estruturam a análise empírica e que são relacionadas como dimensões analíticas do mesmo problema de economia política: a origem dos recursos fiscais e o controle sobre eles. Ambas subordinam-se à pergunta central.</td>
<td style="text-align: left;">(1) De onde viriam os recursos adicionais necessários para a expansão em grande escala do ensino público elementar? (2) Quais esferas de governo e da sociedade deveriam ser responsáveis pela administração dos recursos e pela supervisão do sistema escolar? Ambas derivam diretamente da pergunta central e são tratadas como dimensões do mesmo problema de economia política do financiamento educacional.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Puzzle-Type</strong></td>
<td style="text-align: left;">O puzzle é genuíno: a literatura existente concentrava-se nas reformas republicanas pós-1889, deixando sem resposta por que o atraso persistiu mesmo após o crescimento econômico. O autor acrescenta o ângulo das disputas de economia política sobre o financiamento, que a historiografia havia negligenciado. O puzzle é generalizável a outros casos de subexpansão educacional em contextos de crescimento com desigualdade.</td>
<td style="text-align: left;"><strong>Puzzle explicativo</strong> combinado com <strong>mudança institucional frustrada</strong>: a existência de recursos econômicos (café) e de esforço legislativo repetido não produziu expansão educacional. O autor argumenta que a explicação reside em conflitos distributivos sobre financiamento e controle — aspecto negligenciado pela historiografia educacional brasileira. O puzzle tem boa generalização para a literatura de economia política do desenvolvimento educacional (Lindert, Sokoloff, Engerman).</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Conclusão / Argumento Central</strong></td>
<td style="text-align: left;">A tese é desenvolvida ao longo do artigo de forma indutiva, a partir dos conflitos legislativos, e sintetizada nas conclusões. O argumento é plausível e bem fundamentado nas fontes primárias, mas seu caráter causal permanece inferencial: o artigo demonstra que havia conflito político sobre financiamento e controle, mas não isola causalmente esse conflito como <em>o</em> determinante do atraso frente a outras hipóteses (oferta de trabalho infantil, baixa demanda, elites agrárias com baixo retorno à educação, etc.).</td>
<td style="text-align: left;">A persistência do atraso educacional em São Paulo no período imperial e no início da República não é explicável apenas pela falta de recursos ou pela inércia burocrática, mas principalmente pelos conflitos de economia política sobre o financiamento e o controle administrativo da instrução pública primária. Liberais-republicanos defendiam descentralização fiscal e participação popular nos conselhos municipais; conservadores resistiam, temendo perda de controle hierárquico e aumento de gastos. Esse impasse bloqueou reformas com potencial de expansão escolar. <em>Claim of discovery</em>: a dimensão político-fiscal do atraso educacional foi sistematicamente negligenciada pela historiografia, que focou nas reformas republicanas pós-1889.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Métodos</strong></td>
<td style="text-align: left;">O artigo é qualitativo e historiográfico, baseado em processo de rastreamento (<em>process tracing</em> implícito) dos debates legislativos e das decisões governamentais. O autor não declara explicitamente um design metodológico; a análise emerge da montagem cronológica dos eventos e documentos. A ausência de sistematização do DGP torna difícil avaliar o grau de seleção das evidências.</td>
<td style="text-align: left;">Estudo de caso histórico (São Paulo, 1851–1892). Fontes primárias: manuscritos legislativos do Arquivo da Assembleia Legislativa de SP, relatórios presidenciais provinciais, anais legislativos, imprensa periódica (<em>A Província de São Paulo</em>, <em>Correio Paulistano</em>, <em>A Constituinte</em>). Fontes secundárias: literatura especializada em história da educação brasileira, obras de Lindert, Sokoloff e Engerman. Técnica: análise narrativa/processual dos debates políticos e legislativos. <strong>Limitação de identificação</strong>: ausência de contrafactual explícito; seleção de eventos legislativos pode superrepresentar o conflito político-ideológico em detrimento de outros mecanismos.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Data Generation Process (DGP)</strong></td>
<td style="text-align: left;">O DGP é implícito e não declarado. O fenômeno observável (debates e votações legislativas) é um proxy razoável para o mecanismo de conflito político, mas não é o único canal possível. A unidade de análise (episódio legislativo/conflito político) é coerente com a pergunta, mas o autor não discute critérios de seleção dos episódios ou de saturação das evidências.</td>
<td style="text-align: left;"><strong>Fenômeno</strong>: conflitos político-institucionais sobre financiamento e controle da instrução pública. <strong>Observação</strong>: registros de debates parlamentares, relatórios presidenciais, editoriais de imprensa. <strong>Coleta</strong>: fontes primárias de arquivo (Assembleia Legislativa de SP) e impressas. <strong>Operacionalização</strong>: posições dos partidos (Liberal, Conservador, Republicano) nos debates como indicadores dos conflitos de interesse. <strong>Análise</strong>: narrativa cronológica e comparação de propostas legislativas sucessivas. <strong>Inferência</strong>: o padrão de bloqueio conservador e a alternância de avanços e recuos das reformas são lidos como evidência do mecanismo causal. <strong>Unidade de análise</strong>: episódios legislativos/administrativos. <strong>Nível de agregação</strong>: provincial (São Paulo).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Achados e Contribuições</strong></td>
<td style="text-align: left;">Os achados empíricos são bem documentados e a narrativa dos conflitos é convincente. A contribuição mais sólida é a identificação do impasse entre descentralização fiscal-participativa (liberais-republicanos) e centralização hierárquica (conservadores) como mecanismo de bloqueio institucional. A generalização comparativa (Lindert, Sokoloff-Engerman) é sugerida, mas não desenvolvida sistematicamente.</td>
<td style="text-align: left;"><strong>Empíricos</strong>: (1) O projeto de Rangel Pestana (1883) e o Ato de 2 de maio de 1885 foram as iniciativas mais radicais de descentralização fiscal e participativa; (2) A reação conservadora de 1885–1887 bloqueou a participação popular direta nos conselhos municipais, embora aprovasse o fundo escolar; (3) A Lei nº 81/1887 representou um recuo significativo em termos de eletividade, mas manteve a descentralização financeira; (4) Na República, o conflito sobre municipalização vs.&nbsp;estadualização do ensino reconfigurou o mesmo problema sob novos termos, culminando na Reforma Caetano de Campos (1892). <strong>Teórico-metodológicas</strong>: reposicionamento da política educacional brasileira dentro do arcabouço de economia política da educação (Lindert); identificação de conflito distributivo entre elites sobre controle burocrático-fiscal como variável explicativa negligenciada.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Análise Crítica dos Achados</strong></td>
<td style="text-align: left;">O artigo demonstra com riqueza empírica que houve conflito político sobre descentralização e financiamento. O passo inferencial mais fraco é tratar esse conflito como <em>causa suficiente</em> do atraso, sem controlar para outras hipóteses concorrentes (baixa demanda por educação, custos de oportunidade do trabalho infantil, estrutura fundiária, etc.). O design de caso único limita a generalização causal, embora o valor descritivo seja elevado.</td>
<td style="text-align: left;">O autor responde adequadamente à dimensão político-institucional da pergunta. <strong>Vulnerabilidades</strong>: (1) ausência de hipóteses alternativas explicitamente testadas ou descartadas (ex.: demanda familiar por educação, custo de oportunidade do trabalho infantil, restrições de oferta de professores); (2) o artigo centra-se na dimensão legislativa/de elite, com atenção limitada às condições de demanda por educação na população; (3) seleção do caso São Paulo pode não ser representativa de outras províncias; (4) as reformas republicanas de 1892 (Caetano de Campos) são tratadas muito brevemente, limitando a análise do período declarado no título (até 1892). <strong>Ameaças à identificação</strong>: endogeneidade entre conflito político e condições econômicas (o próprio crescimento cafeeiro estruturava os interesses dos grupos em disputa); possível viés de arquivo (sobrerrepresentação de liberais/republicanos na imprensa).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Limitações</strong></td>
<td style="text-align: left;">O autor reconhece limitações geográficas e de foco, mas não aborda explicitamente as limitações metodológicas do design de caso único nem as ameaças de seleção de evidências.</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> O artigo circunscreve explicitamente a análise à “dimensão mais visível das políticas para o ensino primário”, enfatizando como elas foram “pensadas, debatidas e implementadas” — ou seja, o autor declara que não está cobrindo todas as dimensões do problema educacional. A análise também é limitada ao caso de São Paulo, reconhecendo que o estado tinha características excepcionais (crescimento cafeeiro) que o tornam “ilustrativo”, mas não necessariamente representativo.<br><br><strong>Não reconhecidas ou subestimadas:</strong> (1) Ausência de discussão sobre a demanda por educação entre as famílias trabalhadoras (dimensão da procura escolar); (2) Nenhuma análise sistemática de dados quantitativos sobre matrículas, gastos ou número de escolas ao longo do período — o artigo é quase inteiramente narrativo, o que limita a verificação empírica das consequências das mudanças institucionais; (3) Design de caso único sem estratégia de comparação explícita com outras províncias ou países — a referência a EUA, Alemanha e Inglaterra é retórica (como faziam os atores históricos), não analítica; (4) A periodização do título (1851–1892) é enganosa: o artigo foca principalmente os anos 1880–1892, com menção episódica ao período 1851–1879.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Perspectiva Teórica</strong></td>
<td style="text-align: left;">A moldura de economia política é adequada à pergunta explicativa sobre bloqueio de reformas. A filiação a Lindert é explícita; Sokoloff e Engerman são mobilizados para o contexto latino-americano. A ontologia implícita é de ação racional estratégica dos grupos políticos em torno de interesses de classe/partido, o que é coerente com os dados apresentados, embora o autor não tematize essa escolha ontológica.</td>
<td style="text-align: left;"><strong>Tradição principal</strong>: economia política histórica da educação (Lindert 2004; Sokoloff &amp; Engerman 2000). <strong>Tradições secundárias</strong>: historiografia institucional brasileira (Leal, Tavares Bastos, Visconde do Uruguai como fontes primárias também mobilizadas teoricamente). A moldura é adequada ao tipo de pergunta (bloqueio de reforma por conflito distributivo). <strong>Coerência ontologia-método</strong>: o autor adota ontologia de atores racionais estratégicos (partidos como portadores de interesses), o que é coerente com a análise dos debates legislativos; no entanto, não há discussão sobre a formação das preferências dos atores — as posições conservadoras e liberais são tratadas como dadas, sem problematizar suas bases sociais ou econômicas de forma sistemática.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Principais Referências</strong></td>
<td style="text-align: left;">A base bibliográfica é sólida nas fontes primárias e adequada nas referências da historiografia educacional brasileira. O diálogo com a literatura internacional de economia política da educação poderia ser mais desenvolvido — Lindert é citado, mas a articulação analítica com seu argumento comparativo não é plenamente explorada.</td>
<td style="text-align: left;">Lindert, P. (2004). <em>Growing public</em>; Sokoloff, K. &amp; Engerman, S. (2000) (sobre desigualdade e educação na América Latina); historiografia educacional brasileira: Reis Filho (1995), Souza (1998), Hilsdorf (2011), Love (1982); fontes primárias legislativas e de imprensa do período. <strong>Diálogo potencialmente subdesenvolvido</strong>: literatura sobre rent-seeking e captura do Estado em contextos de descentralização fiscal; literatura comparada sobre municipalização do ensino na América Latina do século XIX.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Observações</strong></td>
<td style="text-align: left;">O artigo tem alto valor como contribuição historiográfica e como mapeamento de um mecanismo político negligenciado. Para pesquisas em política comparada e economia política da educação, é um ponto de partida útil, mas requer complementação com dados quantitativos e com análise de demanda.</td>
<td style="text-align: left;">(1) A narrativa do artigo é exemplarmente documentada em fontes primárias, conferindo alta credibilidade descritiva; (2) A principal lacuna teórica é a ausência de formalização do mecanismo causal — o argumento ficaria mais robusto com um modelo simples de negociação política ou de barganha distributiva; (3) A validade externa é limitada a contextos de descentralização fiscal com conflito de classes/partidos sobre controle educacional — outras províncias brasileiras com estrutura partidária diferente podem não replicar o padrão; (4) Para a pesquisa do leitor (políticas educacionais, desigualdade, mudança institucional): o artigo é útil como estudo de mecanismo de bloqueio institucional e como exemplo de <em>process tracing</em> histórico implícito; a discussão sobre imposto de capitação para educação é diretamente relevante para debates contemporâneos sobre vinculação constitucional de receitas à educação (FUNDEB).</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<hr>
</section>
<section id="introdução-pp.-13" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução-pp.-13"><span class="header-section-number">1</span> Introdução (pp.&nbsp;1–3)</h2>
<section id="o-problema-do-atraso-educacional-e-a-lacuna-historiográfica-14" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="o-problema-do-atraso-educacional-e-a-lacuna-historiográfica-14"><span class="header-section-number">1.1</span> O problema do atraso educacional e a lacuna historiográfica [§1–§4]</h3>
<p>§1 inicia o artigo situando o debate sobre o atraso educacional brasileiro desde o século XIX, quando intelectuais, jornalistas, políticos e membros do governo já se manifestavam sobre a precariedade do ensino primário na nação recém-constituída. Colistete aponta que, após o <strong>Ato Adicional de 1834</strong>, que atribuiu às províncias o papel central na organização do ensino primário, as assembleias legislativas e os governos provinciais tornaram-se os espaços privilegiados de diagnóstico e debate sobre a superação do atraso educacional. Em São Paulo, tornara-se recorrente nos relatórios provinciais a ênfase na discrepância entre o rápido desenvolvimento econômico — alimentado pelo crescimento excepcional das exportações de café — e o estado precário da instrução primária.</p>
<p>§2 introduz dados comparativos que ancoram empiricamente a escala do problema. Por volta de 1900, a taxa de matrícula nas escolas primárias do Brasil chegava a apenas 29 crianças por mil habitantes, enquanto os Estados Unidos atingiam 203, o Canadá 185 e a Alemanha 158 — índices de cinco a sete vezes maiores. Mesmo na América Latina, o Brasil situava-se entre os países com os menores índices, ficando muito atrás da Argentina (98), do Uruguai (78), do Peru (72) e do Chile (68). São Paulo não constituía exceção a esse quadro geral, embora viesse a ocupar posição de liderança nacional a partir da década de 1930.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Questão de pesquisa central (formulada explicitamente pelo autor, p.&nbsp;2):</strong> Por que o acesso à educação primária para a maioria das crianças em idade escolar continuou altamente restrito e desigual, mesmo com o enorme crescimento econômico de São Paulo desde a segunda metade do século XIX e a implementação de políticas supostamente ilustradas pelos fundadores da República no início do século XX?</p>
</div>
</div>
<p>§3 critica a historiografia existente. Uma extensa literatura dedicou-se a descrever os problemas e eventuais avanços das políticas educacionais no Brasil do século XIX e início do XX, mas boa parte dos estudos concentrou-se nas reformas republicanas pós-1889. No caso de São Paulo, as políticas dos republicanos — que promoveram mudanças substanciais e levaram à ampliação das matrículas — são geralmente vistas como parte de um projeto maior de transformação institucional que consolidou o poder de uma nova elite cafeeira durante a Primeira República. Colistete argumenta que essa ênfase “muitas vezes apologética” nas políticas republicanas deixa sem resposta a questão central sobre a persistência do acesso restrito e desigual à educação primária.</p>
<p>§4 anuncia o argumento do artigo: a resposta reside em um aspecto “geralmente negligenciado pela historiografia” — a forma com que grupos sociais e políticos buscaram resolver o problema crítico do <strong>financiamento</strong> e do <strong>controle</strong> dos recursos da instrução pública primária desde as primeiras décadas do Império. Colistete enquadra o problema como essencialmente de <strong>economia política</strong>: a democratização da instrução primária exigia enorme expansão de gastos públicos, e duas questões particulares polarizaram os debates — de onde viriam os recursos adicionais e quais esferas de governo e da sociedade controlariam esses recursos.</p>
<blockquote class="blockquote">
<p><strong>Puzzle central:</strong> Como explicar que décadas de debate político e de crescimento econômico extraordinário em São Paulo não produziram a expansão do ensino primário? O autor propõe que o bloqueio foi político — resultado de conflitos distributivos sobre financiamento e controle — e não simplesmente técnico ou de recursos.</p>
</blockquote>
<hr>
</section>
</section>
<section id="descentralização-e-o-surgimento-do-elemento-popular-pp.-35" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="descentralização-e-o-surgimento-do-elemento-popular-pp.-35"><span class="header-section-number">2</span> Descentralização e o Surgimento do “Elemento Popular” (pp.&nbsp;3–5)</h2>
<section id="a-lei-nº-9-de-1874-e-seus-limites-57" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="a-lei-nº-9-de-1874-e-seus-limites-57"><span class="header-section-number">2.1</span> A Lei nº 9 de 1874 e seus limites [§5–§7]</h3>
<p>§5 descreve o contexto legal vigente no início da década de 1880. A instrução pública em São Paulo era regulada pela <strong>Lei Provincial nº 9, de 22 de dezembro de 1874</strong>, que pela primeira vez estabeleceu a obrigatoriedade do ensino para crianças de 7 a 11 anos (meninas) ou até 14 anos (meninos) e a chamada <strong>liberdade de ensino</strong> — isto é, a organização do ensino particular sem regulamentos restritivos por parte do governo. Esses dois princípios — obrigatoriedade e liberdade — foram bandeiras convergentes de diferentes grupos políticos: conservadores, liberais e a dissidência que formaria o Partido Republicano no início dos anos 1870. A lei também estabelecia “conselhos de instrução” em cada município, compostos pelo inspetor de instrução pública de distrito, pelo presidente da câmara municipal e por um cidadão nomeado pelo presidente da província.</p>
<p>§6 registra a rápida erosão da crença nos princípios da Lei nº 9. Já em 1876, o jornal <em>A Província de São Paulo</em> — editado por Francisco Rangel Pestana e Américo de Campos, dois destacados liberais radicais convertidos ao republicanismo — constatava que o “sistema de ensino público é mal entre nós” e criticava a hesitação da Assembleia em propor mudanças, embora a única solução então defendida pelo periódico fosse uma fiscalização mais eficaz. A insatisfação ainda era limitada, centrada na execução, não na estrutura.</p>
</section>
<section id="o-projeto-de-reforma-de-rangel-pestana-1883-811" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="o-projeto-de-reforma-de-rangel-pestana-1883-811"><span class="header-section-number">2.2</span> O projeto de reforma de Rangel Pestana (1883) [§8–§11]</h3>
<p>§7 narra a mudança de posição dos republicanos no início dos anos 1880. Em setembro de 1880, o presidente provincial Laurindo Abelardo de Brito (Partido Liberal) nomeou uma comissão de especialistas para elaborar um plano de reforma. A comissão era composta por políticos e professores de diferentes partidos: Américo Brasiliense, Vicente Mamede de Freitas, Francisco Aurélio de Carvalho, Godofredo Furtado e Herculano Inglez de Souza. Com a saída deste último para a presidência de Sergipe, o governo indicou Francisco Rangel Pestana para substituí-lo. A proposta final — em grande parte elaborada por Rangel Pestana — foi aprovada pela comissão de constituição e justiça da Assembleia Legislativa somente em 1883, no governo liberal de Francisco Soares de Carvalho Brandão.</p>
<p>§8 descreve as inovações do projeto de 358 artigos. A primeira novidade era a criação de um <strong>conselho diretor</strong> de 25 membros para coordenar a instrução pública na província, cinco deles eleitos pelos próprios professores. A segunda inovação atingia a composição dos conselhos municipais: em vez de inspetores de distrito e presidentes de câmaras (como na Lei de 1874), os conselhos seriam formados por um vereador eleito anualmente pela câmara, um cidadão eleito pelos pais dos alunos e um comissário indicado pelo inspetor da instrução. Pela primeira vez uma proposição legislativa contemplava a participação de representantes não diretamente vinculados à presidência da província ou às câmaras municipais — os pais e responsáveis reunir-se-iam em assembleia anual para eleger seus representantes por voto majoritário.</p>
<p>§9 destaca a terceira inovação: as disposições provisórias do projeto previam a criação de um <strong>imposto específico</strong> para a construção e aquisição de mobília escolar, embora não ficasse claro se seria de esfera municipal ou provincial. Às câmaras municipais caberia a construção dos prédios e aquisição do mobiliário.</p>
<p>§10 registra a tramitação “tortuosa e protelada” do projeto. No início da legislatura de 1884, o deputado republicano Antônio Muniz de Souza propôs a entrada em pauta, mas Rodrigo Lobato Marcondes Machado (liberal de Taubaté) convenceu a maioria a reenviar o projeto à comissão de constituição e justiça, alegando que era “de muito valor teórico” mas de pouco sentido prático. Deputados conservadores, como Antônio da Silva Prado, chegaram a ironizar a proposta como “um verdadeiro monstro administrativo”. O projeto não voltou a ser discutido em 1884.</p>
<hr>
</section>
</section>
<section id="a-reforma-frustrada-de-1885-pp.-57" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="a-reforma-frustrada-de-1885-pp.-57"><span class="header-section-number">3</span> A Reforma Frustrada de 1885 (pp.&nbsp;5–7)</h2>
<section id="o-ato-de-2-de-maio-e-a-descentralização-participativa-1215" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="o-ato-de-2-de-maio-e-a-descentralização-participativa-1215"><span class="header-section-number">3.1</span> O Ato de 2 de maio e a descentralização participativa [§12–§15]</h3>
<p>§11 narra a reviravolta de 1885. Diante da indefinição da Assembleia Legislativa, o presidente provincial José Luiz de Almeida Couto (Partido Liberal) utilizou uma interpretação da Lei nº 130 de 1880 (que criara a Escola Normal) para decretar unilateralmente a reforma da instrução pública pelo <strong>Ato de 2 de maio de 1885</strong>. Conservadores contestaram a legitimidade da medida; republicanos, em minoria no legislativo, aliaram-se aos liberais e apoiaram a iniciativa. Rangel Pestana argumentou que a Assembleia “não era capaz de fazer a reforma” depois de quatro anos de tentativas infrutíferas, e que a reforma representava a transição de um sistema centralizador para um regime de liberdade com mais intervenção popular.</p>
<p>§12 detalha as inovações do Ato de 2 de maio em relação ao projeto de 1883. O Ato criou um <strong>conselho diretor</strong> de 17 membros, dos quais nove eleitos: cinco pelos conselhos municipais, dois pelos professores públicos e dois pelos diretores e professores de colégios particulares — dando representação direta aos conselhos municipais no conselho provincial, passo além do projeto de 1883. Os <strong>conselhos municipais</strong> foram reformulados de forma ainda mais radical: dois membros eleitos por pais, responsáveis, professores públicos e particulares das localidades; um terceiro representante eleito pela câmara municipal — todos com mandato de três anos. Eliminava-se, assim, a ingerência direta da presidência da província na composição dos conselhos locais.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Conceito-chave — Fundo Escolar:</strong> O Ato de 2 de maio criou em cada município um “fundo escolar” destinado à construção e equipamento das escolas, mantido por donativos, legados, multas e um <strong>imposto anual de 1 mil-réis</strong> sobre todos os indivíduos maiores de 21 anos que vivessem do trabalho ou de rendas — inclusive mulheres. Os conselhos municipais teriam autonomia na aplicação dos recursos, com aprovação prévia de delegados literários nomeados para distritos. Essa combinação de imposto específico com gestão local representava a fórmula mais descentralizadora já proposta para a instrução pública em São Paulo.</p>
</div>
</div>
<p>§13 contextualiza a experiência internacional como referência dos reformadores. A ideia de um imposto municipal específico para a instrução vinha sendo discutida há anos no Brasil. As principais referências citadas pelos reformadores eram os sistemas de ensino da Inglaterra, Alemanha e, especialmente, dos Estados Unidos, onde o ensino primário era descentralizado, com grande autonomia local tanto na arrecadação quanto na aplicação de recursos. Colistete identifica duas fontes intelectuais fundamentais para essa referência: o Visconde do Uruguai — que, apesar de ter sido um dos artífices da centralização política do período do “regresso” (1837), havia enfatizado a autonomia tributária local norte-americana como modelo — e, com posição mais radical, Aureliano <strong>Tavares Bastos</strong>, que em <em>A Província</em> (1870) propunha uma “dupla imposição” escolar, local e provincial.</p>
<p>§14 detalha a proposta de Tavares Bastos. Para ele, a instrução era o “interesse fundamental dos povos modernos” e, no caso brasileiro, rivalizada em importância apenas pela emancipação dos escravos. A proposta consistia em uma taxa escolar com duas camadas: uma “paga por cada habitante ou por cada família” no município, complementada por “uma porcentagem adicionada a qualquer dos impostos diretos” em nível provincial. A parcela provincial seria transitória, até que a população “abraçasse cordialmente o novo sistema”.</p>
<p>§15 registra a formalização em nível nacional. Somente no gabinete liberal do Visconde de Paranaguá (1882–1883) o Ministério do Império divulgou o <strong>Aviso Circular nº 5.781</strong>, recomendando a criação de um “fundo especial” com taxa escolar dividida em imposição local e provincial. Colistete observa que as semelhanças entre o Aviso Circular e a proposta de Tavares Bastos são evidentes, inclusive na redação do texto. Em São Paulo, a primeira proposta legislativa de um imposto específico para a instrução fora apresentada já em 1880, pelo deputado liberal e grande proprietário rural Nicolau de Souza Queiroz (projeto nº 96), mas não chegou a votar.</p>
<hr>
</section>
</section>
<section id="a-reação-conservadora-e-o-veto-de-1886-pp.-912" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="a-reação-conservadora-e-o-veto-de-1886-pp.-912"><span class="header-section-number">4</span> A Reação Conservadora e o Veto de 1886 (pp.&nbsp;9–12)</h2>
<section id="bloqueio-conservador-ao-ato-de-2-de-maio-1618" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="bloqueio-conservador-ao-ato-de-2-de-maio-1618"><span class="header-section-number">4.1</span> Bloqueio conservador ao Ato de 2 de maio [§16–§18]</h3>
<p>§16 descreve a virada política que reverteu a reforma de 1885. A queda do gabinete liberal de Saraiva (maio–agosto de 1885), premida pela disputa parlamentar sobre o fim da escravidão, levou os conservadores de volta ao poder. Em São Paulo, o vice-presidente Elias Antônio Pacheco e Chaves assumiu em setembro de 1885 e mandou <strong>suspender a execução do Ato de 2 de maio</strong> três dias após a posse, justificando que a reforma era “profunda e radical” e acarretava “pesadíssimo sacrifício dos cofres provinciais”. O presidente definitivo, João Alfredo Corrêa de Oliveira (Conservador), manteve a suspensão.</p>
<p>§17 descreve a tramitação do novo projeto em 1886. Com a retomada dos trabalhos da Assembleia em 1886, formou-se comissão especial com representantes dos três partidos, sendo novamente designado relator Rangel Pestana. O projeto seguiu os princípios do Ato de 2 de maio na obrigatoriedade, eletividade e transferência de poderes aos municípios, com algumas medidas ainda mais descentralizadoras: um conselho superior de 12 membros, dos quais sete eletivos; os conselhos municipais, por sua vez, seriam compostos inteiramente por pais, responsáveis e professores, excluindo-se os representantes das câmaras municipais. O fundo escolar e o imposto de capitação de 1 mil-réis foram mantidos.</p>
<p>§18 registra o veto do Barão do Parnaíba ao projeto aprovado em abril de 1886. Em 9 de junho de 1886, o presidente da província apresentou três argumentos: (1) a retirada do presidente da província da direção do ensino em favor de um conselho superior eletivo subvertia a hierarquia estabelecida pelo Ato Adicional de 1834 e pela Lei de Interpretação de 1840; (2) a imposição de multas para fazer cumprir a obrigatoriedade e o aumento de despesas eram injustificados; (3) a eletividade dos conselhos afrouxaria os “laços de subordinação” e quebraria a “unidade sistemática de serviço”.</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Importante
</div>
</div>
<div class="callout-body-container callout-body">
<p>O veto de 1886 constitui o ponto central do argumento de Colistete: ele revela que a resistência conservadora não era apenas fiscal (custo do imposto), mas fundamentalmente política — a defesa de uma cadeia hierárquica de controle do Estado sobre a instrução pública, incompatível com a autonomia eletiva dos conselhos municipais.</p>
</div>
</div>
</section>
<section id="a-reforma-de-compromisso-de-1887-1921" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="a-reforma-de-compromisso-de-1887-1921"><span class="header-section-number">4.2</span> A reforma de compromisso de 1887 [§19–§21]</h3>
<p>§19 descreve a negociação que resultou na <strong>Lei nº 81, de 6 de abril de 1887</strong>. Em março de 1887, um acordo entre os partidos levou à reformulação do projeto. O principal recuo foi na participação direta da população: no conselho superior, os representantes dos conselhos municipais foram substituídos por representantes eleitos pelas câmaras municipais (quatro de nove membros); nos conselhos municipais, os representantes eleitos por pais, responsáveis e professores foram substituídos por dois membros das câmaras municipais e um nomeado pelo presidente da província. Restaurava-se assim o controle hierárquico da presidência.</p>
<p>§20 observa que, apesar do recuo na dimensão participativa, o projeto reformulado manteve a criação do fundo escolar e do imposto de capitação. Colistete interpreta isso como sinal de que a descentralização financeira — sugerida desde o projeto de 1883 e formalizada no Ato de 2 de maio — havia obtido apoio de todos os três grupos políticos, mesmo que a descentralização administrativa e participativa continuasse sendo objeto de disputa. A Lei nº 81/1887 foi sancionada pelo Barão do Parnaíba.</p>
<p>§21 registra o diagnóstico contemporâneo da contradição: um editorial de <em>A Província de São Paulo</em> (provavelmente de Rangel Pestana) afirmou que os conselhos municipais não funcionavam porque haviam sido constituídos “pela indicação das câmaras e nomeação do presidente da província”, em vez de eleição direta por pais e professores. O “espírito tacanho da centralização”, segundo o editorial, havia produzido uma lei fundada na “desconfiança na capacidade popular” — criando conselhos sem legitimidade e sem recursos.</p>
<hr>
</section>
</section>
<section id="consolidação-dos-conselhos-municipais-e-rent-seeking-pp.-1216" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="consolidação-dos-conselhos-municipais-e-rent-seeking-pp.-1216"><span class="header-section-number">5</span> Consolidação dos Conselhos Municipais e <em>Rent-Seeking</em> (pp.&nbsp;12–16)</h2>
<section id="rodrigues-alves-e-a-regulamentação-do-fundo-escolar-2225" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="rodrigues-alves-e-a-regulamentação-do-fundo-escolar-2225"><span class="header-section-number">5.1</span> Rodrigues Alves e a regulamentação do fundo escolar [§22–§25]</h3>
<p>§22 descreve a administração conservadora de Francisco de Paula <strong>Rodrigues Alves</strong>, que assumiu a presidência da província em novembro de 1887. Confrontado com os problemas de funcionamento dos conselhos municipais — que “ou não se constituem, ou, constituídos, não se instalam” —, Rodrigues Alves publicou em fevereiro de 1888 norma configurando como renúncia o não comparecimento de membros eleitos das câmaras, abrindo espaço para nova eleição imediata. Passados oito meses, relatava que os conselhos estavam finalmente sendo instalados e exercendo suas funções.</p>
<p>§23 detalha a regulamentação do fundo escolar em 28 de março de 1888. O regulamento fixou as condições para o arrolamento de contribuintes, a arrecadação do imposto de capitação de 1 mil-réis e a utilização dos recursos pelos conselhos municipais. Para identificar os contribuintes, os exatores deveriam recorrer às listas nominais de eleitores de cada paróquia, aos contribuintes do imposto predial e do imposto de indústria e profissões, além das “relações de moradores de cada quarteirão” obtidas por delegados e subdelegados. Colistete observa que, ao final de sua administração, o conservador Rodrigues Alves deixou estruturadas as normas básicas para o funcionamento dos conselhos e da descentralização financeira.</p>
<p>§24 registra que a cobrança efetiva do imposto escolar foi iniciada nos meses seguintes. Em novembro de 1888, a recebedoria da província publicava anúncios notificando os contribuintes. No entanto, logo surgiram problemas: membros dos conselhos municipais passaram a utilizar os recursos do fundo escolar para finalidades distintas das previstas em lei — contratando professores em vez de construir e equipar escolas —, caracterizando o que Colistete denomina de comportamento de <strong><em>rent-seeking</em></strong> por parte dos conselhos locais.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Conceito-chave — <em>Rent-seeking</em>:</strong> Colistete emprega o termo para descrever o comportamento dos conselhos municipais que desviavam os recursos do fundo escolar para contratação de pessoal (professores), em vez de aplicá-los na construção e equipamento das escolas, como determinava a lei. Isso revela que a autonomia local, ainda que politicamente restrita pela reforma de 1887, foi suficiente para gerar pressões por redistribuição de recursos dentro dos municípios, independentemente das prioridades estabelecidas centralmente.</p>
</div>
</div>
<p>§25 narra a reação do governo provincial. O inspetor-geral da instrução pública emitiu circular proibindo os conselhos de contratar professores com recursos do fundo escolar. A disputa sobre o uso dos recursos evidenciava uma tensão estrutural: a descentralização financeira havia criado incentivos para que os conselhos locais buscassem expandir suas atribuições além das funções de construção e equipamento escolar, gerando conflito com as autoridades provinciais sobre os limites da autonomia municipal.</p>
<hr>
</section>
</section>
<section id="a-crise-de-18891892-república-municipalização-e-a-reforma-caetano-de-campos-pp.-1622" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="a-crise-de-18891892-república-municipalização-e-a-reforma-caetano-de-campos-pp.-1622"><span class="header-section-number">6</span> A Crise de 1889–1892: República, Municipalização e a Reforma Caetano de Campos (pp.&nbsp;16–22)</h2>
<section id="proclamação-da-república-e-reconfiguração-do-conflito-2628" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="proclamação-da-república-e-reconfiguração-do-conflito-2628"><span class="header-section-number">6.1</span> Proclamação da República e reconfiguração do conflito [§26–§28]</h3>
<p>§26 descreve como a Proclamação da República em novembro de 1889 reconfigurou, mas não eliminou, o conflito sobre descentralização e controle da instrução pública. O novo regime extinguiu os partidos do Império, mas os debates sobre municipalização versus estadualização do ensino continuaram, agora sob novas alianças. Os republicanos históricos de São Paulo dividiram-se: um grupo defendia a municipalização radical do ensino, com autonomia local ampla; outro, liderado por figuras como Rangel Pestana, passou a defender maior controle estadual como condição para a efetividade das reformas, dado o fracasso parcial da descentralização sob a Lei nº 81/1887.</p>
<p>§27 descreve os conflitos nos primeiros anos republicanos. As disputas entre defensores da municipalização e da centralização estadual tornaram-se mais intensas no contexto da elaboração da Constituição Estadual (1891) e das novas legislações educacionais. Colistete identifica que a linha divisória não coincidia mais com a clivagem partidária do Império — conservadores x liberais-republicanos —, mas agora cruzava o próprio campo republicano, opondo defensores de diferentes modelos de gestão do ensino público.</p>
<p>§28 examina o papel do inspetor-geral <strong>Antônio Caetano de Campos</strong> no debate sobre a reforma educacional do início da República. Caetano de Campos, defensor do modelo das <em>common schools</em> norte-americanas com base no método intuitivo e na formação pedagógica de professores, tornou-se o principal articulador da <strong>Reforma de 1892</strong> (Reforma Caetano de Campos). Sua proposta enfatizava a centralização estadual da instrução — contra a municipalização — como condição para a melhoria qualitativa do ensino, rompendo com a tradição descentralizadora dos liberais-republicanos do Império.</p>
</section>
<section id="a-reforma-de-1892-e-a-reconfiguração-institucional-2931" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="a-reforma-de-1892-e-a-reconfiguração-institucional-2931"><span class="header-section-number">6.2</span> A Reforma de 1892 e a reconfiguração institucional [§29–§31]</h3>
<p>§29 descreve o conteúdo da Reforma de 1892. A reforma criou as <strong>Escolas-Modelo</strong> — escolas primárias modelares anexas à Escola Normal, destinadas à formação prática de professores — e reorganizou o sistema escolar em grupos escolares graduados, com divisão de alunos por séries e professores especializados por disciplina. A reforma privilegiava a qualidade e a modernização pedagógica, concentrando recursos nas escolas urbanas de maior visibilidade política.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Dica
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Implicação interpretativa:</strong> A Reforma de 1892 representou uma mudança no eixo do conflito: da disputa sobre <em>quem controla e como financia</em> (o tema dominante de 1883 a 1887) para a disputa sobre <em>qual modelo pedagógico e qual estrutura organizacional</em> deve prevalecer. Colistete argumenta que essa mudança de agenda não resolveu o problema fundamental do acesso restrito — ao contrário, ao concentrar recursos nas Escolas-Modelo urbanas, a reforma aprofundou a desigualdade territorial do sistema escolar.</p>
</div>
</div>
<p>§30 examina o debate sobre o financiamento na nova república. O imposto escolar e o fundo municipal criados pela Lei nº 81/1887 foram progressivamente esvaziados ou extintos no contexto da reorganização republicana, sem que um mecanismo alternativo de financiamento de base ampla fosse criado. A receita fiscal do novo estado de São Paulo era concentrada no imposto de exportação do café, mas a alocação de recursos para a educação primária continuou sujeita às disputas orçamentárias anuais, sem vinculação específica.</p>
<p>§31 sintetiza a análise do período 1889–1892. Colistete argumenta que a passagem do Império para a República não representou uma ruptura no problema fundamental da instrução pública em São Paulo, mas uma reconfiguração do mesmo conflito de economia política. A descentralização fiscal e participativa defendida pelos liberais-republicanos nas décadas de 1880 foi abandonada em favor de uma centralização estadual que priorizava a modernização qualitativa sobre a expansão quantitativa do acesso. O resultado, segundo o autor, foi que o novo regime republicano reproduziu, sob formas diferentes, o mesmo padrão de acesso restrito à educação primária que caracterizara o período imperial.</p>
<hr>
</section>
</section>
<section id="conclusões-pp.-22" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="conclusões-pp.-22"><span class="header-section-number">7</span> Conclusões (pp.&nbsp;22)</h2>
<section id="balanço-do-argumento-e-implicações-3234" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="balanço-do-argumento-e-implicações-3234"><span class="header-section-number">7.1</span> Balanço do argumento e implicações [§32–§34]</h3>
<p>§32 sintetiza o argumento do artigo. Colistete conclui que a persistência do atraso educacional em São Paulo entre 1851 e 1892 não pode ser explicada apenas pela escassez de recursos ou pela ausência de vontade política reformadora, pois houve tanto crescimento econômico quanto esforço legislativo. A explicação reside nos conflitos de <strong>economia política</strong> sobre o financiamento e o controle da instrução pública: liberais e republicanos defendiam descentralização fiscal e participação popular direta nos conselhos municipais, enquanto conservadores resistiam por razões tanto fiscais (custo do imposto) quanto políticas (defesa da hierarquia estatal). Esse impasse bloqueou as reformas mais abrangentes.</p>
<p>§33 retoma a comparação internacional. Colistete aponta que a experiência de São Paulo contrasta com a de países que conseguiram expandir massivamente o ensino primário no mesmo período — notadamente os Estados Unidos e os países do norte da Europa —, onde a descentralização fiscal com autonomia local efetiva foi acompanhada de mecanismos de financiamento estável e de demanda popular por educação. No caso paulista, a descentralização financeira foi aprovada mas esvaziada na prática; a descentralização participativa foi bloqueada pelos conservadores; e a demanda popular permaneceu latente, sem mecanismos institucionais para se expressar politicamente.</p>
<p>§34 aponta a implicação mais geral do argumento. O artigo sugere que a chave para entender o atraso educacional brasileiro não está no período republicano — que a historiografia tende a privilegiar —, mas nas décadas anteriores, quando se definiram os padrões institucionais de financiamento e controle que o novo regime herdou e, em muitos aspectos, reproduziu. Essa perspectiva reposiciona a história educacional brasileira dentro de um quadro mais amplo de economia política do desenvolvimento, articulando-a com a literatura internacional sobre desigualdade, instituições e expansão educacional.</p>
<hr>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">8</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> A persistência do atraso educacional em São Paulo entre 1851 e 1892 foi produto de um bloqueio político-institucional estruturado pelo conflito entre dois modelos de economia política da instrução pública: o modelo liberal-republicano de descentralização fiscal e participativa (com imposto local e conselhos eletivos) e o modelo conservador de centralização hierárquica, que resistia tanto ao custo fiscal quanto à perda de controle sobre o sistema escolar.</p>
<p><strong>Natureza do argumento:</strong> Causal-histórico com base em <em>process tracing</em> implícito; argumento explanatório por mecanismo, não por correlação estatística.</p>
<p><strong>O que o texto demonstra:</strong> Que as sucessivas tentativas de reforma (1883, 1885, 1886, 1887, 1892) foram sistematicamente esvaziadas nos seus elementos mais inovadores — a participação popular direta nos conselhos municipais e a autonomia local sobre os recursos do fundo escolar — por resistência conservadora e, depois, pela própria inflexão centralizadora dos republicanos históricos. A narrativa empírica, baseada em extensas fontes primárias, é convincente e densa.</p>
<p><strong>O que fica como hipótese ou agenda:</strong> (1) Se o mecanismo de bloqueio identificado é suficiente para explicar o atraso, ou se fatores de demanda (baixo incentivo familiar para escolarização, custo de oportunidade do trabalho infantil) têm peso explicativo independente; (2) Se o padrão paulista é generalizável a outras províncias/estados com estruturas partidárias e econômicas distintas; (3) Quais as consequências quantificáveis do bloqueio — ou seja, quanto maior teria sido a expansão escolar se as reformas de 1883 ou 1885 tivessem sido plenamente implementadas.</p>
<p><strong>Contribuição para o debate:</strong> O artigo reposiciona a história educacional brasileira dentro da literatura de economia política do desenvolvimento (Lindert, Sokoloff-Engerman), identificando o conflito distributivo sobre financiamento e controle — e não apenas a escassez de recursos ou o voluntarismo reformador — como o mecanismo central do atraso educacional no Brasil do século XIX. É uma contribuição sólida à historiografia, com alto valor descritivo e um argumento mecanístico plausível, mas que requereria formalização teórica e complementação quantitativa para consolidar suas pretensões causais.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:http:|https:)\/\/drganghe\.github\.io\/custom");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="http://www.github.com/mancano-tales">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
<p>Build on <a href="https://github.com/drganghe/quarto-academic-website-template">Quart Academic Website Template</a> adapted by <a href="http://drganghe.github.io">Dr.&nbsp;Gang He</a></p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/drganghe/quarto-academic-website-template" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank">
<p><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></p>
</a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="../../posts.xml" target="_blank">
      <i class="bi bi-rss" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>