<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="description" content="Tales Mançano Academic Website">

<title>Fichamento: Land Inequality in a Coffee Economy: São Paulo During the Early Twentieth Century – Tales Mançano</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-ebcc418b19e6abcbe615d4e8be58f8e7.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "Nenhum resultado",
    "search-matching-documents-text": "documentos correspondentes",
    "search-copy-link-title": "Copiar link para a busca",
    "search-hide-matches-text": "Esconder correspondências adicionais",
    "search-more-match-text": "mais correspondência neste documento",
    "search-more-matches-text": "mais correspondências neste documento",
    "search-clear-button-title": "Limpar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Procurar"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id="></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '', { 'anonymize_ip': true});
</script>


<!-- 

Load Academicons v1: https://jpswalsh.github.io/academicons/

-->

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">



<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">





<!---

The following code are needed to show dimension citation and altmetrics.

https://api.altmetric.com/embeds.html

https://badge.dimensions.ai/

--->



<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>



<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>



<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Fichamento: Land Inequality in a Coffee Economy: São Paulo During the Early Twentieth Century – Tales Mançano">
<meta property="og:description" content="Colistete e Lamounier (2014)">
<meta property="og:site_name" content="Tales Mançano">
<meta name="twitter:title" content="Fichamento: Land Inequality in a Coffee Economy: São Paulo During the Early Twentieth Century – Tales Mançano">
<meta name="twitter:description" content="Colistete e Lamounier (2014)">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Tales Mançano</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Procurar"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Alternar de navegação" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../posts.html">
 <span class="dropdown-text">Posts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../contact.html">
 <span class="dropdown-text">Contact</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-research" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Research</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-research">    
        <li>
    <a class="dropdown-item" href="../../publications.html">
 <span class="dropdown-text">List of Publications</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects.html">
 <span class="dropdown-text">Grants</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-outreach" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Outreach</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-outreach">    
        <li>
    <a class="dropdown-item" href="../../posts.html">
 <span class="dropdown-text">Presentations</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../files/2026-1-02-CV-Mancano-Tales.pdf"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/drganghe/quarto-academic-website-template" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../posts.xml" target="_blank"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Alternar modo de leitor">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Nesta página</h2>
   
  <ul>
  <li><a href="#referência-apa-7" id="toc-referência-apa-7" class="nav-link active" data-scroll-target="#referência-apa-7"><span class="header-section-number">1</span> Referência APA 7</a></li>
  <li><a href="#entrada-bibtex" id="toc-entrada-bibtex" class="nav-link" data-scroll-target="#entrada-bibtex"><span class="header-section-number">2</span> Entrada BibTeX</a></li>
  <li><a href="#timestamp" id="toc-timestamp" class="nav-link" data-scroll-target="#timestamp"><span class="header-section-number">3</span> Timestamp</a></li>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  <li><a href="#introdução-e-contexto-teórico-pp.-15" id="toc-introdução-e-contexto-teórico-pp.-15" class="nav-link" data-scroll-target="#introdução-e-contexto-teórico-pp.-15"><span class="header-section-number">4</span> Introdução e Contexto Teórico (pp.&nbsp;1–5)</a>
  <ul class="collapse">
  <li><a href="#apresentação-do-problema-e-lacuna-na-literatura-14" id="toc-apresentação-do-problema-e-lacuna-na-literatura-14" class="nav-link" data-scroll-target="#apresentação-do-problema-e-lacuna-na-literatura-14"><span class="header-section-number">4.1</span> Apresentação do problema e lacuna na literatura [§1–§4]</a></li>
  <li><a href="#objetivos-método-e-achados-preliminares-58" id="toc-objetivos-método-e-achados-preliminares-58" class="nav-link" data-scroll-target="#objetivos-método-e-achados-preliminares-58"><span class="header-section-number">4.2</span> Objetivos, método e achados preliminares [§5–§8]</a></li>
  </ul></li>
  <li><a href="#grandes-e-pequenas-fazendas-na-agricultura-paulista-pp.-57" id="toc-grandes-e-pequenas-fazendas-na-agricultura-paulista-pp.-57" class="nav-link" data-scroll-target="#grandes-e-pequenas-fazendas-na-agricultura-paulista-pp.-57"><span class="header-section-number">5</span> Grandes e Pequenas Fazendas na Agricultura Paulista (pp.&nbsp;5–7)</a>
  <ul class="collapse">
  <li><a href="#política-fundiária-e-obstáculos-à-pequena-propriedade-912" id="toc-política-fundiária-e-obstáculos-à-pequena-propriedade-912" class="nav-link" data-scroll-target="#política-fundiária-e-obstáculos-à-pequena-propriedade-912"><span class="header-section-number">5.1</span> Política fundiária e obstáculos à pequena propriedade [§9–§12]</a></li>
  <li><a href="#ocupação-de-terras-e-flexibilidade-do-café-1315" id="toc-ocupação-de-terras-e-flexibilidade-do-café-1315" class="nav-link" data-scroll-target="#ocupação-de-terras-e-flexibilidade-do-café-1315"><span class="header-section-number">5.2</span> Ocupação de terras e flexibilidade do café [§13–§15]</a></li>
  </ul></li>
  <li><a href="#a-economia-cafeeira-no-nordeste-de-são-paulo-pp.-810" id="toc-a-economia-cafeeira-no-nordeste-de-são-paulo-pp.-810" class="nav-link" data-scroll-target="#a-economia-cafeeira-no-nordeste-de-são-paulo-pp.-810"><span class="header-section-number">6</span> A Economia Cafeeira no Nordeste de São Paulo (pp.&nbsp;8–10)</a>
  <ul class="collapse">
  <li><a href="#caracterização-da-região-e-expansão-do-café-1619" id="toc-caracterização-da-região-e-expansão-do-café-1619" class="nav-link" data-scroll-target="#caracterização-da-região-e-expansão-do-café-1619"><span class="header-section-number">6.1</span> Caracterização da região e expansão do café [§16–§19]</a></li>
  <li><a href="#variação-regional-na-estrutura-fundiária-2021" id="toc-variação-regional-na-estrutura-fundiária-2021" class="nav-link" data-scroll-target="#variação-regional-na-estrutura-fundiária-2021"><span class="header-section-number">6.2</span> Variação regional na estrutura fundiária [§20–§21]</a></li>
  </ul></li>
  <li><a href="#estrutura-fundiária-e-distribuição-de-tamanho-pp.-1016" id="toc-estrutura-fundiária-e-distribuição-de-tamanho-pp.-1016" class="nav-link" data-scroll-target="#estrutura-fundiária-e-distribuição-de-tamanho-pp.-1016"><span class="header-section-number">7</span> Estrutura Fundiária e Distribuição de Tamanho (pp.&nbsp;10–16)</a>
  <ul class="collapse">
  <li><a href="#fonte-de-dados-e-estatísticas-descritivas-2224" id="toc-fonte-de-dados-e-estatísticas-descritivas-2224" class="nav-link" data-scroll-target="#fonte-de-dados-e-estatísticas-descritivas-2224"><span class="header-section-number">7.1</span> Fonte de dados e estatísticas descritivas [§22–§24]</a></li>
  <li><a href="#classificação-prado-jr-milliet-e-distribuição-numérica-2528" id="toc-classificação-prado-jr-milliet-e-distribuição-numérica-2528" class="nav-link" data-scroll-target="#classificação-prado-jr-milliet-e-distribuição-numérica-2528"><span class="header-section-number">7.2</span> Classificação Prado Jr-Milliet e distribuição numérica [§25–§28]</a></li>
  <li><a href="#distribuição-da-área-total-por-classe-de-tamanho-2932" id="toc-distribuição-da-área-total-por-classe-de-tamanho-2932" class="nav-link" data-scroll-target="#distribuição-da-área-total-por-classe-de-tamanho-2932"><span class="header-section-number">7.3</span> Distribuição da área total por classe de tamanho [§29–§32]</a></li>
  <li><a href="#percentis-e-coeficiente-de-gini-3336" id="toc-percentis-e-coeficiente-de-gini-3336" class="nav-link" data-scroll-target="#percentis-e-coeficiente-de-gini-3336"><span class="header-section-number">7.4</span> Percentis e coeficiente de Gini [§33–§36]</a></li>
  </ul></li>
  <li><a href="#desigualdade-na-terra-cultivada-e-nos-pés-de-café-pp.-2024" id="toc-desigualdade-na-terra-cultivada-e-nos-pés-de-café-pp.-2024" class="nav-link" data-scroll-target="#desigualdade-na-terra-cultivada-e-nos-pés-de-café-pp.-2024"><span class="header-section-number">8</span> Desigualdade na Terra Cultivada e nos Pés de Café (pp.&nbsp;20–24)</a>
  <ul class="collapse">
  <li><a href="#concentração-da-terra-cultivada-3740" id="toc-concentração-da-terra-cultivada-3740" class="nav-link" data-scroll-target="#concentração-da-terra-cultivada-3740"><span class="header-section-number">8.1</span> Concentração da terra cultivada [§37–§40]</a></li>
  <li><a href="#comparação-com-o-sul-dos-eua-4142" id="toc-comparação-com-o-sul-dos-eua-4142" class="nav-link" data-scroll-target="#comparação-com-o-sul-dos-eua-4142"><span class="header-section-number">8.2</span> Comparação com o sul dos EUA [§41–§42]</a></li>
  <li><a href="#concentração-dos-pés-de-café-4346" id="toc-concentração-dos-pés-de-café-4346" class="nav-link" data-scroll-target="#concentração-dos-pés-de-café-4346"><span class="header-section-number">8.3</span> Concentração dos pés de café [§43–§46]</a></li>
  </ul></li>
  <li><a href="#conclusão-pp.-2425" id="toc-conclusão-pp.-2425" class="nav-link" data-scroll-target="#conclusão-pp.-2425"><span class="header-section-number">9</span> Conclusão (pp.&nbsp;24–25)</a>
  <ul class="collapse">
  <li><a href="#síntese-dos-achados-4749" id="toc-síntese-dos-achados-4749" class="nav-link" data-scroll-target="#síntese-dos-achados-4749"><span class="header-section-number">9.1</span> Síntese dos achados [§47–§49]</a></li>
  <li><a href="#implicações-e-agenda-de-pesquisa-5052" id="toc-implicações-e-agenda-de-pesquisa-5052" class="nav-link" data-scroll-target="#implicações-e-agenda-de-pesquisa-5052"><span class="header-section-number">9.2</span> Implicações e agenda de pesquisa [§50–§52]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">10</span> Argumento Sintético</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: Land Inequality in a Coffee Economy: São Paulo During the Early Twentieth Century</h1>
<p class="subtitle lead">Colistete e Lamounier (2014)</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Economic History</div>
    <div class="quarto-category">Inequality</div>
    <div class="quarto-category">Quantitative Methods</div>
    <div class="quarto-category">Latin America</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">19 de abril de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>

<style>
.lang-toggle {
  position: fixed;
  top: 70px;
  right: 20px;
  z-index: 1000;
}
.lang-btn {
  background: transparent;
  border: 1px solid #666;
  border-radius: 4px;
  padding: 5px 12px;
  margin: 0 2px;
  cursor: pointer;
  font-size: 14px;
  transition: all 0.3s;
}
.lang-btn:hover {
  background: #f0f0f0;
}
.lang-btn.active {
  background: #0366d6;
  color: white;
  border-color: #0366d6;
}
.lang-content[lang]:not([lang="en"]) { display: none; }
.lang-content[lang="en"] { display: block; }
</style>
<section id="referência-apa-7" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="referência-apa-7"><span class="header-section-number">1</span> Referência APA 7</h2>
<p>Colistete, R. P., &amp; Lamounier, M. L. (2014). <em>Land Inequality in a Coffee Economy: São Paulo During the Early Twentieth Century</em> (Working Paper No.&nbsp;2014-1). Department of Economics, FEA-USP.</p>
</section>
<section id="entrada-bibtex" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="entrada-bibtex"><span class="header-section-number">2</span> Entrada BibTeX</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Entrada BibTeX → Colistete-Lamounier2014
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="va">@techreport</span>{<span class="ot">Colistete</span>-<span class="ot">Lamounier2014</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>      = {Renato P. Colistete and Maria Lucia Lamounier},</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>       = {Land Inequality in a Coffee Economy: São Paulo During the Early Twentieth Century},</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">institution</span> = {Department of Economics, FEA-USP},</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>        = {2014},</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">number</span>      = {2014-1},</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">type</span>        = {Working Paper}</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</div>
</div>
</section>
<section id="timestamp" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="timestamp"><span class="header-section-number">3</span> Timestamp</h2>
<p>Última atualização: 2026-04-19 Modelo: GPT-5 (OpenAI) — equivalente a GPT-5 / Claude 4 / Gemini Ultra 2.0 Gerado em: 2026-04-19T18:30:00-03:00</p>
</section>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v15.0</em>. A análise é adversarial sem ser destrutiva: identifica vulnerabilidades reais do argumento e reconhece contribuições genuínas com a mesma precisão. O raciocínio analítico subjacente a cada dimensão é registrado no campo <code>Raciocínio analítico</code> da tabela.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Nota</span>Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Instituição</strong></td>
<td style="text-align: left;">O cabeçalho do artigo (p.&nbsp;2) indica filiação dupla: Renato P. Colistete no Department of Economics, FEA-USP; Maria Lucia Lamounier na FEA-USP, Ribeirão Preto. O working paper é numerado 2014-1, sugerindo vínculo institucional formal. Não há informação sobre nível de formação (doutorado, etc.) no documento.</td>
<td style="text-align: left;">Department of Economics, FEA-USP (Universidade de São Paulo). Nível de formação não informado.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Questão de Pesquisa</strong></td>
<td style="text-align: left;">O artigo formula explicitamente na p.&nbsp;4: “how unequal was the distribution of land ownership in regions with a dynamic export agriculture?” A pergunta é <strong>descritiva</strong> (medir desigualdade) e <strong>comparativa</strong> (situar São Paulo em relação a outras regiões das Américas). A natureza descritiva é dominante, embora haja implicações para teorias de desenvolvimento (Engerman-Sokoloff).</td>
<td style="text-align: left;">“Quão desigual era a distribuição da propriedade da terra em regiões com agricultura de exportação dinâmica?” — Pergunta descritiva e comparativa, reconstruída a partir da p.&nbsp;4.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Questões Secundárias</strong></td>
<td style="text-align: left;">Derivam diretamente da pergunta central: (a) Qual era o grau de concentração de terra no nordeste paulista? (b) Havia variação significativa entre sub-regiões e municípios? (c) Como a desigualdade fundiária de São Paulo se compara à de outras regiões cafeeiras da América Latina e à do sul dos EUA? (d) A desigualdade se mantém quando se analisa terra cultivada e pés de café? Essas perguntas são operacionalizadas nas tabelas e índices.</td>
<td style="text-align: left;">1. Qual a estrutura de posse de terra (pequena, média, grande, latifúndio) no nordeste paulista em 1904-1905? 2. Existem diferenças regionais e municipais significativas na concentração? 3. Como a desigualdade paulista se compara à de Porto Rico, Colômbia, Costa Rica e ao sul dos EUA (antes da Guerra Civil)? 4. A concentração de terra cultivada e de pés de café segue o mesmo padrão da terra total?</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Puzzle-Type</strong></td>
<td style="text-align: left;">O artigo não apresenta um puzzle no sentido de anomalia empírica ou contradição teórica explícita. O “puzzle” implícito é a aparente contradição entre a predominância numérica de pequenos e médios proprietários (Tabela 2) e a alta concentração de área controlada pelos grandes proprietários (Tabela 3). Esse é um <strong>puzzle descritivo</strong> com implicações para teorias de desenvolvimento comparado (Engerman-Sokoloff). É generalizável para outras economias de plantation.</td>
<td style="text-align: left;"><strong>Puzzle descritivo</strong> implícito: como explicar a coexistência de uma grande quantidade de pequenos e médios proprietários (43,8% e 28,8% do número de proprietários, respectivamente) com níveis de concentração de terra comparáveis ou superiores aos de regiões escravistas (sul dos EUA)? O puzzle é genuíno e generalizável para outras economias de exportação agrícola com trabalho livre.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Conclusão / Argumento Central</strong></td>
<td style="text-align: left;">A tese central é apresentada na p.&nbsp;4 e reiterada na conclusão (p.&nbsp;24): a despeito da presença generalizada de pequenas e médias propriedades, o nordeste paulista exibia alta concentração de terra, com latifúndios controlando a maior parte da área total, cultivada e dos pés de café. O argumento é <strong>descritivo-comparativo</strong>, com um <em>claim of discovery</em> relativo à mensuração precisa da desigualdade fundiária na região. O suporte empírico vem de um censo detalhado (3.893 proprietários) e de múltiplas medidas de desigualdade (Gini, percentis, classificação Prado Jr-Milliet).</td>
<td style="text-align: left;">Apesar da predominância numérica de pequenas e médias propriedades no nordeste paulista (43,8% e 28,8% dos proprietários), a terra estava altamente concentrada: os 5% maiores proprietários controlavam 52,7% da área total (Gini 0,773), e os latifúndios (&gt;500 alqueires) detinham 52,6% da área. A desigualdade era maior do que nas regiões cafeeiras de pequena escala (Costa Rica, Colômbia) e comparável ou superior à do sul dos EUA escravista.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Métodos</strong></td>
<td style="text-align: left;">O estudo é quantitativo, baseado em censo agrícola nominal de 1904-1905. A fonte primária é a <em>Estatistica Agricola e Zootecnica do Estado de Sao Paulo</em>. Técnicas: estatística descritiva (média, mediana, desvio padrão), análise percentílica, coeficiente de Gini e índices de entropia generalizada (GE(0), GE(1), GE(2)). Classificação de propriedades adotada de Prado Jr (1945b) e Milliet (1941). Limitações: não há teste de hipóteses, análise de regressão ou controle de variáveis confundidoras; a inferência é estritamente descritiva.</td>
<td style="text-align: left;">Tipo de estudo: quantitativo descritivo-comparativo. Fonte: censo agrícola do Estado de São Paulo (1904-1905), com 3.893 proprietários em 13 municípios. Técnicas: estatística descritiva, percentis (10º, 25º, 50º, 75º, 80º, 90º, 95º, 99º), coeficiente de Gini, índices de entropia generalizada (GE(0), GE(1), GE(2)). Classificação de propriedades: pequenas (0-25 alqueires), médias (25-100), grandes (100-500), latifúndios (&gt;500) — adaptada de Prado Jr e Milliet. Limitação de identificação: não há análise causal; os autores medem desigualdade, não explicam suas causas.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Data Generation Process (DGP)</strong></td>
<td style="text-align: left;">O fenômeno é a distribuição de terra em uma economia cafeeira exportadora. A observação vem de um censo administrativo estadual, coletado pela Secretaria da Agricultura. A unidade de análise é o <strong>proprietário de terra</strong> (indivíduo). A operacionalização agrega múltiplas propriedades do mesmo dono no mesmo município. O nível de agregação para análise é o município e a região (Ribeirão Preto, Cajuru, Batatais, Franca). A inferência é descritiva: os autores comparam indicadores entre sub-regiões e com outras regiões (EUA, Porto Rico, Colômbia, Costa Rica) a partir de dados secundários da literatura. O DGP é adequado para a pergunta descritiva, mas não permite inferência causal sobre os determinantes da desigualdade.</td>
<td style="text-align: left;">Fenômeno: distribuição de posse de terra. Coleta: censo administrativo estadual de 1904-1905 (Secretaria da Agricultura). Unidade de análise: proprietário individual (com agregação de múltiplas fazendas por município). Operacionalização: área total em alqueires paulistas (1 alqueire = 2,42 ha), área cultivada, número de pés de café. Análise: estatística descritiva, percentis, Gini, entropia. Inferência: comparação de indicadores entre 13 municípios e 4 regiões, e com dados secundários da literatura (Porto Rico, Colômbia, Costa Rica, EUA).</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Achados e Contribuições</strong></td>
<td style="text-align: left;">Os principais achados empíricos: (a) 43,8% dos proprietários eram pequenos, mas controlavam apenas 2,8% da terra; (b) Gini total de terra = 0,773; (c) Sertãozinho (Gini 0,911) e Ribeirão Preto (0,847) eram os municípios mais desiguais; (d) a desigualdade em São Paulo era maior que em regiões cafeeiras de pequenos produtores (Costa Rica, Colômbia) e comparável/superior ao sul dos EUA. Contribuições: (i) preenche lacuna empírica sobre desigualdade fundiária paulista no início do século XX; (ii) fornece evidência quantitativa detalhada (por município) que qualifica generalizações anteriores (ex.: Franca como região de pequena propriedade); (iii) contribui para o debate Engerman-Sokoloff ao mostrar alta concentração mesmo em economia de trabalho livre imigrante.</td>
<td style="text-align: left;"><strong>Achados:</strong> (1) Pequenos proprietários (0-25 alq.) = 43,8% dos donos, mas apenas 2,8% da área. (2) Latifúndios (&gt;500 alq.) = 4,5% dos donos, mas 52,6% da área. (3) Gini da terra total = 0,773; terra cultivada = 0,757; pés de café = 0,766. (4) Franca, supostamente região de pequena propriedade, tinha apenas 10,5% de pequenos proprietários e Gini de 0,575 (terra total) — ainda assim desigual, mas menos que Ribeirão Preto. (5) Comparação internacional: Gini similar a Porto Rico (0,750), maior que Colômbia e Costa Rica, e maior que o sul dos EUA (0,575 para terra melhorada). <strong>Contribuições:</strong> Preenche lacuna empírica; fornece base para comparações sistemáticas; qualifica a literatura que enfatizava a presença de pequenos proprietários sem medir concentração.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Análise Crítica dos Achados</strong></td>
<td style="text-align: left;">O artigo responde adequadamente à pergunta descritiva. As vulnerabilidades incluem: (a) o censo de 1904-1905 é um instantâneo no tempo, sem série histórica; (b) a classificação Prado Jr-Milliet é arbitrária (embora os autores a defendam como conservadora); (c) a comparação com o sul dos EUA usa dados de 1860 (45 anos antes) e conceitos diferentes (“improved land” vs.&nbsp;terra total/cultivada), o que pode exagerar a diferença; (d) os autores não controlam para qualidade do solo, acesso a mercado ou infraestrutura ferroviária, que poderiam explicar a variação intra-regional; (e) a alegação de que o trabalho livre imigrante não reduziu a desigualdade é plausível, mas o design não permite testá-la causalmente. O DGP é adequado para descrição, não para explicação.</td>
<td style="text-align: left;"><strong>Adequação:</strong> O artigo responde à pergunta descritiva com rigor e transparência. <strong>Vulnerabilidades:</strong> (1) A comparação com o sul dos EUA usa dados de 1860 (antes da abolição) enquanto São Paulo é 1904-1905 (pós-abolição e com imigração em massa) — diferenças temporais e conceituais (“improved land” vs.&nbsp;terra cultivada) podem enviesar a comparação. (2) A classificação de tamanho de propriedade é arbitrária, embora os autores a defendam como conservadora (limites altos). (3) Não há análise de regressão para testar se a variação na desigualdade entre municípios está associada a fatores como tipo de solo, preço da terra, ou acesso à ferrovia — os autores descrevem a variação, mas não a explicam. (4) A inferência sobre as implicações para a tese Engerman-Sokoloff é especulativa, dado que o artigo não mede poder político ou políticas públicas. <strong>Scope conditions declaradas:</strong> nordeste paulista, 1904-1905, economia cafeeira. <strong>Omitidas:</strong> o artigo não discute se os resultados se aplicam a outras regiões cafeeiras do Brasil (sul de Minas, Espírito Santo, oeste paulista) ou a outros períodos.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Limitações</strong></td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> (p.&nbsp;4-5) os autores reconhecem que a classificação de tamanho é convencional e arbitrária; (p.&nbsp;12-13) admitem problemas na tipologia Prado Jr-Milliet (ex.: pequenas propriedades às vezes empregavam trabalhadores externos); (p.&nbsp;19) mencionam que o Gini pode não ser suficiente quando curvas de Lorenz se cruzam, e por isso usam índices de entropia. <strong>Não reconhecidas ou subestimadas:</strong> (1) A ausência de dados longitudinais — não se sabe se a desigualdade estava aumentando ou diminuindo. (2) O viés de seleção do censo: propriedades muito pequenas (posseiros sem título) podem estar sub-representadas. (3) A comparação internacional usa fontes secundárias com metodologias heterogêneas (diferentes definições de “terra”, diferentes anos). (4) O artigo não discute a qualidade dos dados do censo de 1904-1905 (subnotificação, evasão fiscal, etc.). (5) A análise não inclui terra pública não titulada (<em>terras devolutas</em>), que poderia ser relevante para a fronteira agrícola.</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> Arbitrariedade da classificação de tamanho (p.&nbsp;12-13); limitações do Gini quando curvas de Lorenz se cruzam (p.&nbsp;19); dificuldade de comparar com outras regiões devido a diferentes definições (p.&nbsp;13, 22).<br><br><strong>Não reconhecidas ou subestimadas:</strong> Viés de seleção do censo (posseiros sem título podem estar ausentes); ausência de série temporal (não permite análise de tendência); heterogeneidade metodológica nas comparações internacionais; falta de discussão sobre qualidade e cobertura do censo (subnotificação, evasão); exclusão de <em>terras devolutas</em> (terras públicas não ocupadas formalmente), que poderiam alterar a concentração medida.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Perspectiva Teórica</strong></td>
<td style="text-align: left;">Os autores operam dentro da tradição de <strong>história econômica institucional comparada</strong>, fortemente influenciada por Engerman e Sokoloff (1997, 2012). A premissa teórica central é que a desigualdade inicial (dotação de fatores) molda instituições e trajetórias de desenvolvimento. O artigo não testa essa teoria causalmente, mas fornece evidência descritiva consistente com a hipótese de que a concentração de terra em São Paulo era alta mesmo sem trabalho escravo. A ontologia implícita é realista: a desigualdade é um atributo mensurável da estrutura agrária. O método quantitativo descritivo é coerente com essa ontologia, mas o desenho não permite testar mecanismos causais.</td>
<td style="text-align: left;"><strong>Tradição teórica:</strong> Economia política institucional comparada (Engerman &amp; Sokoloff 1997, 2012; Acemoglu, Johnson &amp; Robinson 2001, 2002). <strong>Premissa central:</strong> a concentração inicial de ativos (terra, capital humano) molda instituições e desenvolvimento de longo prazo. <strong>Adequação:</strong> a moldura é adequada para situar a pergunta descritiva em um debate mais amplo, mas o artigo não testa a relação causal entre desigualdade e desenvolvimento. <strong>Coerência ontologia-método:</strong> ontologia realista (desigualdade como atributo mensurável do mundo) e método quantitativo descritivo são coerentes. A limitação é que a ontologia implícita trata a desigualdade como exógena, quando poderia ser endógena a políticas fundiárias, preços do café ou imigração.</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Principais Referências</strong></td>
<td style="text-align: left;">Os autores dialogam extensivamente com Engerman &amp; Sokoloff (1997, 2012), Acemoglu et al.&nbsp;(2001, 2002), e Williamson (1999) — ou seja, a literatura mainstream de história econômica institucional. Referências brasileiras clássicas incluem Caio Prado Jr (1942, 1945a, 1945b), Sérgio Milliet (1941), Warren Dean (1971, 1976), e Pierre Monbeig (1984). A literatura sobre café na América Latina (Gudmundson 1989; Roseberry 1995; Samper 1994) é bem representada. <strong>Diálogo pobre:</strong> o artigo não engaja com a literatura brasileira que enfatiza a resistência camponesa e a persistência da pequena propriedade (ex.: Maria Yedda Linhares, Hebe Mattos de Castro), nem com a historiografia marxista que vê o latifúndio como resultado da articulação com o capital internacional (ex.: Caio Prado Jr é citado, mas sem engajamento crítico profundo).</td>
<td style="text-align: left;"><strong>Centrais:</strong> Engerman &amp; Sokoloff (1997, 2012); Acemoglu, Johnson &amp; Robinson (2001, 2002); Prado Jr (1945b); Milliet (1941); Dean (1976); Gudmundson (1989); Samper (1994). <strong>Diálogo pobre ou desequilibrado:</strong> (1) A literatura brasileira recente sobre estrutura fundiária e campesinato (Linhares 1983; Castro 1988; Fragoso &amp; Florentino 1993) é citada na p.&nbsp;11, mas não integrada à análise substantiva. (2) A tese de que a pequena propriedade em Franca era relevante (Oliveira 1997, 2006; Tosi, Faleiros &amp; Teodoro 2007) é mencionada (p.&nbsp;10), mas os autores a refutam com dados sem discutir possíveis mudanças temporais ou definições de “pequeno”. (3) Não há engajamento com a literatura sobre <em>terras devolutas</em> e grilagem (Cobra 1923; Lima 1935), que poderia explicar a concentração.</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Observações</strong></td>
<td style="text-align: left;"><strong>Vulnerabilidades adicionais:</strong> (1) O artigo não discute a possibilidade de que a concentração de terra medida seja um artefato da unidade de análise (município). Se um proprietário tivesse terras em múltiplos municípios, os autores agregaram apenas dentro do mesmo município (p.&nbsp;10) — isso pode subestimar a concentração. (2) A comparação com o sul dos EUA em 1860 ignora o fato de que a produção de café em São Paulo em 1904-1905 já estava em uma fase de maturidade, enquanto o algodão no sul dos EUA em 1860 estava em expansão. (3) A ausência de dados sobre arrendamento e parceria (<em>colonato</em>) significa que a desigualdade no <em>acesso</em> à terra (não apenas na propriedade) pode ser diferente. <strong>Relação com pesquisa do leitor:</strong> O artigo é útil para pesquisadores interessados em desigualdade fundiária comparada, história econômica do café, e testes empíricos da hipótese Engerman-Sokoloff. <strong>Omissão crítica:</strong> Os autores não discutem o papel do estado na reprodução da desigualdade (leis de terra, política fiscal, crédito subsidiado), o que limitaria a utilidade do artigo para explicar, e não apenas descrever, a concentração.</td>
<td style="text-align: left;"><strong>Vulnerabilidades adicionais:</strong> (a) Agregação de propriedades por município, mas não entre municípios — um grande proprietário com terras em Ribeirão Preto e Franca seria contado separadamente, subestimando a concentração real. (b) A comparação com o sul dos EUA usa dados de “improved land” (terra melhorada) enquanto o artigo usa “cultivated land” e “total farmland” — os conceitos não são equivalentes. (c) Ausência de dados sobre formas de acesso à terra diferentes da propriedade plena (arrendamento, parceria, posse) pode subestimar a desigualdade de <em>controle</em> sobre a terra, já que muitos trabalhadores imigrantes eram <em>colonos</em> (parceiros) sem propriedade. <strong>Lacuna teórica:</strong> O artigo não articula um mecanismo causal que explique por que a imigração em massa e o trabalho livre não reduziram a concentração — isso enfraquece a contribuição para o debate Engerman-Sokoloff. <strong>Implicações para o argumento:</strong> A ausência de discussão sobre políticas fundiárias (Lei de Terras de 1850, grilagem, colonização oficial) deixa uma lacuna explicativa: a concentração pode ser resultado não apenas de “fatores iniciais”, mas de ação estatal deliberada.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="introdução-e-contexto-teórico-pp.-15" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="introdução-e-contexto-teórico-pp.-15"><span class="header-section-number">4</span> Introdução e Contexto Teórico (pp.&nbsp;1–5)</h2>
<section id="apresentação-do-problema-e-lacuna-na-literatura-14" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="apresentação-do-problema-e-lacuna-na-literatura-14"><span class="header-section-number">4.1</span> Apresentação do problema e lacuna na literatura [§1–§4]</h3>
<p><strong>§1</strong> O artigo se insere no debate sobre as origens da desigualdade na América Latina, que serve como “laboratório” para testar teorias sobre a relação entre desigualdade e desenvolvimento econômico. Os autores mencionam obras clássicas (Prado Jr 1942, 1945a; Bagú 1949; Furtado 1959, 1969) e o renascimento recente do interesse impulsionado por Engerman e Sokoloff (1997, 2012), Acemoglu, Johnson e Robinson (2001, 2002), e outros.</p>
<p><strong>§2</strong> Apesar do interesse, os dados disponíveis para calcular a desigualdade passada na América Latina são escassos e frequentemente não representativos. Métodos alternativos incluem atribuir rendas a classes ocupacionais ou usar proxies como razões aluguel-salário. Os autores criticam essas estratégias por problemas de amostragem, evidência frágil e extrapolações injustificadas.</p>
<p><strong>§3</strong> Como estratégia alternativa, os autores propõem análises baseadas em fontes primárias cuidadosamente coletadas, como inventários <em>post-mortem</em>, registros fiscais, listas eleitorais e censos econômicos. Essas fontes têm dificuldades conceituais, mas oferecem evidência detalhada para lidar com representatividade e generalização. Além disso, um foco regional ajuda a identificar influências de especializações produtivas e instituições locais frequentemente negligenciadas quando a unidade de análise é a economia nacional.</p>
<p><strong>§4</strong> O artigo trata de um aspecto específico da desigualdade nas Américas: <strong>quão desigual era a distribuição da propriedade da terra em regiões com agricultura de exportação dinâmica?</strong> O foco é o nordeste do estado de São Paulo durante os anos dourados da economia cafeeira (início do século XX), quando a região era a maior produtora de café do estado e do mundo. A fonte é a <em>Estatistica Agricola do Estado de Sao Paulo</em> (1904-1905), com dados de 3.893 proprietários.</p>
</section>
<section id="objetivos-método-e-achados-preliminares-58" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="objetivos-método-e-achados-preliminares-58"><span class="header-section-number">4.2</span> Objetivos, método e achados preliminares [§5–§8]</h3>
<blockquote class="blockquote">
<p><strong>Puzzle implícito do artigo:</strong> “Como explicar a coexistência de uma vasta maioria de pequenos e médios proprietários (72,6% do número total de proprietários) com níveis de concentração de terra comparáveis ou superiores aos de regiões escravistas como o sul dos Estados Unidos?”</p>
</blockquote>
<p><strong>§5</strong> O artigo destaca a variação regional na estrutura fundiária, mesmo dentro de uma área geográfica onde o crescimento econômico era largamente impulsionado pelo café. A maioria esmagadora das fazendas era de pequenos e médios proprietários, mas isso não se traduziu em uma estrutura fundiária “democrática”: a maior parte da área total, cultivada e dos pés de café era controlada por relativamente poucos grandes fazendeiros.</p>
<p><strong>§6</strong> A desigualdade no nordeste paulista era tão alta quanto em outras áreas cafeeiras da América Latina (ex.: distrito de Yauco em Porto Rico) e significativamente maior do que em regiões cafeeiras tradicionais de produção em pequena escala na Costa Rica e Colômbia.</p>
<p><strong>§7</strong> Para fins comparativos, a agricultura cafeeira do nordeste paulista mostra desigualdade fundiária tão alta ou maior do que a região algodoeira do sul dos EUA na era anterior à Guerra Civil. Isso corrobora a noção de Engerman e Sokoloff (1997; 2012) de que a posse da terra tendia a ser mais concentrada na América Latina do que nos Estados Unidos. Mesmo baseada em trabalho livre e força de trabalho imigrante em massa, a agricultura cafeeira paulista estava em situação desfavorável em termos de desigualdade fundiária quando comparada aos estados agrícolas do norte dos EUA ou mesmo à economia escravista de exportação de algodão do sul.</p>
<p><strong>§8</strong> O artigo se organiza em: (i) panorama da economia cafeeira em São Paulo; (ii) evidência sobre a distribuição de terra no nordeste paulista usando medidas quantitativas; (iii) sumário dos achados e conclusões.</p>
</section>
</section>
<section id="grandes-e-pequenas-fazendas-na-agricultura-paulista-pp.-57" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="grandes-e-pequenas-fazendas-na-agricultura-paulista-pp.-57"><span class="header-section-number">5</span> Grandes e Pequenas Fazendas na Agricultura Paulista (pp.&nbsp;5–7)</h2>
<section id="política-fundiária-e-obstáculos-à-pequena-propriedade-912" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="política-fundiária-e-obstáculos-à-pequena-propriedade-912"><span class="header-section-number">5.1</span> Política fundiária e obstáculos à pequena propriedade [§9–§12]</h3>
<p><strong>§9</strong> Após a independência (1822), o parlamento e os governos provinciais tenderam a favorecer políticas que preservavam a grande propriedade como fundamento do sistema agrário, assim como as antigas <em>sesmarias</em> no período colonial. Intelectuais e altos burocratas às vezes destacavam as vantagens da pequena propriedade na Europa Ocidental e nos EUA, mas não conseguiram vencer os interesses fundiários do nordeste e sudeste brasileiros, firmemente representados no parlamento. O assentamento de pequenos proprietários (principalmente imigrantes europeus) pelo governo imperial só teve sucesso nas províncias do sul (Rio Grande do Sul e Santa Catarina) e em uma pequena região do sudeste (Espírito Santo), provavelmente devido à necessidade de proteger as fronteiras e à ausência de uma classe fundiária mobilizada nessas regiões.</p>
<p><strong>§10</strong> Nas áreas agrícolas tradicionais onde a produção em larga escala se desenvolveu, houve vários obstáculos à expansão da pequena propriedade. Durante o século XIX, os governos provinciais geralmente evitavam promover o assentamento de pequenos proprietários mesmo nas regiões de fronteira agrícola em expansão. Warren Dean, descrevendo a transformação de Rio Claro em um grande município cafeeiro em meados do século XIX, observou que os formuladores de políticas no Brasil acreditavam que “apenas os ricos e bem-nascidos poderiam exibir qualidades empreendedoras”.</p>
<p><strong>§11</strong> Mesmo na ausência de uma política de homestead, pequenos proprietários continuaram a comprar, ocupar, limpar e cultivar terra na fronteira paulista ao longo do século XIX. No entanto, com o advento de culturas de exportação como açúcar e café, os pequenos proprietários enfrentaram a ameaça de despejo por novos proprietários que compravam ou simplesmente tomavam grandes lotes de terra. Alguns desses pequenos produtores foram despossuídos e forçados a se mudar para a fronteira, outros foram incorporados como trabalhadores dependentes (<em>agregados</em>) nas grandes fazendas. A Lei de Terras de 1850, que determinava que terras públicas só poderiam ser alienadas por venda, não melhorou a situação dos pequenos proprietários.</p>
<p><strong>§12</strong> A posição dos pequenos proprietários mudou apenas marginalmente com a chegada de imigrantes europeus a São Paulo em meados do século XIX. A partir de 1887, a imigração europeia em massa foi canalizada principalmente para fornecer mão de obra abundante para as grandes fazendas de café. Os poucos núcleos oficiais de colonização espalhados pelo interior paulista, que vendiam pequenos lotes parcelados, assentaram apenas 933 famílias até 1908.</p>
</section>
<section id="ocupação-de-terras-e-flexibilidade-do-café-1315" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="ocupação-de-terras-e-flexibilidade-do-café-1315"><span class="header-section-number">5.2</span> Ocupação de terras e flexibilidade do café [§13–§15]</h3>
<p><strong>§13</strong> Pequenos proprietários sem títulos de propriedade não estavam sozinhos na fronteira agrícola. Posseiros de grandes áreas foram capazes de tomar vastas extensões de terra através de suas conexões especiais com autoridades legais e políticas. Títulos de terra podiam ser concedidos com base em uma alegada primeira ocupação de terra pública (<em>terra devoluta</em>) ou simplesmente falsificando a documentação com a ajuda de funcionários e políticos locais. A maior parte dessas terras foi particionada nos anos seguintes, mas a estrutura agrária remanescente tendia a manter uma parcela desproporcional de terra nas mãos de grandes proprietários.</p>
<p><strong>§14</strong> Somente no início do século XX o aumento do número de pequenas propriedades se tornou mais substancial, como resultado da imigração, do aumento das rendas e do declínio relativo das propriedades extremamente grandes em zonas agrícolas antigas e novas. Companhias de colonização começaram a vender pequenos lotes de terra no noroeste e sudoeste do estado de São Paulo (e norte do Paraná), que haviam sido apenas esparsamente ocupados pela população não nativa antes de 1900.</p>
<p><strong>§15</strong> O café era suficientemente flexível para ser cultivado em vários tipos e tamanhos de terra. Como Lowell Gudmundson apontou, “o café era produzido por uma ampla variedade de elementos sociais, do campesinato à plutocracia […] De fato, de todas as principais atividades de exportação agrícola desenvolvidas na região [América Latina] após meados do século XIX, o café foi talvez a mais conciliável, em certos contextos, com a pequena propriedade e cultivo”. No entanto, a concentração da propriedade, e não o número absoluto de pequenos proprietários, é o que mais importa para a distribuição do poder econômico e suas implicações de longo prazo.</p>
</section>
</section>
<section id="a-economia-cafeeira-no-nordeste-de-são-paulo-pp.-810" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="a-economia-cafeeira-no-nordeste-de-são-paulo-pp.-810"><span class="header-section-number">6</span> A Economia Cafeeira no Nordeste de São Paulo (pp.&nbsp;8–10)</h2>
<section id="caracterização-da-região-e-expansão-do-café-1619" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="caracterização-da-região-e-expansão-do-café-1619"><span class="header-section-number">6.1</span> Caracterização da região e expansão do café [§16–§19]</h3>
<p><strong>§16</strong> O nordeste paulista compreendia 13 municípios: Ribeirão Preto, Cravinhos, Sertãozinho, São Simão, Cajuru, Santo Antônio d’Alegria, Batatais, Nuporanga, Jardinópolis, Franca, Ituverava, Patrocínio do Sapucaí e Santa Rita do Paraíso (mais tarde Igarapava). Juntos, representavam 9,3% da população do estado (1907), mas 20,1% da produção total de café (1905). Na época, Ribeirão Preto e São Simão eram os maiores produtores de café do estado, e o porto de Santos respondia por 72,8% das exportações brasileiras e 52,1% das exportações mundiais de café.</p>
<p><strong>§17</strong> A colonização do nordeste paulista data do início do século XVIII, com a venda de sal e gado para as minas recém-descobertas em Goiás e Mato Grosso. Em 1805, a localidade foi estabelecida como freguesia, tornando-se o município de Vila Franca do Imperador (1824), depois Franca (1856). Com o crescimento econômico e populacional, novos distritos e municípios foram criados: Batatais (1839), São Simão (1865), Cajuru (1865), Ribeirão Preto (1871), Santa Rita do Paraíso (1873) e Sertãozinho (1896).</p>
<p><strong>§18</strong> Viajantes que cruzavam a região no início do século XIX registraram a produção de alimentos, tecidos de algodão grosseiros, chapéus e armas de fogo, mas apontaram que sua atividade mais dinâmica era a exportação de gado para outras regiões de São Paulo e Brasil. Em 1836, a área nordeste (então consistindo apenas de Franca) produzia 5,5% da farinha de mandioca, 4% do milho e 3% do fumo da província de São Paulo. Destacava-se, no entanto, na produção pecuária: 20,1% das ovelhas, 10,3% do gado e 9,4% dos porcos criados em São Paulo vinham do nordeste. A produção de café era insignificante até meados do século.</p>
<p><strong>§19</strong> O café começou a ser cultivado em São Paulo no final do século XVIII na região da costa norte e no Vale do Paraíba, alcançando Campinas por volta de 1830. Nas décadas seguintes, o café se espalhou para o interior, incluindo o nordeste. A expansão da fronteira cafeeira foi grandemente estimulada pelo desenvolvimento de uma rede ferroviária construída por empresas privadas como a Paulista e a Mogiana. Os municípios servidos pela ferrovia no final do século XIX e início do XX incluíam São Simão (1882), Ribeirão Preto (1883), Batatais (1886), Franca (1887), Sertãozinho (1899), Ituverava (1903) e Igarapava (1914).</p>
</section>
<section id="variação-regional-na-estrutura-fundiária-2021" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="variação-regional-na-estrutura-fundiária-2021"><span class="header-section-number">6.2</span> Variação regional na estrutura fundiária [§20–§21]</h3>
<p><strong>§20</strong> A chegada do café teve impacto direto nos mercados de terra, com especulação generalizada e aumento dramático dos preços da terra. O preço por hectare de terra fértil em Batatais e Nuporanga aumentou doze vezes entre 1850 e 1890. No entanto, o efeito na estrutura fundiária diferiu significativamente entre as sub-regiões. Ribeirão Preto é conhecida por suas enormes plantações e fazendeiros lendários (Henrique Dumont, Francisco Schmidt, Martinho Prado Jr.), com consolidação de grandes propriedades predominando. Franca, por outro lado, tem sido descrita como um exemplo onde pequenas propriedades familiares dominavam a paisagem — devido ao assentamento antigo por agricultores com poucos recursos, especializados no abastecimento de alimentos e gado para o mercado doméstico, e à falta do melhor solo para o café.</p>
<p><strong>§21</strong> O artigo se propõe a avaliar essas visões com evidência quantitativa do censo de 1904-1905.</p>
</section>
</section>
<section id="estrutura-fundiária-e-distribuição-de-tamanho-pp.-1016" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="estrutura-fundiária-e-distribuição-de-tamanho-pp.-1016"><span class="header-section-number">7</span> Estrutura Fundiária e Distribuição de Tamanho (pp.&nbsp;10–16)</h2>
<section id="fonte-de-dados-e-estatísticas-descritivas-2224" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="fonte-de-dados-e-estatísticas-descritivas-2224"><span class="header-section-number">7.1</span> Fonte de dados e estatísticas descritivas [§22–§24]</h3>
<p><strong>§22</strong> A fonte é o censo da Secretaria da Agricultura do estado de São Paulo para o ano agrícola de 1904-1905, que fornece dados detalhados sobre fazendas, incluindo nome do proprietário, tamanho da propriedade, área cultivada e culturas produzidas. Os autores identificaram 3.893 proprietários nos 13 municípios, agregando propriedades de um mesmo indivíduo dentro do mesmo município. Os 13 municípios foram divididos em quatro regiões: Ribeirão Preto, Cajuru, Batatais e Franca.</p>
<p><strong>§23</strong> A <strong>Tabela 1</strong> (p.&nbsp;11) apresenta estatísticas descritivas da área total de terra. O número de proprietários variou de 507 em Nuporanga a 83 em Cravinhos. A área média foi maior em Nuporanga (336 alqueires) e menor em Santo Antônio d’Alegria (27 alqueires). A média é sempre muito superior à mediana, indicando distribuição assimétrica com cauda direita (poucos valores muito altos). O desvio padrão e o coeficiente de variação mostram alta heterogeneidade em Jardinópolis e Sertãozinho. A área mínima varia de 0,25 alqueire a enormes propriedades com mais de 1.000 alqueires — a maior foi em Nuporanga (17.000 alqueires). Um alqueire paulista equivale a 2,42 hectares.</p>
<blockquote class="blockquote">
<p><strong>Conversão de unidades:</strong> 1 alqueire paulista = 2,42 hectares = 5,98 acres. Uma propriedade de 500 alqueires (limite inferior para latifúndio) equivale a 1.210 hectares ou cerca de 2.990 acres.</p>
</blockquote>
</section>
<section id="classificação-prado-jr-milliet-e-distribuição-numérica-2528" class="level3" data-number="7.2">
<h3 data-number="7.2" class="anchored" data-anchor-id="classificação-prado-jr-milliet-e-distribuição-numérica-2528"><span class="header-section-number">7.2</span> Classificação Prado Jr-Milliet e distribuição numérica [§25–§28]</h3>
<p><strong>§25</strong> Os autores adotam a classificação de Caio Prado Jr (1935/1945b) modificada por Sérgio Milliet (1941): <strong>pequenas</strong> (0-25 alqueires), <strong>médias</strong> (25-100), <strong>grandes</strong> (100-500) e <strong>latifúndios</strong> (&gt;500 alqueires). A classificação é convencional e arbitrária, mas os autores argumentam que os limites são altos o suficiente para não superestimar a concentração.</p>
<p><strong>§26</strong> A <strong>Tabela 2</strong> (p.&nbsp;14) mostra a distribuição do <em>número</em> de proprietários por classe de tamanho. Pequenos proprietários representavam 43,8% de todos os proprietários no nordeste paulista. Médias (28,8%) e grandes (22,8%) tinham participações significativamente menores, e latifundiários apenas 4,5%. No entanto, há variação substancial entre municípios: a porcentagem de pequenos proprietários variou de 2,8% em Nuporanga a 74% em Santo Antônio d’Alegria.</p>
<p><strong>§27</strong> Surpreendentemente, Franca — descrita pela historiografia como região de pequena propriedade — tinha uma das menores participações de pequenos proprietários (10,5%), com a maioria composta por médios (50,1%) e grandes (34,9%). Também surpreendente: Ribeirão Preto, conhecida pelos “reis do café”, tinha 53,9% de pequenos proprietários — uma parcela maior que a de Franca.</p>
<p><strong>§28</strong> A conclusão provisória é que a predominância numérica de pequenos proprietários não significa necessariamente uma estrutura fundiária igualitária. Para avaliar a concentração real, é necessário analisar a área controlada por cada classe.</p>
</section>
<section id="distribuição-da-área-total-por-classe-de-tamanho-2932" class="level3" data-number="7.3">
<h3 data-number="7.3" class="anchored" data-anchor-id="distribuição-da-área-total-por-classe-de-tamanho-2932"><span class="header-section-number">7.3</span> Distribuição da área total por classe de tamanho [§29–§32]</h3>
<p><strong>§29</strong> A <strong>Tabela 3</strong> (pp.&nbsp;14-15) mostra a porcentagem da área total de terra por classe de tamanho. Pequenas propriedades controlavam apenas <strong>2,8%</strong> da área total do nordeste paulista, médias 11,4%, grandes 33,1% e latifúndios <strong>52,6%</strong>. Ou seja, 4,5% dos proprietários (latifundiários) controlavam mais da metade da terra.</p>
<p><strong>§30</strong> A única região onde pequenas propriedades tinham alguma importância em termos de área foi Cajuru (13,2%). Em todas as outras regiões, pequenos proprietários detinham no máximo 3,5% da área. Em Franca, a área controlada por pequenos proprietários era de apenas 1,2% — menor do que em Ribeirão Preto (2,5%).</p>
<p><strong>§31</strong> Grandes propriedades e latifúndios mostraram variação substancial entre regiões. Ribeirão Preto e Sertãozinho tinham a presença mais disseminada de latifúndios: 75,8% e 76,5% da área total, respectivamente. Em contraste, em Franca e Patrocínio do Sapucaí os latifúndios ocupavam 34,7% e 38,6% da área. No entanto, mesmo em Franca, a combinação de grandes propriedades (44,4%) e latifúndios (34,7%) totalizava 79,1% da área.</p>
<p><strong>§32</strong> A Tabela 3 também revela que em São Simão (região de Ribeirão Preto) os latifúndios ocupavam apenas 35,9% da área — bem menos que a média regional — indicando que mesmo dentro de regiões de alta concentração havia municípios com estrutura menos desigual.</p>
</section>
<section id="percentis-e-coeficiente-de-gini-3336" class="level3" data-number="7.4">
<h3 data-number="7.4" class="anchored" data-anchor-id="percentis-e-coeficiente-de-gini-3336"><span class="header-section-number">7.4</span> Percentis e coeficiente de Gini [§33–§36]</h3>
<p><strong>§33</strong> Os autores complementam a análise com percentis e coeficiente de Gini (Tabela 4, p.&nbsp;17). No nordeste paulista como um todo, o <strong>Gini da terra total foi 0,773</strong> — um valor alto, indicando concentração extrema. O topo 5% dos proprietários controlava 52,7% da área, enquanto os 50% inferiores controlavam apenas 4,1%.</p>
<p><strong>§34</strong> A região de Ribeirão Preto apresentou a maior concentração (Gini 0,838; top 5% com 66,3% da área). Franca foi a região com menor participação do topo (41,6% para os 5% superiores, Gini 0,674). No entanto, o limiar para estar no top 5% em Franca era maior (500 alqueires) do que em Ribeirão Preto (420 alqueires), mostrando que “menor desigualdade” não significa “pequenas propriedades predominam” — significa que havia mais proprietários de tamanho médio-grande, não que houvesse muitos pequenos.</p>
<p><strong>§35</strong> Sertãozinho foi o município mais desigual (Gini 0,911; top 5% com 80,5% da área). Jardinópolis também teve Gini muito alto (0,880). Os municípios menos desiguais foram Santo Antônio d’Alegria (Gini 0,628), Franca (0,575) e Patrocínio do Sapucaí (0,599).</p>
<p><strong>§36</strong> Os índices de entropia generalizada (Apêndice, Tabela 4A) confirmam a ordenação: Sertãozinho tem o GE(2) mais alto (21,247), indicando forte sensibilidade a diferenças no topo da distribuição; Patrocínio do Sapucaí tem o GE(2) mais baixo (1,122). Os autores observam que, quando as curvas de Lorenz se cruzam, o Gini pode não ser suficiente, mas nesse caso os índices convergem.</p>
</section>
</section>
<section id="desigualdade-na-terra-cultivada-e-nos-pés-de-café-pp.-2024" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="desigualdade-na-terra-cultivada-e-nos-pés-de-café-pp.-2024"><span class="header-section-number">8</span> Desigualdade na Terra Cultivada e nos Pés de Café (pp.&nbsp;20–24)</h2>
<section id="concentração-da-terra-cultivada-3740" class="level3" data-number="8.1">
<h3 data-number="8.1" class="anchored" data-anchor-id="concentração-da-terra-cultivada-3740"><span class="header-section-number">8.1</span> Concentração da terra cultivada [§37–§40]</h3>
<p><strong>§37</strong> Os autores argumentam que a terra cultivada é uma medida mais relevante do status econômico do que a terra total, já que vastas extensões podiam ser usadas para pasto ou deixadas em pousio. A <strong>Tabela 5</strong> (p.&nbsp;21) mostra os indicadores de desigualdade para terra cultivada.</p>
<p><strong>§38</strong> A concentração da terra cultivada era ainda maior do que a da terra total: o top 5% dos proprietários controlava 55,9% da área cultivada (contra 52,7% da terra total), e o top 20% controlava 82,4%. Os 50% inferiores mantinham cerca de 4% — praticamente o mesmo que para terra total.</p>
<p><strong>§39</strong> O Gini da terra cultivada no nordeste paulista foi 0,757 (ligeiramente menor que o Gini da terra total, 0,773). A região de Ribeirão Preto novamente apresentou a maior concentração (Gini 0,761; top 5% com 49,5% da área cultivada). A região de Cajuru teve o Gini mais baixo (0,560), com o top 5% controlando 36,3% da área cultivada.</p>
<p><strong>§40</strong> No entanto, o significado desses percentis variava muito entre regiões. O limiar para estar no top 5% da terra cultivada era de 200 alqueires em Ribeirão Preto, mas apenas 44 alqueires em Franca e 70 em Batatais (Apêndice, Tabela 2A). Isso significa que, embora a desigualdade <em>medida pelo Gini</em> fosse maior em Ribeirão Preto, a escala absoluta das propriedades também era muito maior.</p>
</section>
<section id="comparação-com-o-sul-dos-eua-4142" class="level3" data-number="8.2">
<h3 data-number="8.2" class="anchored" data-anchor-id="comparação-com-o-sul-dos-eua-4142"><span class="header-section-number">8.2</span> Comparação com o sul dos EUA [§41–§42]</h3>
<p><strong>§41</strong> Os autores comparam seus resultados com dados do sul dos EUA em 1860 (Wright 1970). No sul algodoeiro, o Gini da terra melhorada (<em>improved land</em>) era 0,575 — muito inferior ao 0,757 do nordeste paulista. O top 5% dos agricultores controlava 29,6% da terra melhorada no sul dos EUA, contra 55,9% em São Paulo.</p>
<p><strong>§42</strong> Surpreendentemente, a <em>mediana</em> da área cultivada em São Paulo (5,8 alqueires = 34,7 acres) era muito menor do que no sul dos EUA (70,6 acres) e até menor do que em estados do norte dos EUA (Ohio: 64,8 acres; Indiana: 50,9 acres; Wisconsin: 41,8 acres). Ou seja, a existência de muitos pequenos produtores em São Paulo não reduzia a desigualdade agregada porque os poucos grandes produtores controlavam uma parcela desproporcional da terra.</p>
</section>
<section id="concentração-dos-pés-de-café-4346" class="level3" data-number="8.3">
<h3 data-number="8.3" class="anchored" data-anchor-id="concentração-dos-pés-de-café-4346"><span class="header-section-number">8.3</span> Concentração dos pés de café [§43–§46]</h3>
<p><strong>§43</strong> A <strong>Tabela 6</strong> (p.&nbsp;23) mostra a distribuição dos pés de café — uma medida direta da capacidade produtiva cafeeira. A concentração é semelhante à da terra cultivada: o top 5% dos proprietários detinha 50,2% dos pés de café, e os 50% inferiores apenas 5,5%. O Gini dos pés de café foi 0,766.</p>
<p><strong>§44</strong> A região de Ribeirão Preto liderava (top 5% com 43,2% dos pés; Gini 0,743), enquanto Franca tinha menor concentração (top 5% com 27%; Gini 0,646). No entanto, o número absoluto de pés de café no topo era muito maior em Ribeirão Preto: o limiar para o 95º percentil era 400.000 pés, contra 100.000 em Franca (Apêndice, Tabela 3A).</p>
<p><strong>§45</strong> Santo Antônio d’Alegria foi o município com menor desigualdade na distribuição de pés de café (Gini 0,326; top 5% com 10,5%), e também o único onde os 50% inferiores detinham uma parcela significativa (27,9%). Esse município parece ser uma exceção à regra geral de alta concentração.</p>
<p><strong>§46</strong> Os autores concluem que, mesmo considerando apenas a terra efetivamente usada para produção (cultivada) ou a cultura comercial mais importante (café), a desigualdade no nordeste paulista era extremamente alta — maior do que em qualquer região dos EUA no século XIX, e comparável apenas a outras regiões de plantation nas Américas.</p>
</section>
</section>
<section id="conclusão-pp.-2425" class="level2" data-number="9">
<h2 data-number="9" class="anchored" data-anchor-id="conclusão-pp.-2425"><span class="header-section-number">9</span> Conclusão (pp.&nbsp;24–25)</h2>
<section id="síntese-dos-achados-4749" class="level3" data-number="9.1">
<h3 data-number="9.1" class="anchored" data-anchor-id="síntese-dos-achados-4749"><span class="header-section-number">9.1</span> Síntese dos achados [§47–§49]</h3>
<p><strong>§47</strong> O artigo demonstrou que, embora a maioria das propriedades no nordeste paulista fosse de pequenos e médios proprietários, a terra estava altamente concentrada. A classificação por tamanho mostrou que a maior parte da terra era controlada por grandes proprietários e latifundiários. A presença numérica de pequenos e médios proprietários não se traduziu em uma estrutura fundiária “democrática”.</p>
<p><strong>§48</strong> As estimativas de desigualdade (percentis, Gini, índices de entropia) corroboram essa conclusão: a elite fundiária controlava a maioria dos recursos produtivos. A classe média-alta de proprietários era importante em quase todos os municípios, mas mesmo onde a desigualdade era relativamente menor, os pequenos proprietários controlavam uma parcela pequena da riqueza agrícola. Os 50% inferiores detinham cerca de 4-5% da área ou dos pés de café.</p>
<p><strong>§49</strong> A comparação internacional mostra que a desigualdade fundiária em São Paulo era similar à de Porto Rico (Yauco, Gini 0,750), mas significativamente maior do que em regiões cafeeiras tradicionais de pequena escala na Colômbia e Costa Rica. Em comparação com os EUA do século XIX, a desigualdade em São Paulo era substancialmente maior do que nos estados agrícolas do norte, e pelo menos equivalente ou maior do que no sul algodoeiro — especialmente quando se usa terra melhorada como medida.</p>
</section>
<section id="implicações-e-agenda-de-pesquisa-5052" class="level3" data-number="9.2">
<h3 data-number="9.2" class="anchored" data-anchor-id="implicações-e-agenda-de-pesquisa-5052"><span class="header-section-number">9.2</span> Implicações e agenda de pesquisa [§50–§52]</h3>
<p><strong>§50</strong> Os autores argumentam que o resultado não se deve à ausência de pequenas ou médias unidades produtivas em São Paulo. Pelo contrário, a mediana da área cultivada em São Paulo era significativamente menor do que no sul dos EUA ou nos estados do norte. O que impulsionava a desigualdade era o <strong>grande proprietário</strong>, que contribuía desproporcionalmente para os indicadores de concentração.</p>
<blockquote class="blockquote">
<p><strong>Implicação para a tese Engerman-Sokoloff:</strong> O artigo fornece evidência de que mesmo em uma economia de trabalho livre imigrante (não escravista) e com uma classe média de proprietários significativa, a concentração de terra poderia ser extremamente alta — comparável ou superior à de regiões escravistas. Isso sugere que o trabalho escravo não é condição necessária para alta desigualdade fundiária.</p>
</blockquote>
<p><strong>§51</strong> Os autores reconhecem que as conclusões se aplicam a uma região que não deve ser considerada necessariamente representativa da agricultura de exportação brasileira como um todo — pelo menos até que a concentração de terra em outras áreas geográficas seja mais completamente investigada. No entanto, o cenário descrito para o nordeste paulista é “um passo adiante para entender as formas de desigualdade que influenciaram o desenvolvimento de longo prazo no Brasil e em outras partes das Américas”.</p>
<p><strong>§52</strong> O artigo conclui com a nota de que a pesquisa futura deve investigar outras regiões e períodos para determinar se o padrão de alta concentração com muitos pequenos proprietários é geral ou específico do nordeste paulista cafeeiro.</p>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="10">
<h2 data-number="10" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">10</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Nota
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> Apesar da predominância numérica de pequenos e médios proprietários no nordeste paulista (72,6% dos proprietários), a terra estava altamente concentrada, com os latifúndios (&gt;500 alqueires) controlando 52,6% da área total e os 5% maiores proprietários detendo 52,7% da terra (Gini = 0,773) — níveis de desigualdade superiores aos das regiões cafeeiras de pequena escala da Costa Rica e Colômbia, e comparáveis ou superiores aos do sul dos EUA escravista.</p>
<p><strong>Natureza do argumento:</strong> Descritivo-comparativo, com forte ênfase empírica e implicações para teorias institucionais de desenvolvimento (Engerman-Sokoloff), mas sem testar relações causais.</p>
<p><strong>O que o texto demonstra:</strong> (1) A estrutura fundiária do nordeste paulista era extremamente desigual, mesmo em uma economia de trabalho livre imigrante. (2) Há variação significativa entre municípios e sub-regiões, com Sertãozinho (Gini 0,911) e Ribeirão Preto (0,847) como os mais desiguais, e Franca (0,575) como o menos desigual — embora ainda com concentração alta em padrões internacionais. (3) A desigualdade se mantém quando se analisa terra cultivada (Gini 0,757) e pés de café (Gini 0,766), indicando que a elite fundiária controlava não apenas terra ociosa, mas os meios de produção efetivos. (4) Comparativamente, São Paulo era mais desigual do que as regiões cafeeiras de pequenos produtores na América Central e Colômbia, e tão ou mais desigual do que o sul dos EUA antes da Guerra Civil.</p>
<p><strong>O que fica como hipótese ou agenda:</strong> (1) A relação causal entre imigração em massa e desigualdade fundiária não é testada — os autores não demonstram que a imigração <em>reduziu</em> ou <em>ampliou</em> a concentração, apenas que a concentração persistiu. (2) O papel do estado (Lei de Terras de 1850, grilagem, política fiscal) na reprodução da desigualdade é mencionado mas não analisado. (3) A generalização para outras regiões cafeeiras brasileiras (sul de Minas, Espírito Santo, oeste paulista) permanece como agenda de pesquisa. (4) A evolução temporal da desigualdade (se estava aumentando ou diminuindo) não pode ser avaliada devido ao corte transversal.</p>
<p><strong>Contribuição para o debate:</strong> O artigo fornece a evidência empírica mais detalhada até o momento sobre a desigualdade fundiária na principal região cafeeira do mundo no início do século XX. Qualifica afirmações anteriores da historiografia (ex.: Franca como região de pequena propriedade) ao mostrar que, mesmo onde a desigualdade era menor, a concentração permanecia alta. Contribui para o debate Engerman-Sokoloff ao demonstrar que altos níveis de desigualdade fundiária podem ocorrer sem trabalho escravo, desafiando interpretações que associam diretamente escravidão à concentração. A base de dados em nível nominal (3.893 proprietários) permite futuras análises de mobilidade social, persistência intergeracional e conexões entre elite fundiária e política.</p>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:http:|https:)\/\/drganghe\.github\.io\/custom");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="http://www.github.com/mancano-tales">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
<p>Build on <a href="https://github.com/drganghe/quarto-academic-website-template">Quart Academic Website Template</a> adapted by <a href="http://drganghe.github.io">Dr.&nbsp;Gang He</a></p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/drganghe/quarto-academic-website-template" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank">
<p><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></p>
</a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="../../posts.xml" target="_blank">
      <i class="bi bi-rss" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>