<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tales Mançano">
<meta name="dcterms.date" content="2026-04-25">
<meta name="description" content="Tales Mançano Academic Website">

<title>Fichamento: Institutional Determinants of Railroad Subsidy and Regulation in Imperial Brazil – Tales Mançano</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-234273d1456647dabc34a594ac50e507.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-27ef39e98df4f05f4e0a48f4fb22c86d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/quarto-contrib/fontawesome6-1.2.0/all.min.css" rel="stylesheet">
<link href="../../site_libs/quarto-contrib/fontawesome6-1.2.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id="></script>

<script type="text/javascript">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', '', { 'anonymize_ip': true});
</script>


<!-- 

Load Academicons v1: https://jpswalsh.github.io/academicons/

-->

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">



<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">





<!---

The following code are needed to show dimension citation and altmetrics.

https://api.altmetric.com/embeds.html

https://badge.dimensions.ai/

--->



<script type="text/javascript" src="https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js"></script>



<script async="" src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>



<script type="text/javascript" src="//cdn.plu.mx/widget-popup.js"></script>


<link rel="stylesheet" href="../../styles.css">
<meta property="og:title" content="Fichamento: Institutional Determinants of Railroad Subsidy and Regulation in Imperial Brazil – Tales Mançano">
<meta property="og:description" content="Summerhill (2000)">
<meta property="og:site_name" content="Tales Mançano">
<meta name="twitter:title" content="Fichamento: Institutional Determinants of Railroad Subsidy and Regulation in Imperial Brazil – Tales Mançano">
<meta name="twitter:description" content="Summerhill (2000)">
<meta name="twitter:card" content="summary">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Tales Mançano</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-about" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">About</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-about">    
        <li>
    <a class="dropdown-item" href="../../posts.html">
 <span class="dropdown-text">Posts</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../contact.html">
 <span class="dropdown-text">Contact</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-research" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Research</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-research">    
        <li>
    <a class="dropdown-item" href="../../publications.html">
 <span class="dropdown-text">List of Publications</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../projects.html">
 <span class="dropdown-text">Grants</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-outreach" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Outreach</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-outreach">    
        <li>
    <a class="dropdown-item" href="../../posts.html">
 <span class="dropdown-text">Presentations</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../files/2026-1-02-CV-Mancano-Tales.pdf"> 
<span class="menu-text">CV</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/drganghe/quarto-academic-website-template" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank"> 
<span class="menu-text"><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../posts.xml" target="_blank"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introdução-pp.-14" id="toc-introdução-pp.-14" class="nav-link active" data-scroll-target="#introdução-pp.-14"><span class="header-section-number">1</span> Introdução (pp.&nbsp;1–4)</a>
  <ul class="collapse">
  <li><a href="#a-primazia-das-instituições-políticas-sobre-as-econômicas-12" id="toc-a-primazia-das-instituições-políticas-sobre-as-econômicas-12" class="nav-link" data-scroll-target="#a-primazia-das-instituições-políticas-sobre-as-econômicas-12"><span class="header-section-number">1.1</span> A primazia das instituições políticas sobre as econômicas [§1–§2]</a></li>
  <li><a href="#o-papel-distributivo-da-política-e-as-três-questões-centrais-34" id="toc-o-papel-distributivo-da-política-e-as-três-questões-centrais-34" class="nav-link" data-scroll-target="#o-papel-distributivo-da-política-e-as-três-questões-centrais-34"><span class="header-section-number">1.2</span> O papel distributivo da política e as três questões centrais [§3–§4]</a></li>
  <li><a href="#revisão-crítica-da-historiografia-e-reposicionamento-analítico-57" id="toc-revisão-crítica-da-historiografia-e-reposicionamento-analítico-57" class="nav-link" data-scroll-target="#revisão-crítica-da-historiografia-e-reposicionamento-analítico-57"><span class="header-section-number">1.3</span> Revisão crítica da historiografia e reposicionamento analítico [§5–§7]</a></li>
  </ul></li>
  <li><a href="#da-falha-de-mercado-ao-desenvolvimento-ferroviário-pp.-47" id="toc-da-falha-de-mercado-ao-desenvolvimento-ferroviário-pp.-47" class="nav-link" data-scroll-target="#da-falha-de-mercado-ao-desenvolvimento-ferroviário-pp.-47"><span class="header-section-number">2</span> Da Falha de Mercado ao Desenvolvimento Ferroviário (pp.&nbsp;4–7)</a>
  <ul class="collapse">
  <li><a href="#o-impacto-direto-das-ferrovias-e-os-cinco-obstáculos-ao-investimento-privado-89" id="toc-o-impacto-direto-das-ferrovias-e-os-cinco-obstáculos-ao-investimento-privado-89" class="nav-link" data-scroll-target="#o-impacto-direto-das-ferrovias-e-os-cinco-obstáculos-ao-investimento-privado-89"><span class="header-section-number">2.1</span> O impacto direto das ferrovias e os cinco obstáculos ao investimento privado [§8–§9]</a></li>
  <li><a href="#o-mecanismo-de-garantia-de-dividendos-e-o-crescimento-do-setor-1011" id="toc-o-mecanismo-de-garantia-de-dividendos-e-o-crescimento-do-setor-1011" class="nav-link" data-scroll-target="#o-mecanismo-de-garantia-de-dividendos-e-o-crescimento-do-setor-1011"><span class="header-section-number">2.2</span> O mecanismo de garantia de dividendos e o crescimento do setor [§10–§11]</a></li>
  <li><a href="#dados-de-crescimento-do-setor-ferroviário-18551887-1213" id="toc-dados-de-crescimento-do-setor-ferroviário-18551887-1213" class="nav-link" data-scroll-target="#dados-de-crescimento-do-setor-ferroviário-18551887-1213"><span class="header-section-number">2.3</span> Dados de crescimento do setor ferroviário, 1855–1887 [§12–§13]</a></li>
  </ul></li>
  <li><a href="#origens-institucionais-do-subsídio-ferroviário-pp.-613" id="toc-origens-institucionais-do-subsídio-ferroviário-pp.-613" class="nav-link" data-scroll-target="#origens-institucionais-do-subsídio-ferroviário-pp.-613"><span class="header-section-number">3</span> Origens Institucionais do Subsídio Ferroviário (pp.&nbsp;6–13)</a>
  <ul class="collapse">
  <li><a href="#crítica-à-literatura-anterior-e-o-papel-do-barril-de-carne-parlamentar-1415" id="toc-crítica-à-literatura-anterior-e-o-papel-do-barril-de-carne-parlamentar-1415" class="nav-link" data-scroll-target="#crítica-à-literatura-anterior-e-o-papel-do-barril-de-carne-parlamentar-1415"><span class="header-section-number">3.1</span> Crítica à literatura anterior e o papel do “barril de carne” parlamentar [§14–§15]</a></li>
  <li><a href="#o-modelo-formal-da-escolha-legislativa-de-subsídio-1618" id="toc-o-modelo-formal-da-escolha-legislativa-de-subsídio-1618" class="nav-link" data-scroll-target="#o-modelo-formal-da-escolha-legislativa-de-subsídio-1618"><span class="header-section-number">3.2</span> O modelo formal da escolha legislativa de subsídio [§16–§18]</a></li>
  <li><a href="#dinâmicas-de-coalizão-e-distribuição-provincial-de-subsídios-1921" id="toc-dinâmicas-de-coalizão-e-distribuição-provincial-de-subsídios-1921" class="nav-link" data-scroll-target="#dinâmicas-de-coalizão-e-distribuição-provincial-de-subsídios-1921"><span class="header-section-number">3.3</span> Dinâmicas de coalizão e distribuição provincial de subsídios [§19–§21]</a></li>
  <li><a href="#o-índice-de-shapley-shubik-e-a-correlação-com-subsídios-2223" id="toc-o-índice-de-shapley-shubik-e-a-correlação-com-subsídios-2223" class="nav-link" data-scroll-target="#o-índice-de-shapley-shubik-e-a-correlação-com-subsídios-2223"><span class="header-section-number">3.4</span> O índice de Shapley-Shubik e a correlação com subsídios [§22–§23]</a></li>
  </ul></li>
  <li><a href="#taxa-de-retorno-social-e-ineficiência-alocativa-pp.-1317" id="toc-taxa-de-retorno-social-e-ineficiência-alocativa-pp.-1317" class="nav-link" data-scroll-target="#taxa-de-retorno-social-e-ineficiência-alocativa-pp.-1317"><span class="header-section-number">4</span> Taxa de Retorno Social e Ineficiência Alocativa (pp.&nbsp;13–17)</a>
  <ul class="collapse">
  <li><a href="#o-conceito-de-taxa-de-retorno-social-médio-versus-marginal-2325" id="toc-o-conceito-de-taxa-de-retorno-social-médio-versus-marginal-2325" class="nav-link" data-scroll-target="#o-conceito-de-taxa-de-retorno-social-médio-versus-marginal-2325"><span class="header-section-number">4.1</span> O conceito de taxa de retorno social: médio versus marginal [§23–§25]</a></li>
  <li><a href="#desempenho-desagregado-por-ferrovia-e-o-custo-da-alocação-errônea-2627" id="toc-desempenho-desagregado-por-ferrovia-e-o-custo-da-alocação-errônea-2627" class="nav-link" data-scroll-target="#desempenho-desagregado-por-ferrovia-e-o-custo-da-alocação-errônea-2627"><span class="header-section-number">4.2</span> Desempenho desagregado por ferrovia e o custo da alocação errônea [§26–§27]</a></li>
  </ul></li>
  <li><a href="#a-economia-política-da-regulação-das-tarifas-de-frete-pp.-1720" id="toc-a-economia-política-da-regulação-das-tarifas-de-frete-pp.-1720" class="nav-link" data-scroll-target="#a-economia-política-da-regulação-das-tarifas-de-frete-pp.-1720"><span class="header-section-number">5</span> A Economia Política da Regulação das Tarifas de Frete (pp.&nbsp;17–20)</a>
  <ul class="collapse">
  <li><a href="#o-modelo-político-de-fixação-de-tarifas-2829" id="toc-o-modelo-político-de-fixação-de-tarifas-2829" class="nav-link" data-scroll-target="#o-modelo-político-de-fixação-de-tarifas-2829"><span class="header-section-number">5.1</span> O modelo político de fixação de tarifas [§28–§29]</a></li>
  <li><a href="#a-hipótese-de-propriedade-e-o-teste-econométrico-3032" id="toc-a-hipótese-de-propriedade-e-o-teste-econométrico-3032" class="nav-link" data-scroll-target="#a-hipótese-de-propriedade-e-o-teste-econométrico-3032"><span class="header-section-number">5.2</span> A hipótese de propriedade e o teste econométrico [§30–§32]</a></li>
  </ul></li>
  <li><a href="#estática-institucional-comparativa-e-conjecturas-contrafactuais-pp.-2022" id="toc-estática-institucional-comparativa-e-conjecturas-contrafactuais-pp.-2022" class="nav-link" data-scroll-target="#estática-institucional-comparativa-e-conjecturas-contrafactuais-pp.-2022"><span class="header-section-number">6</span> Estática Institucional Comparativa e Conjecturas Contrafactuais (pp.&nbsp;20–22)</a>
  <ul class="collapse">
  <li><a href="#centralismo-imperial-versus-federalismo-preservador-de-mercado-3234" id="toc-centralismo-imperial-versus-federalismo-preservador-de-mercado-3234" class="nav-link" data-scroll-target="#centralismo-imperial-versus-federalismo-preservador-de-mercado-3234"><span class="header-section-number">6.1</span> Centralismo imperial versus federalismo preservador de mercado [§32–§34]</a></li>
  <li><a href="#o-cenário-do-monarca-absoluto-e-a-lógica-da-dependência-3536" id="toc-o-cenário-do-monarca-absoluto-e-a-lógica-da-dependência-3536" class="nav-link" data-scroll-target="#o-cenário-do-monarca-absoluto-e-a-lógica-da-dependência-3536"><span class="header-section-number">6.2</span> O cenário do monarca absoluto e a lógica da dependência [§35–§36]</a></li>
  </ul></li>
  <li><a href="#conclusão-pp.-2122" id="toc-conclusão-pp.-2122" class="nav-link" data-scroll-target="#conclusão-pp.-2122"><span class="header-section-number">7</span> Conclusão (pp.&nbsp;21–22)</a>
  <ul class="collapse">
  <li><a href="#síntese-dos-achados-e-implicações-para-a-historiografia-3639" id="toc-síntese-dos-achados-e-implicações-para-a-historiografia-3639" class="nav-link" data-scroll-target="#síntese-dos-achados-e-implicações-para-a-historiografia-3639"><span class="header-section-number">7.1</span> Síntese dos achados e implicações para a historiografia [§36–§39]</a></li>
  </ul></li>
  <li><a href="#argumento-sintético" id="toc-argumento-sintético" class="nav-link" data-scroll-target="#argumento-sintético"><span class="header-section-number">8</span> Argumento Sintético</a></li>
  <li><a href="#ficha-analítica-crítica" id="toc-ficha-analítica-crítica" class="nav-link" data-scroll-target="#ficha-analítica-crítica">Ficha Analítica Crítica</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Fichamento: Institutional Determinants of Railroad Subsidy and Regulation in Imperial Brazil</h1>
<p class="subtitle lead">Summerhill (2000)</p>
  <div class="quarto-categories">
    <div class="quarto-category">Annotated Bibliography</div>
    <div class="quarto-category">Economia Política Comparada</div>
    <div class="quarto-category">Economia Histórica</div>
    <div class="quarto-category">Instituições Políticas</div>
    <div class="quarto-category">Brasil Imperial</div>
    <div class="quarto-category">Política de Infraestrutura</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tales Mançano </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 25, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>

<style>
.lang-toggle {
  position: fixed;
  top: 70px;
  right: 20px;
  z-index: 1000;
}
.lang-btn {
  background: transparent;
  border: 1px solid #666;
  border-radius: 4px;
  padding: 5px 12px;
  margin: 0 2px;
  cursor: pointer;
  font-size: 14px;
  transition: all 0.3s;
}
.lang-btn:hover {
  background: #f0f0f0;
}
.lang-btn.active {
  background: #0366d6;
  color: white;
  border-color: #0366d6;
}
.lang-content[lang]:not([lang="en"]) { display: none; }
.lang-content[lang="en"] { display: block; }
</style>
<p>Summerhill, W. R. (2000). Institutional determinants of railroad subsidy and regulation in Imperial Brazil. In S. Haber (Ed.), <em>Political institutions and economic growth in Latin America: Essays in policy, history, and political economy</em> (pp.&nbsp;1–29). Hoover Institution Press.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Entrada BibTeX → Summerhill2000
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="sourceCode" id="cb1"><pre class="sourceCode bibtex code-with-copy"><code class="sourceCode bibtex"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="va">@incollection</span>{<span class="ot">Summerhill2000</span>,</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="dt">author</span>    = {Summerhill, William R.},</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>  <span class="dt">title</span>     = {Institutional Determinants of Railroad Subsidy and Regulation in Imperial Brazil},</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  <span class="dt">booktitle</span> = {Political Institutions and Economic Growth in Latin America: Essays in Policy, History, and Political Economy},</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="dt">editor</span>    = {Haber, Stephen},</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>  <span class="dt">year</span>      = {2000},</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="dt">publisher</span> = {Hoover Institution Press},</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="dt">address</span>   = {Stanford, CA},</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="dt">pages</span>     = {1--29},</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
</div>
<p>Última atualização: 2026-04-25 Modelo: Perplexity — Claude Sonnet 4.6 Prompt Version: v13.0 2026-04-19 | 2026-04-24 “IA Blog Post QMD” Gerado em: 2026-04-25T18:07:00-03:00</p>
<hr>
<section id="introdução-pp.-14" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução-pp.-14"><span class="header-section-number">1</span> Introdução (pp.&nbsp;1–4)</h2>
<section id="a-primazia-das-instituições-políticas-sobre-as-econômicas-12" class="level3" data-number="1.1">
<h3 data-number="1.1" class="anchored" data-anchor-id="a-primazia-das-instituições-políticas-sobre-as-econômicas-12"><span class="header-section-number">1.1</span> A primazia das instituições políticas sobre as econômicas [§1–§2]</h3>
<p>O capítulo abre afirmando que a maior parte da literatura sobre instituições e desenvolvimento na América Latina concentrou-se nas <strong>instituições econômicas</strong> — regras, leis e práticas que moldam incentivos ao investimento e à produção. Summerhill argumenta, contudo, que tais instituições econômicas são frequentemente <em>resultados</em> de políticas e ações governamentais específicas, e não variáveis exógenas. Os arranjos institucionais dentro do sistema político — divisão de poderes, câmaras legislativas, sistemas eleitorais, organizações partidárias — moldam leis, regulações, a definição e a aplicação de direitos de propriedade, e qualquer forma recorrente de intervenção no mercado. Ao estruturar o que conta como instituição econômica, o sistema político torna-se diretamente relevante para o estudo do desempenho econômico: as instituições econômicas formais são, na metáfora do autor, apenas a “ponta do iceberg”, cuja base é a organização política e a formulação de políticas.</p>
<p>O segundo parágrafo aplica esse argumento geral ao caso do Brasil do século XIX. Tratava-se de uma economia relativamente atrasada, tardia na adoção de elementos como investimento em capital humano e social, direitos de propriedade modernos, legislação comercial para empresas de responsabilidade limitada e sistemas financeiros menos restritivos. A falha de mercado era disseminada. Summerhill, porém, insiste que a extensão da falha de mercado era apenas <em>um</em> dos determinantes do atraso relativo; o outro era o grau em que a organização política auxiliava — ou impedia — a correção dessas falhas. O ideal normativo de referência é o de políticas que maximizariam o excedente social em um ambiente sem outras distorções institucionais, seguindo o que o autor chama de potencial “gerschenkroniano” do Estado.</p>
</section>
<section id="o-papel-distributivo-da-política-e-as-três-questões-centrais-34" class="level3" data-number="1.2">
<h3 data-number="1.2" class="anchored" data-anchor-id="o-papel-distributivo-da-política-e-as-três-questões-centrais-34"><span class="header-section-number">1.2</span> O papel distributivo da política e as três questões centrais [§3–§4]</h3>
<p>No terceiro parágrafo, Summerhill introduz a tensão central do capítulo: porque políticos não compartilham necessariamente os critérios de eficiência da economia, as políticas por eles selecionadas podem divergir drasticamente do ótimo social. Políticos buscam conferir benefícios a seus constituintes e minimizar os custos que estes suportam; as <strong>consequências distributivas</strong> das intervenções no mercado são, assim, de importância primordial para qualquer análise de política pública. A correção de falhas de mercado pode, ela própria, ser dissipadora ou até agravar ineficiências — especialmente quando a falha não é suficientemente ampla e grave para que a intervenção melhore o <em>status quo</em>.</p>
<p>O quarto parágrafo apresenta o problema empírico concreto — o desenvolvimento ferroviário no Brasil imperial — e formula as três questões que o capítulo se propõe a responder: (1) por quais instituições e mecanismos o Estado imperial promoveu e regulou os investimentos ferroviários?; (2) como a organização política do Brasil determinou a seleção dessas políticas?; (3) quais foram as consequências da política ferroviária para a economia como um todo? As respostas a essas questões iluminam uma preocupação compartilhada por estudiosos da América Latina: as origens e o impacto da política governamental em economias relativamente atrasadas.</p>
</section>
<section id="revisão-crítica-da-historiografia-e-reposicionamento-analítico-57" class="level3" data-number="1.3">
<h3 data-number="1.3" class="anchored" data-anchor-id="revisão-crítica-da-historiografia-e-reposicionamento-analítico-57"><span class="header-section-number">1.3</span> Revisão crítica da historiografia e reposicionamento analítico [§5–§7]</h3>
<p>O quinto parágrafo apresenta e critica a interpretação dominante da história ferroviária brasileira, segundo a qual o padrão “plantation-e-mina-ao-porto” das ferrovias latino-americanas pouco contribuiu para a integração política ou mercados domésticos, tendo apenas aprofundado a dependência em relação aos mercados mundiais. Na visão convencional, as ferrovias foram eficientes em desperdiçar recursos, enriquecer uma pequena classe de proprietários rurais e empobrecer o país. Paralelamente, a visão sobre o financiamento externo sustentava que mesmo os países maiores e mais estáveis perderam o controle sobre suas próprias economias ao recorrer ao capital estrangeiro.</p>
<p>No sexto parágrafo, Summerhill observa que, apesar das implicações testáveis embutidas nessas formulações, há surpreendentemente poucas avaliações empíricas rigorosas das consequências econômicas das ferrovias de propriedade estrangeira, dos subsídios ferroviários ou da política regulatória no Brasil. Isso contrasta com a riqueza de análises dedutivas e impressões estilizadas. O sétimo parágrafo anuncia o reposicionamento analítico do capítulo: em vez de aceitar explicações puramente dedutivas, o trabalho avalia o processo de desenvolvimento ferroviário no Brasil imperial em termos de suas consequências observáveis, focando nos <strong>determinantes institucionais</strong> do subsídio e da regulação ferroviária. O capítulo prossegue em cinco seções, descritas em seguida.</p>
<hr>
</section>
</section>
<section id="da-falha-de-mercado-ao-desenvolvimento-ferroviário-pp.-47" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="da-falha-de-mercado-ao-desenvolvimento-ferroviário-pp.-47"><span class="header-section-number">2</span> Da Falha de Mercado ao Desenvolvimento Ferroviário (pp.&nbsp;4–7)</h2>
<section id="o-impacto-direto-das-ferrovias-e-os-cinco-obstáculos-ao-investimento-privado-89" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="o-impacto-direto-das-ferrovias-e-os-cinco-obstáculos-ao-investimento-privado-89"><span class="header-section-number">2.1</span> O impacto direto das ferrovias e os cinco obstáculos ao investimento privado [§8–§9]</h3>
<p>O oitavo parágrafo afirma que as ferrovias tiveram um forte impacto direto sobre a economia brasileira, apesar do início tardio. Durante o <strong>Segundo Reinado</strong> (1840–1889), as ferrovias representaram a maior parte do financiamento externo que fluía para o país e constituíam o maior setor “moderno” da economia. Entretanto, os mercados privados falharam em fornecer serviços de transporte ferroviário, não obstante os enormes retornos potenciais para produtores e consumidores resultantes da redução dos custos de transporte. O desenvolvimento ferroviário só ganhou impulso nos anos 1850, quando o governo criou a garantia de dividendo mínimo para investidores.</p>
<p>O nono parágrafo detalha os <strong>cinco fatores inter-relacionados</strong> que atrasaram a era ferroviária brasileira:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Obstáculo</th>
<th style="text-align: left;">Descrição</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Capital inicial elevado</td>
<td style="text-align: left;">Ferrovias eram, de longe, o investimento mais caro do Brasil do século XIX</td>
</tr>
<tr class="even">
<td style="text-align: left;">Incerteza sobre retornos</td>
<td style="text-align: left;">Investidores não sabiam quanto uma ferrovia geraria de receita; o retorno privado esperado ficava aquém do retorno social</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Risco de expropriação</td>
<td style="text-align: left;">A intensidade de capital e os custos fixos elevados expunham os proprietários de ferrovias à regulação confiscatória</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mercado de capitais subdesenvolvido</td>
<td style="text-align: left;">Difícil mobilizar investidores com preferências de risco e fundos adequados</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Instabilidade política</td>
<td style="text-align: left;">A Regência e os primeiros anos do Segundo Reinado desestimularam o risco; os recursos necessários para sufocar revoltas tornavam os subsídios governamentais inviáveis</td>
</tr>
</tbody>
</table>
</section>
<section id="o-mecanismo-de-garantia-de-dividendos-e-o-crescimento-do-setor-1011" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="o-mecanismo-de-garantia-de-dividendos-e-o-crescimento-do-setor-1011"><span class="header-section-number">2.2</span> O mecanismo de garantia de dividendos e o crescimento do setor [§10–§11]</h3>
<p>O décimo parágrafo descreve como somente com a primeira provisão de <strong>garantias de dividendo mínimo</strong> pelo governo imperial, em 1852, os investimentos vieram. Tanto o governo central quanto os governos provinciais passaram a satisfazer as demandas dos proprietários de terra por transporte barato, oferecendo dividendos mínimos garantidos a projetos ferroviários. As garantias iniciais eram específicas por projeto, mas legislação posterior nos anos 1870 e 1880 expandiu os compromissos do governo central, tornando-os acessíveis a todas as províncias. O mecanismo de garantia funcionava da seguinte forma: quando os lucros líquidos de uma ferrovia ficavam abaixo do nível estipulado, o governo pagava a diferença; quando os lucros excediam suficientemente o dividendo prescrito, os lucros adicionais eram divididos com o governo para reembolsar pagamentos anteriores; dividendos ainda mais elevados ocasionavam a redução das tarifas de frete e passageiros.</p>
<p>O décimo-primeiro parágrafo sintetiza os dois desfechos possíveis do mecanismo de garantia. Para ferrovias viáveis, somente o valor nominal dos pagamentos de dividendo garantido era reembolsado, sendo o valor do subsídio equivalente ao juro que a ferrovia não pagou. Para ferrovias que nunca geraram lucro suficiente, o valor do subsídio equivalia ao fluxo integral de garantias pagas pelo governo. Em ambos os casos, a contrapartida — o <em>quid pro quo</em> — era a regulação tarifária pelas autoridades governamentais. Com controles sobre tarifas de frete e passageiros, a política de dividendo mínimo criava uma <strong>banda de taxa de retorno</strong> para as ferrovias garantidas.</p>
</section>
<section id="dados-de-crescimento-do-setor-ferroviário-18551887-1213" class="level3" data-number="2.3">
<h3 data-number="2.3" class="anchored" data-anchor-id="dados-de-crescimento-do-setor-ferroviário-18551887-1213"><span class="header-section-number">2.3</span> Dados de crescimento do setor ferroviário, 1855–1887 [§12–§13]</h3>
<p>O décimo-segundo parágrafo apresenta a <strong>Tabela 1</strong>, que registra o crescimento do setor ferroviário brasileiro entre 1855 e 1887 por dois indicadores: quilômetros de trilho em operação e receitas operacionais totais (deflacionadas a preços de 1887). A primeira ferrovia brasileira abriu em 1854, mas o crescimento do setor foi lento até após a Guerra do Paraguai (1864–1870). A partir daí, tanto a capacidade quanto o tráfego cresceram especialmente após 1875. Em 1887, o Brasil possuía 8.400 quilômetros de trilhos em operação. Entre 1855 e 1887, o aumento médio anual da produção ferroviária foi de quase 15% ao ano.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 36%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Ano</th>
<th style="text-align: left;">Trilhos totais (km de rota)</th>
<th style="text-align: left;">Produção ferroviária (em milréis de 1887)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1855</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">200.155</td>
</tr>
<tr class="even">
<td style="text-align: left;">1860</td>
<td style="text-align: left;">223</td>
<td style="text-align: left;">2.078.514</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1865</td>
<td style="text-align: left;">498</td>
<td style="text-align: left;">3.611.287</td>
</tr>
<tr class="even">
<td style="text-align: left;">1870</td>
<td style="text-align: left;">744</td>
<td style="text-align: left;">6.571.833</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1875</td>
<td style="text-align: left;">1.801</td>
<td style="text-align: left;">14.306.998</td>
</tr>
<tr class="even">
<td style="text-align: left;">1880</td>
<td style="text-align: left;">3.398</td>
<td style="text-align: left;">26.744.889</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1885</td>
<td style="text-align: left;">6.930</td>
<td style="text-align: left;">34.966.580</td>
</tr>
<tr class="even">
<td style="text-align: left;">1887</td>
<td style="text-align: left;">8.400</td>
<td style="text-align: left;">37.368.187</td>
</tr>
</tbody>
</table>
<p><em>Fonte: Summerhill, “Benefits and Costs”. Deflacionado pelo índice de preços no atacado do Rio de Janeiro.</em></p>
<p>O décimo-terceiro parágrafo apresenta a magnitude das <strong>economias sociais</strong> geradas pela substituição de modos de transporte mais caros — carroças de tração animal, tropas de mulas e, em alguns casos, carregadores humanos — pelas ferrovias. Em 1887, as ferrovias brasileiras produziram 221,1 milhões de toneladas-quilômetro de serviço de frete, cobrando em média 0,123 milréis por tonelada-quilômetro — muito abaixo do custo pré-ferroviário de melhores práticas de cerca de 0,417 milréis (ajustado a preços de 1887). As economias sociais estimadas no frete foram de 64,9 milhões de milréis em 1887, equivalentes a 9,5% do PIB brasileiro. No período 1861–1887, o PIB quase dobrou (de 336,2 para 657,7 milhões de milréis em preços de 1887); o ganho de produtividade implícito, controlando pelo aumento populacional, foi de 130,4 milhões de milréis. A medida pelo limite superior das economias sociais corresponde a 50% desse avanço; medidas pelo limite inferior superam 25%. As ferrovias eram, sem dúvida, a força mais importante no aumento do produto per capita entre 1861 e 1887.</p>
<hr>
</section>
</section>
<section id="origens-institucionais-do-subsídio-ferroviário-pp.-613" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="origens-institucionais-do-subsídio-ferroviário-pp.-613"><span class="header-section-number">3</span> Origens Institucionais do Subsídio Ferroviário (pp.&nbsp;6–13)</h2>
<section id="crítica-à-literatura-anterior-e-o-papel-do-barril-de-carne-parlamentar-1415" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="crítica-à-literatura-anterior-e-o-papel-do-barril-de-carne-parlamentar-1415"><span class="header-section-number">3.1</span> Crítica à literatura anterior e o papel do “barril de carne” parlamentar [§14–§15]</h3>
<p>O décimo-quarto parágrafo aponta que estudos anteriores sobre ferrovias brasileiras enfatizaram o papel de restrições externas, classes agrárias e interesses locais, mas curiosamente nenhum examinou os determinantes do padrão de subsídio, e todos abstraíram o papel das instituições políticas. Ao adicionar apenas um modesto grau de detalhe institucional político, é possível revelar as forças que sustentam o padrão real de subsídio. Ao fornecer garantias de dividendos às ferrovias, o Parlamento imperial resolveu um problema que o mercado sozinho havia falhado em resolver.</p>
<p>O décimo-quinto parágrafo descreve brevemente a organização política brasileira: projetos de lei percorriam duas câmaras (Senado vitalício e Câmara de Deputados com mandatos de quatro anos), sendo então enviados ao imperador para sanção ou veto. As assembleias provinciais também legislavam, mas seus atos estavam sujeitos à revisão do parlamento nacional — inclusive os subsídios provinciais a ferrovias. Ao contrário de um arranjo federal como o dos Estados Unidos do século XIX, que colocava unidades subnacionais em competição por fatores de produção móveis, o <strong>centralismo brasileiro</strong> colocava as delegações provinciais em competição por <em>pork</em> e patronagem dentro do parlamento.</p>
</section>
<section id="o-modelo-formal-da-escolha-legislativa-de-subsídio-1618" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="o-modelo-formal-da-escolha-legislativa-de-subsídio-1618"><span class="header-section-number">3.2</span> O modelo formal da escolha legislativa de subsídio [§16–§18]</h3>
<p>O décimo-sexto parágrafo introduz os três fatores institucionais que influenciavam o impacto econômico da intervenção parlamentar no mercado: (1) a percepção dos legisladores sobre a incidência dos benefícios e custos da intervenção; (2) o uso da regra de maioria, que seleciona a preferência do legislador mediano; e (3) os incentivos para que legisladores do mesmo distrito cooperem em apoiar uma política de subsídio.</p>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Formalização da escolha do legislador:</strong> O legislador <em>i</em> busca a política <em>x</em> que maximiza seu suporte político:</p>
<p>[N_i(x) = B_{i1}(x) + C_{i1}(x) - C_{i2}(x) - t_i T(x)]</p>
<p>onde (B_{i1}(x)) são os benefícios criados pela política dentro do distrito eleitoral; (C_{i1}(x)) são os desembolsos diretos recebidos dentro do distrito; (C_{i2}(x)) são os custos indiretos incidentes sobre o distrito; e (t_i T(x)) é a parcela do ônus fiscal total que cabe ao distrito.</p>
<p>A política eficiente, por contraste, maximizaria:</p>
<p>[x^E = , E(x) = B(x) - C_1(x) - C_2(x)]</p>
<p>A política “politicamente eficiente”, ao agregar as funções de suporte de todos os distritos, resulta em:</p>
<p>[N(x) = B(x) - C_2(x)]</p>
<p>que difere da eficiente porque os desembolsos diretos — componente de custo econômico — são tratados pelos legisladores como benefícios políticos para seus constituintes. O subsídio politicamente escolhido tende, portanto, a ser <em>maior</em> que o socialmente eficiente.</p>
</div>
</div>
<p>O décimo-sétimo parágrafo complementa a análise com o segundo fator de distorção: a <strong>regra de maioria</strong>. Os arranjos institucionais na Câmara dos Deputados do Brasil garantiam a existência de um equilíbrio de política ao separar o espaço de alternativas em dimensões únicas de política, consideradas uma de cada vez. Assim, na dimensão do subsídio, a política vencedora é a preferida pelo legislador mediano. Para que o subsídio seja politicamente eficiente, seria necessário que o nível de subsídio correspondesse à média das preferências de todos os legisladores — condição de equilíbrio de fio de navalha que raramente se verificaria. Os dois fatores — partição geográfica e regra de maioria — geram a primeira hipótese: subsídios tendem a ser excessivos.</p>
</section>
<section id="dinâmicas-de-coalizão-e-distribuição-provincial-de-subsídios-1921" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="dinâmicas-de-coalizão-e-distribuição-provincial-de-subsídios-1921"><span class="header-section-number">3.3</span> Dinâmicas de coalizão e distribuição provincial de subsídios [§19–§21]</h3>
<p>O décimo-oitavo parágrafo apresenta três abordagens analíticas para o problema distributivo em uma legislatura de maioria. A primeira trata o problema como jogo de soma zero, prevendo o surgimento de uma <strong>coalizão mínima vencedora</strong> que distribui subsídios apenas a seus membros. A segunda abordagem, que não assume soma zero e introduz incerteza sobre a composição da coalizão, prevê uma <strong>coalizão universal</strong> que distribui subsídios a todos os distritos. A terceira, intermediária, explora a possibilidade de que os legisladores tenham incerteza apenas parcial sobre a composição da coalizão vencedora, o que levaria à formação de blocos provinciais coordenados.</p>
<p>O décimo-nono parágrafo elabora a lógica da terceira abordagem: um projeto ferroviário concentra benefícios diretos e externalidades em uma província, criando incentivos para que deputados dessa província votem juntos, independentemente de ideologia ou partido. Províncias com delegações maiores na Câmara tinham maior chance de que pelo menos um de seus deputados fosse pivô na coalizão vencedora, e, portanto, de que a ferrovia proposta recebesse subsídio. A hipótese intuitiva resultante é: <strong>províncias com delegações maiores na Câmara dos Deputados obtiveram mais subsídios ferroviários</strong>.</p>
<p>O vigésimo parágrafo operacionaliza a medição do subsídio. As duas componentes do subsídio ferroviário eram: (1) dividendos garantidos e (2) desembolsos diretos do governo para ferrovias que ele assumiu ou construiu. O valor do compromisso do governo central com ferrovias em cada província <em>i</em> é dado por:</p>
<p>[G_i = OC_i + rK_{1i} + K_{2i}]</p>
<p>onde (OC_i) é a soma das perdas operacionais das ferrovias governamentais na província <em>i</em>; (rK_{1i}) é o valor do “subsídio” de capital direto sobre todas as ferrovias governamentais na província <em>i</em>; e (K_{2i}) é o valor da garantia de dividendo sobre as ferrovias garantidas na província <em>i</em>. O capital subsídio é tomado como 6% do custo de construção das ferrovias governamentais em operação em 1888.</p>
</section>
<section id="o-índice-de-shapley-shubik-e-a-correlação-com-subsídios-2223" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="o-índice-de-shapley-shubik-e-a-correlação-com-subsídios-2223"><span class="header-section-number">3.4</span> O índice de Shapley-Shubik e a correlação com subsídios [§22–§23]</h3>
<p>O vigésimo-primeiro parágrafo descreve a mensuração do <strong>poder de votação</strong> de cada província por meio da teoria dos jogos cooperativos — especificamente o <strong>índice de Shapley-Shubik</strong>, que expressa com que frequência, em média, uma determinada província pode esperar que um de seus deputados seja pivô em uma coalizão vencedora. Tal medida, baseada exclusivamente na estrutura da representação, prediz como projetos geradores de renda como os subsídios ferroviários serão distribuídos entre as províncias brasileiras. A <strong>Tabela 2</strong> apresenta os compromissos de subsídio e os índices de Shapley-Shubik por província.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 10%">
<col style="width: 41%">
<col style="width: 20%">
<col style="width: 27%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Província</th>
<th style="text-align: center;">Compromisso de Subsídio, 1888 (em milréis)</th>
<th style="text-align: center;">Índice S-S até 1881</th>
<th style="text-align: center;">Índice S-S a partir de 1884</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Rio de Janeiro</td>
<td style="text-align: center;">4.472.898</td>
<td style="text-align: center;">0,0993</td>
<td style="text-align: center;">0,0970</td>
</tr>
<tr class="even">
<td style="text-align: left;">Minas Gerais</td>
<td style="text-align: center;">4.159.397</td>
<td style="text-align: center;">0,1808</td>
<td style="text-align: center;">0,1761</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Bahia</td>
<td style="text-align: center;">3.723.732</td>
<td style="text-align: center;">0,1181</td>
<td style="text-align: center;">0,1153</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pernambuco</td>
<td style="text-align: center;">3.667.260</td>
<td style="text-align: center;">0,1086</td>
<td style="text-align: center;">0,1060</td>
</tr>
<tr class="odd">
<td style="text-align: left;">São Paulo</td>
<td style="text-align: center;">2.815.439</td>
<td style="text-align: center;">0,0726</td>
<td style="text-align: center;">0,0709</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rio Grande do Sul</td>
<td style="text-align: center;">1.501.365</td>
<td style="text-align: center;">0,0472</td>
<td style="text-align: center;">0,0462</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ceará</td>
<td style="text-align: center;">930.393</td>
<td style="text-align: center;">0,0640</td>
<td style="text-align: center;">0,0626</td>
</tr>
<tr class="even">
<td style="text-align: left;">Alagoas</td>
<td style="text-align: center;">826.686</td>
<td style="text-align: center;">0,0390</td>
<td style="text-align: center;">0,0381</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Paraná</td>
<td style="text-align: center;">804.443</td>
<td style="text-align: center;">0,0153</td>
<td style="text-align: center;">0,0149</td>
</tr>
<tr class="even">
<td style="text-align: left;">Santa Catarina</td>
<td style="text-align: center;">392.651</td>
<td style="text-align: center;">0,0153</td>
<td style="text-align: center;">0,0149</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rio Grande do Norte</td>
<td style="text-align: center;">384.514</td>
<td style="text-align: center;">0,0153</td>
<td style="text-align: center;">0,0149</td>
</tr>
<tr class="even">
<td style="text-align: left;">Paraíba</td>
<td style="text-align: center;">302.188</td>
<td style="text-align: center;">0,0390</td>
<td style="text-align: center;">0,0381</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Maranhão</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0,0472</td>
<td style="text-align: center;">0,0462</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sergipe</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0,0310</td>
<td style="text-align: center;">0,0303</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pará</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0,0231</td>
<td style="text-align: center;">0,0462</td>
</tr>
<tr class="even">
<td style="text-align: left;">Piauí</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0,0231</td>
<td style="text-align: center;">0,0226</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Amazonas</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0,0153</td>
<td style="text-align: center;">0,0149</td>
</tr>
<tr class="even">
<td style="text-align: left;">Espírito Santo</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0,0153</td>
<td style="text-align: center;">0,0149</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Goiás</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0,0153</td>
<td style="text-align: center;">0,0149</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mato Grosso</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0,0153</td>
<td style="text-align: center;">0,0149</td>
</tr>
</tbody>
</table>
<p>O coeficiente de correlação entre poder de votação e subsídios recebidos é de <strong>0,89</strong>, indicando que a variação no poder de votação está associada a 89% da variação na quantidade de subsídios ferroviários recebidos pelas províncias.</p>
<p>O vigésimo-segundo parágrafo discute os desvios da tabela em relação aos resultados previstos. O Rio Grande do Sul, por exemplo, recebeu uma parcela desproporcionalmente grande de subsídios por razões estratégico-militares (mobilização de tropas para o extremo sul, diante do risco de conflito no Rio da Prata). Algumas províncias do norte receberam subsídios como parte de programas de alívio à seca. Contudo, o ponto fundamental permanece claro: o <strong>poder de votação foi um determinante central</strong> da capacidade de uma província em capturar subsídios ferroviários.</p>
<hr>
</section>
</section>
<section id="taxa-de-retorno-social-e-ineficiência-alocativa-pp.-1317" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="taxa-de-retorno-social-e-ineficiência-alocativa-pp.-1317"><span class="header-section-number">4</span> Taxa de Retorno Social e Ineficiência Alocativa (pp.&nbsp;13–17)</h2>
<section id="o-conceito-de-taxa-de-retorno-social-médio-versus-marginal-2325" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="o-conceito-de-taxa-de-retorno-social-médio-versus-marginal-2325"><span class="header-section-number">4.1</span> O conceito de taxa de retorno social: médio versus marginal [§23–§25]</h3>
<p>O vigésimo-terceiro parágrafo apresenta dois conceitos distintos de taxa de retorno social. O primeiro — a <strong>taxa de retorno social média</strong> — examina se o retorno sobre os investimentos em ferrovias justificou os recursos a eles destinados. O segundo — a <strong>taxa de retorno social marginal</strong> — responde se o Brasil investiu demais ou de menos em suas ferrovias. O critério de eficiência ideal seria que o governo subsidiasse projetos até o ponto em que o retorno sobre uma unidade adicional de capital investido igualasse os retornos de outras atividades na economia. Se o retorno ferroviário fosse inferior, o governo havia subsidiado em excesso; se fosse superior, o nível de subsídio era insuficiente.</p>
<p>O vigésimo-quarto parágrafo apresenta os resultados da <strong>Tabela 3</strong>, que deriva a taxa de retorno social média sobre o capital ferroviário em 1887. Em 1887, as ferrovias brasileiras apresentavam uma taxa de retorno privado não subsidiado de pouco menos de 3%. Para investidores em linhas garantidas, a taxa efetiva recebida (incluindo subsídios e receitas operacionais líquidas) foi de 4,75%. O retorno de baixo risco na época era o dos títulos de dívida pública, em pouco mais de 4%. Somando as economias sociais no frete (limite inferior) às receitas de capital não subsidiadas, obtém-se uma <strong>taxa de retorno social de 9,4%</strong>. Convertendo-a à marginal mediante multiplicação pelo quociente dos lucros de capital na receita total subsidiada (elasticidade do capital de 0,52), chega-se a uma <strong>taxa de retorno marginal de 4,9% em 1887</strong>. Em agregado, o Brasil não havia superinvestido em ferrovias — poderia até ter ligeiramente subinvestido no final do Império.</p>
</section>
<section id="desempenho-desagregado-por-ferrovia-e-o-custo-da-alocação-errônea-2627" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="desempenho-desagregado-por-ferrovia-e-o-custo-da-alocação-errônea-2627"><span class="header-section-number">4.2</span> Desempenho desagregado por ferrovia e o custo da alocação errônea [§26–§27]</h3>
<p>O vigésimo-quinto parágrafo observa que a medida agregada obscurece que projetos individuais podem ter sido sistematicamente super ou subsidiados. A <strong>Tabela 3</strong> apresenta as taxas de retorno social marginais por ferrovia em 1887. Embora várias ferrovias apresentassem retornos positivos fortes, três quartos delas não o faziam. As linhas com retorno abaixo do corte de 4,5% (equivalente ao retorno sobre títulos públicos) geradas combinadas para o Brasil uma taxa marginal de apenas 2,2%. Essas linhas representavam mais da metade do capital total do setor ferroviário em 1887. O grupo com alto retorno apresentava taxa marginal de 7,5%, indicando que havia espaço para subsídio adicional.</p>
<p>O vigésimo-sexto parágrafo quantifica o custo dessa alocação errônea por meio de um exercício hipotético (Tabela 4). Realocar o capital das linhas de baixo retorno para as de alto retorno aumentaria o excedente das ferrovias em pelo menos 23,2 milhões de milréis. Isso corresponderia a um aumento de 36% nas economias sociais diretas estimadas pelo limite superior em 1887, ou mais de 3% do PIB. A razão para a concentração errônea de capital ferroviário não era erro de previsão ingênuo, mas antes <strong>previsão política</strong> — o governo promovia investimentos em ferrovias não em conformidade com alguma estratégia abstrata de desenvolvimento, mas em resposta a imperativos políticos internos.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 61%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Indicador</th>
<th style="text-align: left;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Taxa de retorno social marginal (linhas de alto retorno)</td>
<td style="text-align: left;">7,5%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Taxa de retorno social marginal (linhas de baixo retorno)</td>
<td style="text-align: left;">–2,2%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Diferença</td>
<td style="text-align: left;">9,7 p.p.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Capital físico reprodutível das linhas de baixo retorno</td>
<td style="text-align: left;">239,3 milhões de milréis</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aumento hipotético nas economias sociais</td>
<td style="text-align: left;">23,2 milhões de milréis</td>
</tr>
<tr class="even">
<td style="text-align: left;">Economias sociais diretas (limite superior)</td>
<td style="text-align: left;">64,9 milhões de milréis</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Aumento nas economias sociais</td>
<td style="text-align: left;">36%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Aumento no PIB</td>
<td style="text-align: left;">3,4%</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="a-economia-política-da-regulação-das-tarifas-de-frete-pp.-1720" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="a-economia-política-da-regulação-das-tarifas-de-frete-pp.-1720"><span class="header-section-number">5</span> A Economia Política da Regulação das Tarifas de Frete (pp.&nbsp;17–20)</h2>
<section id="o-modelo-político-de-fixação-de-tarifas-2829" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="o-modelo-político-de-fixação-de-tarifas-2829"><span class="header-section-number">5.1</span> O modelo político de fixação de tarifas [§28–§29]</h3>
<p>O vigésimo-sétimo parágrafo estabelece que, dado que a contrapartida das garantias de dividendo era a regulação tarifária, é necessário examinar como as tarifas de frete eram fixadas no Brasil. O custo elevado do transporte pré-ferroviário e a possibilidade de precificação monopolista tornavam a regulação tarifária potencialmente benéfica. Analogamente à análise dos subsídios, o argumento é que os políticos fixavam tarifas não no interesse da eficiência, mas para angariar e manter apoio político, considerando a incidência dos componentes de custos e benefícios em seus respectivos distritos.</p>
<p>O vigésimo-oitavo parágrafo formaliza o modelo de regulação. O suporte político do legislador <em>i</em> ao escolher a política regulatória <em>x</em> é:</p>
<p>[N_i(x) = B_{i1}(x) - C_{i2}(x)]</p>
<p>onde (B_{i1}(x)) são os benefícios criados pela regulação dentro do distrito (tarifas menores para remetentes locais) e (C_{i2}(x)) são os custos indiretos ao distrito (lucros reduzidos dos acionistas ferroviários locais). O insight central é que os custos políticos indiretos da regulação variavam com a <strong>propriedade da ferrovia</strong>: para uma ferrovia com proprietários predominantemente brasileiros, a regulação tarifária reduzia lucros de acionistas que constituíam parte do eleitorado do legislador, gerando resistência à regulação estrita. Para ferrovias de propriedade predominantemente britânica ou estatal, esses custos eram nulos — nenhuma força contrária à regulação rígida existia.</p>
</section>
<section id="a-hipótese-de-propriedade-e-o-teste-econométrico-3032" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="a-hipótese-de-propriedade-e-o-teste-econométrico-3032"><span class="header-section-number">5.2</span> A hipótese de propriedade e o teste econométrico [§30–§32]</h3>
<p>O vigésimo-nono parágrafo explicita a hipótese: ferrovias de propriedade estrangeira ou do Estado seriam sobrecarregadas com regulação tarifária mais estrita do que as ferrovias de propriedade brasileira. Isso porque poucos constituintes de deputados brasileiros recebiam rendas na forma de lucros de ferrovias britânicas (que iam predominantemente para acionistas em Londres) ou governamentais (que iam para o Tesouro). Os acionistas brasileiros constituíam uma importante circunscrição política e tinham algum sucesso em resistir à pressão baixista sobre tarifas; os britânicos eram menos eficazes por ter menos representação direta no sistema político.</p>
<p>O trigésimo parágrafo especifica e estima o modelo econométrico:</p>
<p>[ = + _1 + _2 + _3 + _4 ]</p>
<p>onde RATE é a tarifa por tonelada-quilômetro de serviço de frete; EXPORT e IMPORT são <em>dummies</em> para produtos de alto valor por unidade; GOV é <em>dummy</em> para ferrovia governamental; e BRITISH é <em>dummy</em> para propriedade predominantemente britânica. Os resultados (Tabela 5) para 22 ferrovias nos anos 1880 confirmam a hipótese. Ferrovias privadas brasileiras desfrutavam de tarifas mais altas. As ferrovias britânicas cobravam tarifas significativamente menores que a média (coeficiente: –0,165; t = –5,5). O maior desvio da média é encontrado nas ferrovias governamentais (coeficiente: –0,24; t = –7), onde inexistiam acionistas a exigir taxa mínima de retorno.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Variável Independente</th>
<th style="text-align: left;">Coeficiente</th>
<th style="text-align: left;">Estatística t</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Constante</td>
<td style="text-align: left;">0,305</td>
<td style="text-align: left;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mercadoria de exportação</td>
<td style="text-align: left;">0,097</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mercadoria de importação</td>
<td style="text-align: left;">0,211</td>
<td style="text-align: left;">6,5</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ferrovia governamental</td>
<td style="text-align: left;">–0,24</td>
<td style="text-align: left;">–7</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ferrovia britânica</td>
<td style="text-align: left;">–0,165</td>
<td style="text-align: left;">–5,5</td>
</tr>
<tr class="even">
<td style="text-align: left;">R²</td>
<td style="text-align: left;">0,62</td>
<td style="text-align: left;">—</td>
</tr>
<tr class="odd">
<td style="text-align: left;">R² ajustado</td>
<td style="text-align: left;">0,60</td>
<td style="text-align: left;">—</td>
</tr>
<tr class="even">
<td style="text-align: left;">N</td>
<td style="text-align: left;">66</td>
<td style="text-align: left;">—</td>
</tr>
</tbody>
</table>
<p>O trigésimo-primeiro parágrafo sublinha que, ao contrário dos Estados Unidos — onde a regulação generalizada das ferrovias aguardou a criação da Interstate Commerce Commission —, no Brasil o governo regulava ferrovias desde o início. As tarifas eram em geral fixadas dentro do Ministério da Agricultura, em conformidade com as preferências do parlamento, que operava sob responsabilidade ministerial. Isso permitia ao parlamento evitar legislar todas as tarifas diretamente e ainda assim obter o resultado desejado para seus constituintes.</p>
<hr>
</section>
</section>
<section id="estática-institucional-comparativa-e-conjecturas-contrafactuais-pp.-2022" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="estática-institucional-comparativa-e-conjecturas-contrafactuais-pp.-2022"><span class="header-section-number">6</span> Estática Institucional Comparativa e Conjecturas Contrafactuais (pp.&nbsp;20–22)</h2>
<section id="centralismo-imperial-versus-federalismo-preservador-de-mercado-3234" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="centralismo-imperial-versus-federalismo-preservador-de-mercado-3234"><span class="header-section-number">6.1</span> Centralismo imperial versus federalismo preservador de mercado [§32–§34]</h3>
<p>O trigésimo-segundo parágrafo observa que a comparação com o critério de eficiência de “primeiro ótimo” é um instrumento analítico útil, mas de relevância histórica limitada. A relevância histórica deriva de arranjos institucionais alternativos historicamente plausíveis, não apenas do ideal teórico. Diferentes arranjos poderiam ficar aquém da plena eficiência e ainda assim melhorar o centralismo do Brasil imperial.</p>
<p>O trigésimo-terceiro parágrafo considera o primeiro cenário contrafactual: o que teria ocorrido se o Brasil fosse organizado com base no <strong>federalismo</strong> em vez do centralismo. Embora a monarquia tenha sido seguida por uma república federal, o “federalismo” brasileiro era peculiar, carecendo de elementos do federalismo preservador de mercado. A comparação relevante é com os Estados Unidos, que diferiam do Brasil em dois aspectos: o governo central protegia um mercado comum; e os governos subnacionais interviam nos mercados para subsidiar e regular atividades econômicas locais. Sob federalismo, as ferrovias provinciais seriam subsidiadas e reguladas de acordo com a política provincial, não nacional. Governos provinciais teriam mais incentivos a subsidiar projetos locais em níveis próximos ao da eficiência econômica — pois oversubsidiar criaria ônus fiscal que reduziria a atratividade da província para capital e trabalho, enquanto subsidiar menos do que outras províncias limitaria as oportunidades de novas atividades econômicas.</p>
</section>
<section id="o-cenário-do-monarca-absoluto-e-a-lógica-da-dependência-3536" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="o-cenário-do-monarca-absoluto-e-a-lógica-da-dependência-3536"><span class="header-section-number">6.2</span> O cenário do monarca absoluto e a lógica da dependência [§35–§36]</h3>
<p>O trigésimo-quarto parágrafo apresenta o segundo cenário contrafactual: o que teria ocorrido se o Brasil possuísse um monarca absoluto, como o teve durante a era colonial e em 1808–1822? Nesse caso, as distorções alocativas impostas pelas instituições do governo parlamentar representativo desapareceriam, pois a lógica política é muito diferente. O soberano, em vez de delegar autoridade sobre políticas públicas a representantes eleitos, barganharia diretamente com produtores sobre alíquotas de imposto e política. Trocar controle de política por receitas tem uma implicação clara: o capital — por sua maior mobilidade — ganha controle desproporcional sobre a política. Em um cenário em que o soberano buscasse promover o desenvolvimento ferroviário, os capitalistas (incluindo estrangeiros), e não os proprietários de terra representados em um parlamento, comandariam os termos do subsídio e da regulação — resultado notavelmente similar ao previsto pela análise dependentista.</p>
<p>O trigésimo-quinto parágrafo conclui o exercício contrafactual: a organização política da monarquia brasileira evitou esse resultado dependentista específico porque as instituições representativas adaptavam políticas responsivas aos proprietários de terra e investidores ferroviários brasileiros, não a capitalistas estrangeiros. Ficou muito aquém da plena eficiência porque a centralização exacerbou as pressões inerentes à política distributiva. Como nenhum dos arranjos alternativos — federalismo preservador de mercado ou monarquia absolutista — prevaleceu no primeiro estágio do desenvolvimento ferroviário brasileiro, nenhum teste rigoroso de seus impactos é possível em termos historicamente aceitáveis, e as proposições contrafactuais permanecem necessariamente conjeturais.</p>
<hr>
</section>
</section>
<section id="conclusão-pp.-2122" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="conclusão-pp.-2122"><span class="header-section-number">7</span> Conclusão (pp.&nbsp;21–22)</h2>
<section id="síntese-dos-achados-e-implicações-para-a-historiografia-3639" class="level3" data-number="7.1">
<h3 data-number="7.1" class="anchored" data-anchor-id="síntese-dos-achados-e-implicações-para-a-historiografia-3639"><span class="header-section-number">7.1</span> Síntese dos achados e implicações para a historiografia [§36–§39]</h3>
<p>O trigésimo-sexto parágrafo sintetiza: as ferrovias criaram grandes ganhos para a economia brasileira, mas esses ganhos foram muito menores do que poderiam ter sido, uma vez que muitas linhas individuais produziram resultados medíocres. Isso não resultou de investimento estrangeiro, exploração, dependência, exportação de mais-valia ou conspirações de estrangeiros para minar o serviço eficiente. Resultou diretamente da forma como a organização política do Brasil canalizou subsídios ao investimento.</p>
<p>O trigésimo-sétimo parágrafo reforça que o sistema político não era endógeno à estrutura do mercado internacional nem curvando-se às demandas de investidores estrangeiros; muitas de suas características eram comuns a polities representativas estáveis e bem-sucedidas da época. A diferença-chave era o caráter altamente centralizado das instituições políticas com poder de intervenção no mercado.</p>
<p>O trigésimo-oitavo parágrafo oferece a avaliação normativa final: como a falha do mercado em fornecer ferrovias era pervasiva e disseminada no Brasil, a intervenção estatal melhorou consideravelmente o <em>status quo</em>. Mesmo assim, os resultados ficaram aquém da maximização dos ganhos potenciais dos projetos ferroviários. O Estado não perseguiu uma estratégia de desenvolvimento de forma coerente, nem agiu como simples agente da elite coletiva. Em vez disso, os arranjos institucionais estruturaram a política distributiva de modo a tornar o subsídio e a regulação ferroviária politicamente atraentes.</p>
<p>O trigésimo-nono parágrafo encerra o capítulo afirmando que a importância do sistema político na alocação de subsídios deriva das oportunidades de intervenção criadas por falhas de mercado. Mas, diferentemente da economia — onde os preços transmitem escassez —, no sistema político não há mercados políticos nem preços relativos que alocem recursos. As <strong>instituições políticas e os detalhes procedimentais transformam preferências em resultados</strong>. Embora governo representativo, regra de maioria e incentivos distributivos tenham contribuído para a lacuna entre o equilíbrio de política do Brasil e a eficiência econômica, a centralização política exacerbou os custos dessa lacuna — custos particularmente agudos em uma economia com baixos níveis gerais de produtividade e renda.</p>
<hr>
</section>
</section>
<section id="argumento-sintético" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="argumento-sintético"><span class="header-section-number">8</span> Argumento Sintético</h2>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>Tese central:</strong> A ineficiência alocativa do sistema de subsídios e regulação ferroviária no Brasil imperial resultou não do investimento estrangeiro, da dependência ou dos interesses da classe dos plantadores, mas da forma como as instituições políticas centralizadas do Brasil estruturaram a política distributiva — levando a um nível de subsídio excessivo e a uma distribuição de capital ferroviário determinada pelo poder de votação das províncias, não pelo retorno econômico das linhas.</p>
<p><strong>Natureza do argumento:</strong> Causal-institucional, com formalização em teoria da escolha pública (modelo do legislador, Shapley-Shubik, regressão de tarifas) e estimação econométrica de retornos sociais. O argumento integra análise de custo-benefício histórico com teoria da economia política positiva.</p>
<p><strong>O que o texto demonstra:</strong> (1) Que o subsídio ferroviário foi excessivo e distribuído proporcionalmente ao poder de votação provincial (correlação de 0,89); (2) que ferrovias de propriedade estrangeira ou estatal foram mais reguladas do que as de propriedade brasileira, em linha com o modelo de suporte político; (3) que as economias sociais do setor ferroviário foram reais e substanciais (9,5% do PIB em 1887), mas poderiam ter sido 36% maiores com alocação eficiente.</p>
<p><strong>O que permanece como hipótese ou agenda:</strong> Os cenários contrafactuais (federalismo e monarquia absoluta) são explicitamente conjeturais; a extensão dos mecanismos de <em>log-rolling</em> e barganha de gabinete requer investigação adicional; o peso relativo do “poder moderador” do imperador na agenda legislativa é indicado mas não estimado.</p>
<p><strong>Contribuição para o debate:</strong> O capítulo oferece uma refutação empírica e teórica rigorosa das interpretações dependentistas e de exploração estrangeira para o caso ferroviário brasileiro, ao mesmo tempo em que proporciona uma aplicação pioneira da teoria dos jogos cooperativos e da economia política positiva à história econômica latino-americana. Posiciona-se no campo da <strong>nova economia institucional</strong> e da análise de escolha pública aplicada à história.</p>
</div>
</div>
<hr>
</section>
<section id="ficha-analítica-crítica" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="ficha-analítica-crítica">Ficha Analítica Crítica</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Esta seção segue o formato <em>IA Planilhando Textos v13.0</em>.</p>
</div>
</div>
<div class="callout callout-style-default callout-note no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Ficha Analítica — Tabela Markdown
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<table class="caption-top table">
<colgroup>
<col style="width: 23%">
<col style="width: 52%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Dimensão</th>
<th style="text-align: left;">Raciocínio analítico</th>
<th style="text-align: left;">Conteúdo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Questão de Pesquisa</td>
<td style="text-align: left;">A pergunta é explícita e tripartida; a premissa central é que instituições políticas moldam instituições econômicas — relação causal que precisa ser demonstrada, não apenas afirmada. A interpretação alternativa — que a estrutura de incentivos dos investidores estrangeiros ou a posição na economia mundial explica os resultados — é o alvo explícito de refutação. O ponto mais vulnerável é que a pergunta pressupõe separabilidade entre instituições políticas e econômicas que o próprio texto problematiza no início.</td>
<td style="text-align: left;">Por quais instituições o Estado imperial promoveu e regulou ferrovias? Como a organização política brasileira determinou a seleção dessas políticas? Quais foram as consequências para a economia? Natureza: explicativa/avaliativa.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Questões Secundárias</td>
<td style="text-align: left;">A análise de regulação é uma extensão natural da análise de subsídio, compartilhando o mesmo arcabouço teórico; a comparação contrafactual é metodologicamente separada e serve como exercício de validade externa do argumento.</td>
<td style="text-align: left;">(1) Como o padrão de tarifas de frete foi determinado politicamente? (2) Como arranjos institucionais alternativos (federalismo, monarquia absoluta) teriam alterado os resultados? Relação direta com a pergunta central: ambas são desdobramentos do mecanismo principal.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Puzzle-Type</td>
<td style="text-align: left;">O puzzle é genuíno: a literatura dependentista dominante continha implicações testáveis que nunca haviam sido sistematicamente avaliadas. A generalização é parcialmente limitada ao centralismo como variação institucional específica, mas o mecanismo de política distributiva é generalizável a outros contextos de escolha pública parlamentar.</td>
<td style="text-align: left;">Puzzle explicativo: por que o desenvolvimento ferroviário no Brasil imperial gerou retornos substancialmente inferiores ao potencial tecnológico? O texto refuta a explicação padrão (dependência/capital estrangeiro) e substitui por uma explicação institucional-política.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conclusão / Argumento Central</td>
<td style="text-align: left;">O <em>claim of discovery</em> é bem sustentado pela correlação de 0,89 entre poder de votação e subsídios, pela regressão de tarifas (R²=0,62) e pelo exercício de retorno social. A evidência causal é mais sugestiva que identificada rigorosamente — a correlação pode refletir variáveis omitidas como tamanho econômico provincial.</td>
<td style="text-align: left;">Tese: os custos de eficiência do sistema ferroviário brasileiro não derivaram do capital estrangeiro ou da dependência, mas da forma como o centralismo político estruturou a política distributiva, alocando subsídios por poder de votação, não por retorno econômico. Argumento causal-institucional com base empírica mista (correlação + regressão + análise de custo-benefício).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Métodos</td>
<td style="text-align: left;">A mistura de teoria dos jogos cooperativos, análise de custo-benefício histórico e regressão OLS é inovadora para a época (ca. 2000), mas cada técnica tem limitações próprias de identificação. O Shapley-Shubik captura poder estrutural, não preferências ou barganha efetiva. A regressão de tarifas não controla por características das linhas (extensão, topografia, tráfego) que poderiam explicar a variação tarifária independentemente da propriedade.</td>
<td style="text-align: left;">Estudo histórico-quantitativo; fontes primárias (relatórios ministeriais, legislação imperial, relatórios de companhias); técnicas: índice de Shapley-Shubik, OLS cross-sectional (22 ferrovias), análise de custo-benefício com medida de economias sociais do frete.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Data Generation Process (DGP)</td>
<td style="text-align: left;">A unidade de análise muda entre seções (província para subsídio, ferrovia para tarifas e retornos), o que implica diferentes DGPs sem sistematização explícita. As fontes são primárias e bem documentadas, mas a agregação das garantias de dividendo como proxy de subsídio pode subestimar valores de linhas não garantidas.</td>
<td style="text-align: left;">Fenômeno: alocação de subsídios ferroviários e fixação de tarifas → observação: relatórios ministeriais e legislação imperial → coleta: base de dados de garantias e tarifas por ferrovia/província → operacionalização: Gi para subsídios, RATE para tarifas → análise: correlação + regressão + custo-benefício → inferência: causal-institucional qualificada. Unidade de análise: província (subsídios) e ferrovia (tarifas, retornos).</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Achados e Contribuições</td>
<td style="text-align: left;">A correlação de 0,89 é forte, mas não separada de variáveis de confusão como tamanho econômico ou extensão territorial. A regressão de tarifas tem um R² de 0,62, mas com apenas 22 observações e sem controles de demanda ou custo. A análise de retorno social é o elemento mais sofisticado e contribui para a literatura de social savings.</td>
<td style="text-align: left;">(1) Correlação de 0,89 entre poder de votação provincial e subsídios ferroviários; (2) ferrovias britânicas e governamentais cobram tarifas ~0,17 e ~0,24 milréis/t-km mais baixas que as brasileiras; (3) taxa de retorno social marginal agregada de 4,9% (ligeiro subinvestimento); (4) 75% das linhas individualmente abaixo do limiar de eficiência; (5) custo de realocação equivalente a 3,4% do PIB. Contribuição: pioneirismo na aplicação de teoria dos jogos cooperativos e economia política positiva à história econômica latinoamericana.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Análise Crítica dos Achados</td>
<td style="text-align: left;">A principal ameaça à identificação é a ausência de controle por tamanho econômico provincial — províncias maiores (Minas, Bahia, Pernambuco) têm tanto mais deputados quanto mais atividade econômica e mais demanda por ferrovias. Sem instrumento ou design quasi-experimental, a correlação não distingue efetivamente poder político de demanda econômica. Na análise de tarifas, a ausência de controles de custos é uma lacuna relevante.</td>
<td style="text-align: left;">O autor responde à pergunta de forma parcialmente satisfatória. Pontos fortes: refutação empírica direta da hipótese dependentista; formalização clara do mecanismo político. Pontos vulneráveis: identificação causal frágil (correlação vs.&nbsp;causalidade no caso dos subsídios); pequena amostra na regressão de tarifas; métricas de retorno social dependentes de pressupostos sobre transporte contrafactual. A generalizabilidade é limitada a contextos de parlamentos centralizados com regra de maioria e colégios eleitorais geograficamente particionados.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Limitações</td>
<td style="text-align: left;">A premissa de que poder de votação → subsídios é plausível mas pode refletir endogeneidade (economias maiores → mais deputados → mais demanda ferroviária economicamente justificada). A análise contrafactual é explicitamente conjetural e não testável.</td>
<td style="text-align: left;"><strong>Reconhecidas pelos autores:</strong> desvios individuais da correlação prevista (ex.: Rio Grande do Sul) requerem análise mais detalhada do processo de formulação de políticas; a análise de retorno em corte transversal para 1887 não é ideal; os cenários contrafactuais são necessariamente conjeturais. <br> <strong>Não reconhecidas ou subestimadas:</strong> ausência de controle por tamanho econômico provincial no modelo de subsídios; potencial endogeneidade entre demanda econômica por ferrovias e representação política; a regressão de tarifas não controla por características operacionais das linhas; a medida de economias sociais depende de pressupostos fortes sobre elasticidade de demanda e transporte alternativo.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Perspectiva Teórica</td>
<td style="text-align: left;">A combinação de nova economia institucional (North) com teoria da escolha pública (Weingast, Shepsle) é coerente e foi pioneir na história econômica latinoamericana. A ontologia implícita é individualista-metodológica, com legisladores como atores estratégicos racionais — pressuposto razoável mas que abstrai dinâmicas de partido, executivo e pressão de grupos de interesse organizados.</td>
<td style="text-align: left;">Nova economia institucional (North); teoria da escolha pública e distributiva (Weingast, Shepsle, Buchanan-Tullock); análise de custo-benefício histórico (Fogel, Fishlow); teoria dos jogos cooperativos (Shapley-Shubik). A moldura é adequada à pergunta explicativa; a coerência entre ontologia individualista-racional e métodos quantitativos é alta.</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Principais Referências</td>
<td style="text-align: left;">O diálogo com a literatura dependentista é amplo e explícito; o diálogo com a literatura comparada de regulação ferroviária (além dos EUA) é limitado. A ausência de engajamento com a literatura sobre clientelismo e patrimonialismo brasileiro (Carvalho, Graham) representa lacuna relevante dado o contexto empírico.</td>
<td style="text-align: left;">Weingast, Shepsle &amp; Johnson (1981) — modelo de política distributiva; Fishlow (1965) — economias sociais ferroviárias nos EUA; Fogel (implícito na metodologia de social savings); Frank (1967), Evans (1979), Burns (1980) — dependentistas criticados; Bates &amp; Lien (1985) — modelo de monarquia absoluta e capital.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Observações</td>
<td style="text-align: left;">A abordagem pioneira do capítulo abre agenda relevante para a pesquisa em economia política histórica latinoamericana. Para o leitor com interesse em política distributiva, instituições legislativas e desenvolvimento econômico brasileiro, o texto é referência indispensável, especialmente pela aplicação do índice de Shapley-Shubik a dados históricos. Contudo, a análise seria consideravelmente fortalecida por uma estratégia de identificação mais robusta — por exemplo, um design de regressão de descontinuidade baseado em mudanças na representação parlamentar ou variação nos critérios de elegibilidade para garantias de dividendo.</td>
<td style="text-align: left;">A ausência de análise de mecanismo qualitativa (como rastreamento de processo em casos específicos de negociação de subsídio) é uma lacuna que o próprio autor reconhece marginalmente. A validade externa do argumento principal depende criticamente de o centralismo ser a variação institucional relevante, o que não é demonstrado por comparação sistemática. O argumento sobre regulação diferencial por propriedade é o mais robusto metodologicamente e dialoga diretamente com debates contemporâneos sobre regulação de serviços públicos e captura regulatória.</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("^(?:http:|https:)\/\/drganghe\.github\.io\/custom");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<a href="http://www.github.com/mancano-tales">Tales Mançano</a> ©
<script>document.write(new Date().getFullYear())</script>
</div>   
    <div class="nav-footer-center">
<p>Build on <a href="https://github.com/drganghe/quarto-academic-website-template">Quart Academic Website Template</a> adapted by <a href="http://drganghe.github.io">Dr.&nbsp;Gang He</a></p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/drganghe/quarto-academic-website-template" target="_blank">
      <i class="bi bi-github" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="https://bsky.app" target="_blank">
<p><i class="fa-brands fa-bluesky" aria-label="bluesky"></i></p>
</a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="../../posts.xml" target="_blank">
      <i class="bi bi-rss" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>