---
title: "About the EDUC-306B"
description: "What we learned in this course?"
date: "2026-01-02"
date-modified: "2026-01-15"
categories: [Courses, Syllabus, Political Economy, Classes] # Adicione suas categorias aqui
---

# Description

*EDUC 306B*: Global Education Policy & Organization. "The Politics of Education Policy" 

*Proposed Course Objectives*: The objectives of this course are (1) to introduce students to the nature of some current major debates in educational reforms from a political economy point of view; (2) to give students a grasp of various conceptions of the State—of the workings of the “political system” and the political structures in society; and, through this understanding, (3) to be able better to conduct policy analyses of education, interpret the meaning of existing educational structures and of educational reforms and gain insights into theories of educational change. Although most educational policy is developed within the context of the national State, in the past fifty years there have been important—and some say, increasing—political influences on national States from international organizations.  We will also analyze literature on globalization and global governance and try to come to some conclusions about the importance of those influences. By the end of the course, everyone should have a clear idea of how to analyze education policy through a political economy approach and with an explicit theory of the state.

# First Impressions (2026-01-01)

O cusrso est''a organiado em 18 seções que mesclam teorias mais abstratas sobre o Estado com discussões bastante aplicadas sobre políticas específicas, a disciplina alterna questões teóricas com estudos de caso. 

O curso começa com uma aula introdutoria sobre porque estado importa, vai para as teorias liberais e do mecano, depois cobre o debate entre institucionalistas e gramscianos,,pluralistas, raça, gênero, socialismo etc. Uma pergunta a ser feita para o Carnoy é "How many theories of State are there? What does a theory have to be to be considered a theory of the State?"

Carnoy faz muito bme o que podemos chamar de debate paradigmático da educação, educação não é nem só um investimento tal qual um investimento em capital produtivol, nem simplesmente uma forma de dominação e doutrinação das classes dominantes, nem apenas um instrumento redistributivo e de libertação, depede de qual educação se fala e embora um ou outro modelo educacional possa ser pretominante em determinado país reguão ou momento histórco ou a educação destinada a grupos específicos, geralmente vemos diversidades de educac'~ao e resuktadis


Class titles:

---

* Session 1, Week 1, Monday, January 5: 
**Why Does the State Matter in Educational Policy Analysis?**

* Session 2, Week 1, Wednesday, January 7: 
**Case Study 1: Educational Privatization in the Low-income Countries**
* Session 3, Week 2, Monday, January 12: 
**Theories of the State: Dependency Theory and Embedded Autonomy**
* Session 4, Week 2, Wednesday, January 14: 
**Case Study 2: Educational Privatization in Middle-and High-income Countries**

* Monday, January 12: **Martin Luther King Day**

* Session 5, Week 3, Wednesday, January 21: 
**Theories of the State: Liberal Common Good Theories and Markets**
* Session 6, Week 4, Monday, January 26: 
**Case Study 3: Public Sector Accountability Reforms (including Standards Reforms)**
* Session 7, Week 4, Wednesday, January 28: 
**Theories of the State: The Institutionalists versus the Gramscians**
* Session 8, Week 5, Monday, February 2: 
**Case Study 4: Vocational Education in Europe and Brazil**
* Session 9, Week 5, Wednesday, February 4: 
**Theories of the State: Educational Borrowing and Education and Legitimacy**
* Session 10, Week 6, Monday, February 9: 
**Case Study 5: Persistent Achievement Gaps across Race, Class, and Gender**
* Session 11, Week 6, Wednesday, February 11: 
**Theories of the State: Pluralists, Class Conflict, and Social Reproduction**
* Session 12, Week 7, Wednesday, February 18: 
**Theories of the State: The Racial State and Racial Capitalism**
* Session 13, Week 8, Monday, February 23: 
**Theories of the State: Gender and the State**
* Session 14, Week 8, Wednesday, February 25: 
**Case Study 6: PISA, TIMSS, and the Global Institutions**
* Session 15, Week 9, Monday, March 2: 
**Theories of the State: Globalization and the Decline of the Nation State?**
* Session 16, Week 9, Wednesday, March 4: 
**Case Study 7: Education in Transition in Cuba and China**
* Session 17, Week 10, Monday, March 9: 
**Theories of the State: Socialist States and States in Transition**
* Session 18, Week 10, Wednesday, March 11: 
**Course Wrap-up, Q&A, Discussion of Final Paper**

---

Classes Notes:

### Session 1: Why Does the State Matter in Educational Policy Analysis?

* [Carnoy1989](../Carnoy1989/Carnoy1989.qmd)

* [Carnoy2024-Ch3-Political-Economy-Education](../Carnoy2024Ch3.qmd)






####


It's hard to disagree with such broad statement, he basically says, well 

we can make it more standardized

private section is important for public education - private companies can compete with each other for creating the best textbooks


WHo is goint to compare and to those compariosons? The economists, right

Who came up with the commoc core? the governmente

Federal money is only 9% of the education budget, states get all the power from the thing.

Higher stantarde

state public sector reform in massachusets - introduces competition in the private sector, he doesnt understande textbook markets, only written for larger states.

He doesnt now how the markets work anyway - khan academy, what is he talking about

Selling idea - what is he theoyof the state? he akonwledge that the state that decides, but then he comes back adn pay for capitalism, when the educational system has very little to do with capitalism

why are we buying the texteb bookd

you are going to get a bad score.

that is not neoliberalism, sking the state to step in, merging difrent hings, why does he feels the need to merge that. Federela government and the associations

individual state regulatory capture is not good for competiotion


THEACHER TRAINING:::: that's why common core was not adopted -  that was the main problem, the teachers institutions - Massive teacher training -- thestes scores, the doesn't mention the training of theachers

california suspendede the test for three years before they could do that.




QUestion of money to train all those teachers to make sure that they cna implement this corriculum.

Gates he is biased in the power of government.

Why is he the one sharing thoughts in common core?

He cares about it, he will profit about it? Why is he?

Gates: state mathers -- opublic sector matthers - theories of state that matters -  various theories of state --  the state, part of state, politics, can have autonomy - the state can have aitonomy from politics,


make everything better for the system

the main problem is not the fact that he nevers mentions that you have to fund all of this, is that it's basically a thecnical problem, just introduce the best tecnology and solve diference --  in educatio he belives in off the shelves solutions also, and that is also a problem of the state that says that it's tecnical and never finantioal, he never mentions any of these.

state theories that says that all those theories are ideological, never allow theories core values.

any political debates knoledge we should know as a society, what is missing for the socierty.



education system is inehently politisl s pst of the sttate the political sustem becauso both in democratic and outhoritaion free market ans inven in state 

social mobility
---

Conforme discutido em [Carnoy1989](../2025-01-01-Evans1995-Embedded-Autonomy/)